Enfield: efd::NDQOpGen Class Reference
efd::NDQOpGen Class Reference
NDQOp specialized for generic gates.
#include <Nodes.h>
Public Types
enum IntrinsicKind { K_INTRINSIC_SWAP, K_INTRINSIC_REV_CX, K_INTRINSIC_LCX }
typedef NDQOpGen * Ref
typedef std::unique_ptr< NDQOpGen > uRef
Public Types inherited from efd::NDQOp
typedef NDQOp * Ref
typedef std::unique_ptr< NDQOp > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
void apply (NodeVisitor *visitor) override
Used by visitor classes.
IntrinsicKind getIntrinsicKind () const
Returns the intrinsic kind of this node.
bool isIntrinsic () const
Returns whether this node is in an intrinsic node.
Public Member Functions inherited from efd::NDQOp
virtual ~NDQOp ()
NDId::Ref getId () const
Gets the id.
void setId (NDId::uRef ref)
Sets the id.
NDList::Ref getArgs () const
Gets the arguments.
void setArgs (NDList::uRef ref)
Sets the arguments.
NDList::Ref getQArgs () const
Gets the quantum arguments.
void setQArgs (NDList::uRef ref)
Sets the quantum arguments.
bool isReset () const
Returns true if this is a reset node.
bool isBarrier () const
Returns true if this is a barrier node.
bool isMeasure () const
Returns true if this is a measure node.
bool isU () const
Returns true if this is a u node.
bool isCX () const
Returns true if this is a cx node.
bool isGeneric () const
Returns true if this is a generic node.
std::string getOperation () const override
Returns a std::string representation of the operation.
virtual uint32_t getChildNumber () const override
Returns the number of childrem of this node.
virtual std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode)
Creates a new instance of this node.
Static Public Member Functions inherited from efd::NDQOp
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
Protected Member Functions
NDQOpGen (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode)
NDQOpGen (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode, IntrinsicKind ik)
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
Protected Member Functions inherited from efd::NDQOp
NDQOp (Kind k, NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode)
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
Protected Attributes
IntrinsicKind mIK
The intrinsic kind of the node.
bool mIsIntrinsic
True if it is an intrinsic compiler function.
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Additional Inherited Members
Protected Types inherited from efd::NDQOp
enum ChildType { I_ID = 0, I_ARGS, I_QARGS }
Detailed Description
NDQOp specialized for generic gates.
Definition at line 930 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDQOpGen* efd::NDQOpGen::Ref
Definition at line 932 of file Nodes.h.
uRef
typedef std::unique_ptr<NDQOpGen> efd::NDQOpGen::uRef
Definition at line 933 of file Nodes.h.
Member Enumeration Documentation
IntrinsicKind
enum efd::NDQOpGen::IntrinsicKind
Enumerator
K_INTRINSIC_SWAP
K_INTRINSIC_REV_CX
K_INTRINSIC_LCX
Definition at line 935 of file Nodes.h.
Constructor & Destructor Documentation
NDQOpGen() [1/2]
efd::NDQOpGen::NDQOpGen (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode) protected
Definition at line 1135 of file Nodes.cpp.
NDQOpGen() [2/2]
efd::NDQOpGen::NDQOpGen (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode, IntrinsicKind ik) protected
Definition at line 1139 of file Nodes.cpp.
Member Function Documentation
apply()
void efd::NDQOpGen::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Implements efd::Node.
Definition at line 1144 of file Nodes.cpp.
References efd::NodeVisitor::visit().
ClassOf()
bool efd::NDQOpGen::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 1173 of file Nodes.cpp.
References efd::Node::getKind().
cloneImpl()
efd::Node::uRef efd::NDQOpGen::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Implements efd::Node.
Definition at line 1161 of file Nodes.cpp.
References Create().
Create()
efd::NDQOpGen::uRef efd::NDQOpGen::Create (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode) static
Creates a new instance of this node.
Definition at line 1177 of file Nodes.cpp.
Referenced by cloneImpl().
getIntrinsicKind()
efd::NDQOpGen::IntrinsicKind efd::NDQOpGen::getIntrinsicKind () const
Returns the intrinsic kind of this node.
Only to be used by intrinsic nodes.
Definition at line 1148 of file Nodes.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
Referenced by efd::SemanticVerifierVisitor::visit().
isIntrinsic()
bool efd::NDQOpGen::isIntrinsic () const
Returns whether this node is in an intrinsic node.
Definition at line 1157 of file Nodes.cpp.
Referenced by efd::SemanticVerifierVisitor::visit().
Member Data Documentation
mIK
IntrinsicKind efd::NDQOpGen::mIK protected
The intrinsic kind of the node.
Definition at line 943 of file Nodes.h.
mIsIntrinsic
bool efd::NDQOpGen::mIsIntrinsic protected
True if it is an intrinsic compiler function.
Definition at line 945 of file Nodes.h.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp