Enfield: efd::NodeVisitor Class Reference
efd::NodeVisitor Class Reference
Interface class to be used as a visitor.
#include <NodeVisitor.h>
Public Types
typedef NodeVisitor * Ref
Public Member Functions
virtual void visit (NDQasmVersion::Ref ref)
virtual void visit (NDInclude::Ref ref)
virtual void visit (NDRegDecl::Ref ref)
virtual void visit (NDGateDecl::Ref ref)
virtual void visit (NDOpaque::Ref ref)
virtual void visit (NDQOpMeasure::Ref ref)
virtual void visit (NDQOpReset::Ref ref)
virtual void visit (NDQOpU::Ref ref)
virtual void visit (NDQOpCX::Ref ref)
virtual void visit (NDQOpBarrier::Ref ref)
virtual void visit (NDQOpGen::Ref ref)
virtual void visit (NDBinOp::Ref ref)
virtual void visit (NDUnaryOp::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDList::Ref ref)
virtual void visit (NDStmtList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDIfStmt::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Detailed Description
Interface class to be used as a visitor.
Definition at line 9 of file NodeVisitor.h.
Member Typedef Documentation
Ref
typedef NodeVisitor* efd::NodeVisitor::Ref
Definition at line 11 of file NodeVisitor.h.
Member Function Documentation
visit() [1/21]
void efd::NodeVisitor::visit (NDQasmVersion::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor.
Definition at line 3 of file NodeVisitor.cpp.
Referenced by efd::NDValue< T >::apply(), efd::NDRegDecl::apply(), efd::NDIdRef::apply(), efd::NDList::apply(), efd::NDStmtList::apply(), efd::NDGOpList::apply(), efd::NDQasmVersion::apply(), efd::NDInclude::apply(), efd::NDGateSign::apply(), efd::NDGateDecl::apply(), efd::NDQOpReset::apply(), efd::NDQOpBarrier::apply(), efd::NDQOpMeasure::apply(), efd::NDQOpU::apply(), efd::NDQOpCX::apply(), efd::NDBinOp::apply(), efd::NDUnaryOp::apply(), efd::NDQOpGen::apply(), and efd::NDIfStmt::apply().
visit() [2/21]
void efd::NodeVisitor::visit (NDInclude::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor.
Definition at line 4 of file NodeVisitor.cpp.
visit() [3/21]
void efd::NodeVisitor::visit (NDRegDecl::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor, and efd::XbitToNumberVisitor.
Definition at line 5 of file NodeVisitor.cpp.
visit() [4/21]
void efd::NodeVisitor::visit (NDGateDecl::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor, efd::DependencyBuilderVisitor, and efd::XbitToNumberVisitor.
Definition at line 6 of file NodeVisitor.cpp.
visit() [5/21]
void efd::NodeVisitor::visit (NDOpaque::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor.
Definition at line 7 of file NodeVisitor.cpp.
visit() [6/21]
void efd::NodeVisitor::visit (NDQOpMeasure::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor, efd::NodeRenameVisitor, efd::SemanticVerifierVisitor, efd::FlattenVisitor, efd::StdSolutionImplPass, efd::UsedBitsVisitor, efd::ArchVerifierVisitor, and efd::RenameQbitVisitor.
Definition at line 8 of file NodeVisitor.cpp.
visit() [7/21]
void efd::NodeVisitor::visit (NDQOpReset::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor, efd::NodeRenameVisitor, efd::SemanticVerifierVisitor, efd::FlattenVisitor, efd::StdSolutionImplPass, efd::UsedBitsVisitor, efd::ArchVerifierVisitor, and efd::RenameQbitVisitor.
Definition at line 9 of file NodeVisitor.cpp.
visit() [8/21]
void efd::NodeVisitor::visit (NDQOpU::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor, efd::QModulefyVisitor, efd::NodeRenameVisitor, efd::SemanticVerifierVisitor, efd::FlattenVisitor, efd::StdSolutionImplPass, efd::UsedBitsVisitor, efd::ArchVerifierVisitor, and efd::RenameQbitVisitor.
Definition at line 10 of file NodeVisitor.cpp.
visit() [9/21]
void efd::NodeVisitor::visit (NDQOpCX::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor, efd::QModulefyVisitor, efd::DependencyBuilderVisitor, efd::NodeRenameVisitor, efd::SemanticVerifierVisitor, efd::FlattenVisitor, efd::StdSolutionImplPass, efd::UsedBitsVisitor, efd::ArchVerifierVisitor, efd::ReverseEdgesVisitor, and efd::RenameQbitVisitor.
Definition at line 11 of file NodeVisitor.cpp.
visit() [10/21]
void efd::NodeVisitor::visit (NDQOpBarrier::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor, efd::QModulefyVisitor, efd::NodeRenameVisitor, efd::SemanticVerifierVisitor, efd::FlattenVisitor, efd::StdSolutionImplPass, efd::UsedBitsVisitor, efd::ArchVerifierVisitor, and efd::RenameQbitVisitor.
Definition at line 12 of file NodeVisitor.cpp.
visit() [11/21]
void efd::NodeVisitor::visit (NDQOpGen::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor, efd::QModulefyVisitor, efd::DependencyBuilderVisitor, efd::NodeRenameVisitor, efd::SemanticVerifierVisitor, efd::FlattenVisitor, efd::StdSolutionImplPass, efd::UsedBitsVisitor, efd::ArchVerifierVisitor, efd::ReverseEdgesVisitor, efd::RenameQbitVisitor, and efd::InlineAllVisitor.
Definition at line 13 of file NodeVisitor.cpp.
visit() [12/21]
void efd::NodeVisitor::visit (NDBinOp::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor.
Definition at line 14 of file NodeVisitor.cpp.
visit() [13/21]
void efd::NodeVisitor::visit (NDUnaryOp::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor.
Definition at line 15 of file NodeVisitor.cpp.
visit() [14/21]
void efd::NodeVisitor::visit (NDIdRef::Ref ref) virtual
Definition at line 16 of file NodeVisitor.cpp.
visit() [15/21]
void efd::NodeVisitor::visit (NDList::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor, efd::StdSolutionImplPass, and efd::RenameQbitVisitor.
Definition at line 17 of file NodeVisitor.cpp.
visit() [16/21]
void efd::NodeVisitor::visit (NDStmtList::Ref ref) virtual
Reimplemented in efd::QModulefyVisitor.
Definition at line 18 of file NodeVisitor.cpp.
visit() [17/21]
void efd::NodeVisitor::visit (NDGOpList::Ref ref) virtual
Reimplemented in efd::DependencyBuilderVisitor.
Definition at line 19 of file NodeVisitor.cpp.
visit() [18/21]
void efd::NodeVisitor::visit (NDIfStmt::Ref ref) virtual
Reimplemented in efd::QArgsReplaceVisitor, efd::QModulefyVisitor, efd::DependencyBuilderVisitor, efd::NodeRenameVisitor, efd::SemanticVerifierVisitor, efd::FlattenVisitor, efd::StdSolutionImplPass, efd::UsedBitsVisitor, efd::ArchVerifierVisitor, efd::ReverseEdgesVisitor, and efd::InlineAllVisitor.
Definition at line 20 of file NodeVisitor.cpp.
visit() [19/21]
void efd::NodeVisitor::visit (NDValue< std::string >::Ref ref) virtual
Definition at line 21 of file NodeVisitor.cpp.
visit() [20/21]
void efd::NodeVisitor::visit (NDValue< IntVal >::Ref ref) virtual
Definition at line 22 of file NodeVisitor.cpp.
visit() [21/21]
void efd::NodeVisitor::visit (NDValue< RealVal >::Ref ref) virtual
Definition at line 23 of file NodeVisitor.cpp.
visitChildren()
void efd::NodeVisitor::visitChildren (Node::Ref ref)
Visits the children of ref.
Definition at line 25 of file NodeVisitor.cpp.
The documentation for this class was generated from the following files:
include/enfield/Analysis/NodeVisitor.h
lib/Analysis/NodeVisitor.cpp