Enfield: std Namespace Reference
std Namespace Reference
Functions
template<typename T , T first, T last>
string to_string (efd::EnumString< T, first, last > &val)
template<typename T >
string to_string (const efd::WrapperVal< T > &val)
Overloading std::to_string to work with efd::WrapperVal.
Function Documentation
to_string() [1/2]
template<typename T > string std::to_string (const efd::WrapperVal< T > & val)
Overloading std::to_string to work with efd::WrapperVal.
Definition at line 51 of file WrapperVal.h.
References efd::WrapperVal< T >::mStr.
to_string() [2/2]
template<typename T , T first, T last> string std::to_string (efd::EnumString< T, first, last > & val)
Definition at line 53 of file EnumString.h.
References efd::EnumString< T, first, last >::getStringValue().
Referenced by efd::WeightedGraph< T >::edgeToString(), efd::NDValue< T >::getOperation(), efd::Opt< T >::getStringVal(), efd::MappingToString(), efd::Stat< T >::toString(), efd::NDValue< T >::toString(), efd::Graph::vertexToString(), efd::UsedBitsVisitor::visit(), and efd::XbitToNumberVisitor::visit().