Enfield: efd::NDUnaryOp Class Reference
efd::NDUnaryOp Class Reference
Unary operation node.
#include <Nodes.h>
Public Types
enum UOpType {
UOP_SIN = 0, UOP_COS, UOP_TAN, UOP_EXP,
UOP_LN, UOP_SQRT, UOP_NEG
}
Unary operations available.
typedef NDUnaryOp * Ref
typedef std::unique_ptr< NDUnaryOp > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
Node::Ref getOperand () const
Gets the only operand.
void setOperand (Node::uRef ref)
Sets the only operand.
UOpType getUOpType () const
Returns the unary operation type.
bool isNeg () const
Returns whether this is an neg operation.
bool isSin () const
Returns whether this is an sin operation.
bool isCos () const
Returns whether this is an cos operation.
bool isTan () const
Returns whether this is an tan operation.
bool isExp () const
Returns whether this is an exp operation.
bool isLn () const
Returns whether this is an ln operation.
bool isSqrt () const
Returns whether this is an sqrt operation.
std::string getOperation () const override
Returns a std::string representation of the operation.
std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
uint32_t getChildNumber () const override
Returns the number of childrem of this node.
void apply (NodeVisitor *visitor) override
Used by visitor classes.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (UOpType t, Node::uRef oNode)
Creates a new instance of this node.
static uRef CreateNeg (Node::uRef oNode)
Creates a negative unary operand node.
static uRef CreateSin (Node::uRef oNode)
Creates a sin unary operand node.
static uRef CreateCos (Node::uRef oNode)
Creates a cos unary operand node.
static uRef CreateTan (Node::uRef oNode)
Creates a tan unary operand node.
static uRef CreateExp (Node::uRef oNode)
Creates a exp unary operand node.
static uRef CreateLn (Node::uRef oNode)
Creates a ln unary operand node.
static uRef CreateSqrt (Node::uRef oNode)
Creates a sqrt unary operand node.
Protected Types
enum ChildType { I_ONLY = 0 }
Protected Member Functions
NDUnaryOp (UOpType t, Node::uRef oNode)
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
Protected Attributes
UOpType mT
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
Unary operation node.
Definition at line 851 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDUnaryOp* efd::NDUnaryOp::Ref
Definition at line 858 of file Nodes.h.
uRef
typedef std::unique_ptr<NDUnaryOp> efd::NDUnaryOp::uRef
Definition at line 859 of file Nodes.h.
Member Enumeration Documentation
ChildType
enum efd::NDUnaryOp::ChildType protected
Enumerator
I_ONLY
Definition at line 853 of file Nodes.h.
UOpType
enum efd::NDUnaryOp::UOpType
Unary operations available.
Enumerator
UOP_SIN
UOP_COS
UOP_TAN
UOP_EXP
UOP_LN
UOP_SQRT
UOP_NEG
Definition at line 862 of file Nodes.h.
Constructor & Destructor Documentation
NDUnaryOp()
efd::NDUnaryOp::NDUnaryOp (UOpType t, Node::uRef oNode) protected
Definition at line 1294 of file Nodes.cpp.
References efd::Node::innerAddChild().
Member Function Documentation
apply()
void efd::NDUnaryOp::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Implements efd::Node.
Definition at line 1361 of file Nodes.cpp.
References efd::NodeVisitor::visit().
ClassOf()
bool efd::NDUnaryOp::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 1382 of file Nodes.cpp.
References efd::Node::getKind().
cloneImpl()
efd::Node::uRef efd::NDUnaryOp::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Implements efd::Node.
Definition at line 1298 of file Nodes.cpp.
References Create().
Create()
efd::NDUnaryOp::uRef efd::NDUnaryOp::Create (UOpType t, Node::uRef oNode) static
Creates a new instance of this node.
Definition at line 1386 of file Nodes.cpp.
Referenced by cloneImpl().
CreateCos()
efd::NDUnaryOp::uRef efd::NDUnaryOp::CreateCos (Node::uRef oNode) static
Creates a cos unary operand node.
Definition at line 1398 of file Nodes.cpp.
CreateExp()
efd::NDUnaryOp::uRef efd::NDUnaryOp::CreateExp (Node::uRef oNode) static
Creates a exp unary operand node.
Definition at line 1406 of file Nodes.cpp.
CreateLn()
efd::NDUnaryOp::uRef efd::NDUnaryOp::CreateLn (Node::uRef oNode) static
Creates a ln unary operand node.
Definition at line 1410 of file Nodes.cpp.
CreateNeg()
efd::NDUnaryOp::uRef efd::NDUnaryOp::CreateNeg (Node::uRef oNode) static
Creates a negative unary operand node.
Definition at line 1390 of file Nodes.cpp.
CreateSin()
efd::NDUnaryOp::uRef efd::NDUnaryOp::CreateSin (Node::uRef oNode) static
Creates a sin unary operand node.
Definition at line 1394 of file Nodes.cpp.
CreateSqrt()
efd::NDUnaryOp::uRef efd::NDUnaryOp::CreateSqrt (Node::uRef oNode) static
Creates a sqrt unary operand node.
Definition at line 1414 of file Nodes.cpp.
CreateTan()
efd::NDUnaryOp::uRef efd::NDUnaryOp::CreateTan (Node::uRef oNode) static
Creates a tan unary operand node.
Definition at line 1402 of file Nodes.cpp.
getChildNumber()
uint32_t efd::NDUnaryOp::getChildNumber () const override virtual
Returns the number of childrem of this node.
Implements efd::Node.
Definition at line 1357 of file Nodes.cpp.
getOperand()
efd::Node::Ref efd::NDUnaryOp::getOperand () const
Gets the only operand.
Definition at line 1302 of file Nodes.cpp.
getOperation()
std::string efd::NDUnaryOp::getOperation () const override virtual
Returns a std::string representation of the operation.
Reimplemented from efd::Node.
Definition at line 1342 of file Nodes.cpp.
References ERR, efd::EXIT_unknown_resource, and efd::ExitWith().
getUOpType()
efd::NDUnaryOp::UOpType efd::NDUnaryOp::getUOpType () const
Returns the unary operation type.
Definition at line 1310 of file Nodes.cpp.
isCos()
bool efd::NDUnaryOp::isCos () const
Returns whether this is an cos operation.
Definition at line 1318 of file Nodes.cpp.
isExp()
bool efd::NDUnaryOp::isExp () const
Returns whether this is an exp operation.
Definition at line 1326 of file Nodes.cpp.
isLn()
bool efd::NDUnaryOp::isLn () const
Returns whether this is an ln operation.
Definition at line 1330 of file Nodes.cpp.
isNeg()
bool efd::NDUnaryOp::isNeg () const
Returns whether this is an neg operation.
Definition at line 1338 of file Nodes.cpp.
isSin()
bool efd::NDUnaryOp::isSin () const
Returns whether this is an sin operation.
Definition at line 1314 of file Nodes.cpp.
isSqrt()
bool efd::NDUnaryOp::isSqrt () const
Returns whether this is an sqrt operation.
Definition at line 1334 of file Nodes.cpp.
isTan()
bool efd::NDUnaryOp::isTan () const
Returns whether this is an tan operation.
Definition at line 1322 of file Nodes.cpp.
setOperand()
void efd::NDUnaryOp::setOperand (Node::uRef ref)
Sets the only operand.
Definition at line 1306 of file Nodes.cpp.
toString()
std::string efd::NDUnaryOp::toString (bool pretty = false) const override virtual
Returns a std::string representation of this Node and its childrem.
Implements efd::Node.
Definition at line 1365 of file Nodes.cpp.
References efd::Node::toString().
Member Data Documentation
mT
UOpType efd::NDUnaryOp::mT protected
Definition at line 873 of file Nodes.h.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp