Enfield: efd::LayerBasedOrderingWrapperPass Class Reference
efd::LayerBasedOrderingWrapperPass Class Reference abstract
Interface for ordering the program by a specific layer-based ordering.
#include <LayerBasedOrderingWrapperPass.h>
Public Types
typedef std::unique_ptr< LayerBasedOrderingWrapperPass > uRef
typedef LayerBasedOrderingWrapperPass * Ref
Public Types inherited from efd::PassT< LayerBasedOrdering >
typedef PassT< LayerBasedOrdering > * Ref
typedef std::shared_ptr< PassT< LayerBasedOrdering > > sRef
typedef std::unique_ptr< PassT< LayerBasedOrdering > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
bool run (QModule *qmod) override
Runs the pass in the given QModule and returns true if it has modified qmod.
Public Member Functions inherited from efd::PassT< LayerBasedOrdering >
PassT ()
LayerBasedOrdering getData () const
Gets the resulting data.
LayerBasedOrdering & getData ()
Public Member Functions inherited from efd::Pass
Kind getKind () const
Gets the kind of this pass.
Protected Member Functions
uint32_t getNodeId (Node::Ref ref)
virtual Ordering generate (CircuitGraph &graph)=0
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Protected Attributes
std::unordered_map< Node::Ref, uint32_t > mStmtId
Protected Attributes inherited from efd::PassT< LayerBasedOrdering >
LayerBasedOrdering mData
Additional Inherited Members
Static Public Member Functions inherited from efd::PassT< LayerBasedOrdering >
static bool ClassOf (Pass *ref)
Detailed Description
Interface for ordering the program by a specific layer-based ordering.
One layer is a set of instructions that, theoreticaly, can be executed in parallel. i.e. does not need the same qubits.
Definition at line 22 of file LayerBasedOrderingWrapperPass.h.
Member Typedef Documentation
Ref
typedef LayerBasedOrderingWrapperPass* efd::LayerBasedOrderingWrapperPass::Ref
Definition at line 25 of file LayerBasedOrderingWrapperPass.h.
uRef
typedef std::unique_ptr<LayerBasedOrderingWrapperPass> efd::LayerBasedOrderingWrapperPass::uRef
Definition at line 24 of file LayerBasedOrderingWrapperPass.h.
Member Function Documentation
generate()
virtual Ordering efd::LayerBasedOrderingWrapperPass::generate (CircuitGraph & graph) protected pure virtual
Implemented in efd::CNOTLBOWrapperPass.
getNodeId()
uint32_t efd::LayerBasedOrderingWrapperPass::getNodeId (Node::Ref ref) protected
Definition at line 5 of file LayerBasedOrderingWrapperPass.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), mStmtId, and efd::Node::toString().
Referenced by efd::CNOTLBOWrapperPass::generate().
run()
bool efd::LayerBasedOrderingWrapperPass::run (QModule * qmod) override virtual
Runs the pass in the given QModule and returns true if it has modified qmod.
Implements efd::Pass.
Definition at line 15 of file LayerBasedOrderingWrapperPass.cpp.
References efd::QModule::orderby(), efd::QModule::stmt_begin(), and efd::QModule::stmt_end().
Member Data Documentation
mStmtId
std::unordered_map<Node::Ref, uint32_t> efd::LayerBasedOrderingWrapperPass::mStmtId protected
Definition at line 28 of file LayerBasedOrderingWrapperPass.h.
Referenced by getNodeId().
The documentation for this class was generated from the following files:
include/enfield/Transform/LayerBasedOrderingWrapperPass.h
lib/Transform/LayerBasedOrderingWrapperPass.cpp