Enfield: efd::SwapCostEstimator Struct Reference
efd::SwapCostEstimator Struct Reference abstract
Interface for estimating the number of swaps in phase 2.
#include <BoundedMappingTreeQAllocator.h>
Public Types
typedef SwapCostEstimator * Ref
typedef std::unique_ptr< SwapCostEstimator > uRef
Public Member Functions
SwapCostEstimator ()
void setGraph (Graph::Ref g)
Sets the Graph.
uint32_t estimate (const Mapping &fromM, const Mapping &toM)
Estimates the number of swaps to go from fromM to .
Protected Member Functions
void checkGraphSet ()
virtual void preprocess ()=0
virtual uint32_t estimateImpl (const Mapping &fromM, const Mapping &toM)=0
Protected Attributes
Graph::Ref mG
Detailed Description
Interface for estimating the number of swaps in phase 2.
Definition at line 112 of file BoundedMappingTreeQAllocator.h.
Member Typedef Documentation
Ref
typedef SwapCostEstimator* efd::SwapCostEstimator::Ref
Definition at line 113 of file BoundedMappingTreeQAllocator.h.
uRef
typedef std::unique_ptr<SwapCostEstimator> efd::SwapCostEstimator::uRef
Definition at line 114 of file BoundedMappingTreeQAllocator.h.
Constructor & Destructor Documentation
SwapCostEstimator()
SwapCostEstimator::SwapCostEstimator ()
Definition at line 68 of file BoundedMappingTreeQAllocator.cpp.
Member Function Documentation
checkGraphSet()
void SwapCostEstimator::checkGraphSet () protected
Definition at line 80 of file BoundedMappingTreeQAllocator.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), and mG.
Referenced by estimate().
estimate()
uint32_t SwapCostEstimator::estimate (const Mapping & fromM, const Mapping & toM)
Estimates the number of swaps to go from fromM to .
Definition at line 75 of file BoundedMappingTreeQAllocator.cpp.
References checkGraphSet(), and estimateImpl().
estimateImpl()
virtual uint32_t efd::SwapCostEstimator::estimateImpl (const Mapping & fromM, const Mapping & toM) protected pure virtual
Implemented in efd::GeoDistanceSwapCEstimator.
Referenced by estimate().
preprocess()
virtual void efd::SwapCostEstimator::preprocess () protected pure virtual
Implemented in efd::GeoDistanceSwapCEstimator.
Referenced by setGraph().
setGraph()
void SwapCostEstimator::setGraph (Graph::Ref g)
Sets the Graph.
Definition at line 70 of file BoundedMappingTreeQAllocator.cpp.
References mG, and preprocess().
Member Data Documentation
mG
Graph::Ref efd::SwapCostEstimator::mG protected
Definition at line 124 of file BoundedMappingTreeQAllocator.h.
Referenced by checkGraphSet(), and setGraph().
The documentation for this struct was generated from the following files:
include/enfield/Transform/Allocators/BoundedMappingTreeQAllocator.h
lib/Transform/Allocators/BoundedMappingTreeQAllocator.cpp