Enfield: efd::NDGateDecl Class Reference
efd::NDGateDecl Class Reference
Node for declaration of quantum gates.
#include <Nodes.h>
Public Types
typedef NDGateDecl * Ref
typedef std::unique_ptr< NDGateDecl > uRef
Public Types inherited from efd::NDGateSign
typedef NDGateSign * Ref
typedef std::unique_ptr< NDGateSign > uRef
Public Types inherited from efd::NDDecl
typedef NDDecl * Ref
typedef std::unique_ptr< NDDecl > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
NDGOpList::Ref getGOpList () const
Gets the goplist node.
void setGOpList (NDGOpList::uRef ref)
Sets the goplist node.
std::string getOperation () const override
Returns a std::string representation of the operation.
std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
uint32_t getChildNumber () const override
Returns the number of childrem of this node.
void apply (NodeVisitor *visitor) override
Used by visitor classes.
Public Member Functions inherited from efd::NDGateSign
bool isOpaque () const
Returns true if this is an opaque gate.
NDList::Ref getArgs () const
Gets the args node.
void setArgs (NDList::uRef ref)
Sets the args node.
NDList::Ref getQArgs () const
Gets the qargs node.
void setQArgs (NDList::uRef ref)
Sets the qargs node.
Public Member Functions inherited from efd::NDDecl
NDId::Ref getId () const
Gets the id node.
void setId (NDId::uRef ref)
Sets the id node.
bool isReg () const
Returns true if this is a register declaration.
bool isGate () const
Returns true if this is a gate declaration.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode, NDGOpList::uRef gopNode)
Creates a new instance of this node.
Static Public Member Functions inherited from efd::NDGateSign
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode)
Creates a new instance of this node.
Static Public Member Functions inherited from efd::NDDecl
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
Protected Types
enum ChildType { I_GOPLIST = 3 }
Protected Types inherited from efd::NDGateSign
enum ChildType { I_ARGS = 1, I_QARGS }
Protected Types inherited from efd::NDDecl
enum ChildType { I_ID = 0 }
Protected Member Functions
NDGateDecl (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode, NDGOpList::uRef gopNode)
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
Protected Member Functions inherited from efd::NDGateSign
NDGateSign (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode)
NDGateSign (Kind k, NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode)
Protected Member Functions inherited from efd::NDDecl
NDDecl (Kind k, NDId::uRef idNode)
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
Additional Inherited Members
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
Node for declaration of quantum gates.
Definition at line 543 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDGateDecl* efd::NDGateDecl::Ref
Definition at line 545 of file Nodes.h.
uRef
typedef std::unique_ptr<NDGateDecl> efd::NDGateDecl::uRef
Definition at line 546 of file Nodes.h.
Member Enumeration Documentation
ChildType
enum efd::NDGateDecl::ChildType protected
Enumerator
I_GOPLIST
Definition at line 549 of file Nodes.h.
Constructor & Destructor Documentation
NDGateDecl()
efd::NDGateDecl::NDGateDecl (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode, NDGOpList::uRef gopNode) protected
Definition at line 789 of file Nodes.cpp.
References efd::Node::innerAddChild().
Member Function Documentation
apply()
void efd::NDGateDecl::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Reimplemented from efd::NDGateSign.
Definition at line 820 of file Nodes.cpp.
References efd::NodeVisitor::visit().
ClassOf()
bool efd::NDGateDecl::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 847 of file Nodes.cpp.
References efd::Node::getKind().
cloneImpl()
efd::Node::uRef efd::NDGateDecl::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Reimplemented from efd::NDGateSign.
Definition at line 795 of file Nodes.cpp.
References Create().
Create()
efd::NDGateDecl::uRef efd::NDGateDecl::Create (NDId::uRef idNode, NDList::uRef aNode, NDList::uRef qaNode, NDGOpList::uRef gopNode) static
Creates a new instance of this node.
Definition at line 851 of file Nodes.cpp.
Referenced by cloneImpl().
getChildNumber()
uint32_t efd::NDGateDecl::getChildNumber () const override virtual
Returns the number of childrem of this node.
Reimplemented from efd::NDGateSign.
Definition at line 816 of file Nodes.cpp.
getGOpList()
efd::NDGOpList::Ref efd::NDGateDecl::getGOpList () const
Gets the goplist node.
Definition at line 804 of file Nodes.cpp.
Referenced by efd::InlineGate().
getOperation()
std::string efd::NDGateDecl::getOperation () const override virtual
Returns a std::string representation of the operation.
Reimplemented from efd::NDGateSign.
Definition at line 812 of file Nodes.cpp.
setGOpList()
void efd::NDGateDecl::setGOpList (NDGOpList::uRef ref)
Sets the goplist node.
Definition at line 808 of file Nodes.cpp.
toString()
std::string efd::NDGateDecl::toString (bool pretty = false) const override virtual
Returns a std::string representation of this Node and its childrem.
Reimplemented from efd::NDGateSign.
Definition at line 824 of file Nodes.cpp.
References efd::Node::isEmpty(), and efd::Node::toString().
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp