Enfield: efd::StdSolutionQAllocator Class Reference
efd::StdSolutionQAllocator Class Reference abstract
An abstract allocator that builds the solution based on a StdSolution.
#include <StdSolutionQAllocator.h>
Public Types
typedef StdSolutionQAllocator * Ref
typedef std::unique_ptr< StdSolutionQAllocator > uRef
Public Types inherited from efd::QbitAllocator
typedef QbitAllocator * Ref
typedef std::unique_ptr< QbitAllocator > uRef
typedef std::vector< std::string > BasisVector
typedef DependencyBuilder::DepsVector DepsVector
typedef DependencyBuilder::DepsVector::iterator Iterator
Public Types inherited from efd::PassT< Mapping >
typedef PassT< Mapping > * Ref
typedef std::shared_ptr< PassT< Mapping > > sRef
typedef std::unique_ptr< PassT< Mapping > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
StdSolutionQAllocator (ArchGraph::sRef archGraph)
Public Member Functions inherited from efd::QbitAllocator
bool run (QModule::Ref qmod) override
void setInlineAll (BasisVector basis={})
Flags the QbitAllocator to inline all gates, but those inside the basis vector, before mapping.
void setDontInline ()
Flags the QbitAllocator not to inline.
Public Member Functions inherited from efd::PassT< Mapping >
PassT ()
Mapping getData () const
Gets the resulting data.
Mapping & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Protected Member Functions
virtual StdSolution buildStdSolution (QModule::Ref qmod)=0
Executes the allocation algorithm after the preprocessing.
Mapping allocate (QModule::Ref qmod) override
Executes the allocation algorithm after the preprocessing.
Protected Member Functions inherited from efd::QbitAllocator
QbitAllocator (ArchGraph::sRef archGraph)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Additional Inherited Members
Static Public Member Functions inherited from efd::PassT< Mapping >
static bool ClassOf (Pass *ref)
Protected Attributes inherited from efd::QbitAllocator
bool mInlineAll
ArchGraph::sRef mArchGraph
BasisVector mBasis
QModule::Ref mMod
uint32_t mVQubits
uint32_t mPQubits
Protected Attributes inherited from efd::PassT< Mapping >
Mapping mData
Detailed Description
An abstract allocator that builds the solution based on a StdSolution.
It runs buildStdSolution for getting an StdSolution, and then processes it along with the QModule inserting and replacing instructions where needed.
Definition at line 45 of file StdSolutionQAllocator.h.
Member Typedef Documentation
Ref
typedef StdSolutionQAllocator* efd::StdSolutionQAllocator::Ref
Definition at line 47 of file StdSolutionQAllocator.h.
uRef
typedef std::unique_ptr<StdSolutionQAllocator> efd::StdSolutionQAllocator::uRef
Definition at line 48 of file StdSolutionQAllocator.h.
Constructor & Destructor Documentation
StdSolutionQAllocator()
StdSolutionQAllocator::StdSolutionQAllocator (ArchGraph::sRef archGraph)
Definition at line 182 of file StdSolutionQAllocator.cpp.
Member Function Documentation
allocate()
Mapping StdSolutionQAllocator::allocate (QModule::Ref qmod) override protected virtual
Executes the allocation algorithm after the preprocessing.
Implements efd::QbitAllocator.
Definition at line 185 of file StdSolutionQAllocator.cpp.
References buildStdSolution(), efd::QbitAllocator::mMod, and efd::PassCache::Run().
buildStdSolution()
virtual StdSolution efd::StdSolutionQAllocator::buildStdSolution (QModule::Ref qmod) protected pure virtual
Executes the allocation algorithm after the preprocessing.
Implemented in efd::SimpleQAllocator, efd::IBMQAllocator, efd::DynprogQAllocator, and efd::GreedyCktQAllocator.
Referenced by allocate().
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/StdSolutionQAllocator.h
lib/Transform/Allocators/StdSolutionQAllocator.cpp