Enfield: lib/Transform/Allocators/Simple/RandomMappingFinder.cpp File Reference
RandomMappingFinder.cpp File Reference
#include "enfield/Transform/Allocators/Simple/RandomMappingFinder.h"
#include <ctime>
#include <algorithm>
#include <chrono>
#include <random>
Functions
int rnd (int i)
Variables
efd::Opt< uint32_t > Seed ("seed", "Seed to be used in random algorithms.", std::chrono::system_clock::now().time_since_epoch().count(), false)
efd::Stat< uint32_t > SeedStat ("seed", "Seed used in the random allocator.")
Function Documentation
rnd()
int rnd (int i)
Definition at line 13 of file RandomMappingFinder.cpp.
References Seed.
Referenced by efd::RandomMappingFinder::find().
Variable Documentation
Seed
efd::Opt<uint32_t> Seed("seed", "Seed to be used in random algorithms.", std::chrono::system_clock::now().time_since_epoch().count(), false)
Referenced by efd::IBMQAllocator::buildStdSolution(), efd::RandomMappingFinder::find(), and rnd().
SeedStat
efd::Stat<uint32_t> SeedStat("seed", "Seed used in the random allocator.")
Referenced by efd::RandomMappingFinder::find().