Enfield: efd::QModulefyVisitor Class Reference
efd::QModulefyVisitor Class Reference
Public Member Functions
QModulefyVisitor (QModule &qmod)
void visit (NDQasmVersion::Ref ref) override
void visit (NDInclude::Ref ref) override
void visit (NDRegDecl::Ref ref) override
void visit (NDGateDecl::Ref ref) override
void visit (NDOpaque::Ref ref) override
void visit (NDQOpMeasure::Ref ref) override
void visit (NDQOpReset::Ref ref) override
void visit (NDQOpU::Ref ref) override
void visit (NDQOpCX::Ref ref) override
void visit (NDQOpBarrier::Ref ref) override
void visit (NDQOpGen::Ref ref) override
void visit (NDIfStmt::Ref ref) override
void visit (NDStmtList::Ref ref) override
Public Member Functions inherited from efd::NodeVisitor
virtual void visit (NDBinOp::Ref ref)
virtual void visit (NDUnaryOp::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Public Attributes
QModule & mMod
NDGateDecl::Ref mCurGate
NDInclude::Ref mCurIncl
Additional Inherited Members
Public Types inherited from efd::NodeVisitor
typedef NodeVisitor * Ref
Detailed Description
Definition at line 199 of file Utils.cpp.
Constructor & Destructor Documentation
QModulefyVisitor()
efd::QModulefyVisitor::QModulefyVisitor (QModule & qmod) inline
Definition at line 209 of file Utils.cpp.
Member Function Documentation
visit() [1/13]
void efd::QModulefyVisitor::visit (NDQasmVersion::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 264 of file Utils.cpp.
References efd::Node::clone(), efd::NDStmtList::Create(), efd::NDQasmVersion::Create(), and efd::NDQasmVersion::getVersion().
visit() [2/13]
void efd::QModulefyVisitor::visit (NDInclude::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 273 of file Utils.cpp.
References efd::Node::clone(), efd::NDStmtList::Create(), efd::NDInclude::Create(), and efd::NDInclude::getFilename().
visit() [3/13]
void efd::QModulefyVisitor::visit (NDRegDecl::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 283 of file Utils.cpp.
References efd::Node::clone().
visit() [4/13]
void efd::QModulefyVisitor::visit (NDGateDecl::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 287 of file Utils.cpp.
References efd::Node::clone().
visit() [5/13]
void efd::QModulefyVisitor::visit (NDOpaque::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 297 of file Utils.cpp.
References efd::Node::clone().
visit() [6/13]
void efd::QModulefyVisitor::visit (NDQOpMeasure::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 302 of file Utils.cpp.
References efd::Node::clone().
visit() [7/13]
void efd::QModulefyVisitor::visit (NDQOpReset::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 307 of file Utils.cpp.
References efd::Node::clone().
visit() [8/13]
void efd::QModulefyVisitor::visit (NDQOpU::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 312 of file Utils.cpp.
References efd::Node::clone().
visit() [9/13]
void efd::QModulefyVisitor::visit (NDQOpCX::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 317 of file Utils.cpp.
References efd::Node::clone().
visit() [10/13]
void efd::QModulefyVisitor::visit (NDQOpBarrier::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 321 of file Utils.cpp.
References efd::Node::clone().
visit() [11/13]
void efd::QModulefyVisitor::visit (NDQOpGen::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 326 of file Utils.cpp.
visit() [12/13]
void efd::QModulefyVisitor::visit (NDIfStmt::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 331 of file Utils.cpp.
visit() [13/13]
void efd::QModulefyVisitor::visit (NDStmtList::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 336 of file Utils.cpp.
Member Data Documentation
mCurGate
NDGateDecl::Ref efd::QModulefyVisitor::mCurGate
Definition at line 206 of file Utils.cpp.
mCurIncl
NDInclude::Ref efd::QModulefyVisitor::mCurIncl
Definition at line 207 of file Utils.cpp.
mMod
QModule& efd::QModulefyVisitor::mMod
Definition at line 204 of file Utils.cpp.
The documentation for this class was generated from the following file:
lib/Transform/Utils.cpp