Enfield: efd::NDIfStmt Class Reference
efd::NDIfStmt Class Reference
Node for conditional statement.
#include <Nodes.h>
Public Types
enum ChildType { I_COND_ID = 0, I_COND_N, I_QOP }
typedef NDIfStmt * Ref
typedef std::unique_ptr< NDIfStmt > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
NDId::Ref getCondId () const
Gets the id inside the conditional.
void setCondId (NDId::uRef ref)
Sets the id inside the conditional.
NDInt::Ref getCondN () const
Gets the int inside the conditional.
void setCondN (NDInt::uRef ref)
Sets the int inside the conditional.
NDQOp::Ref getQOp () const
Gets the qop.
void setQOp (NDQOp::uRef ref)
Sets the qop.
std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
std::string getOperation () const override
Returns a std::string representation of the operation.
uint32_t getChildNumber () const override
Returns the number of childrem of this node.
void apply (NodeVisitor *visitor) override
Used by visitor classes.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (NDId::uRef cidNode, NDInt::uRef nNode, NDQOp::uRef qopNode)
Creates a new instance of this node.
Protected Member Functions
NDIfStmt (NDId::uRef cidNode, NDInt::uRef nNode, NDQOp::uRef qopNode)
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
Additional Inherited Members
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
Node for conditional statement.
Definition at line 968 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDIfStmt* efd::NDIfStmt::Ref
Definition at line 970 of file Nodes.h.
uRef
typedef std::unique_ptr<NDIfStmt> efd::NDIfStmt::uRef
Definition at line 971 of file Nodes.h.
Member Enumeration Documentation
ChildType
enum efd::NDIfStmt::ChildType
Enumerator
I_COND_ID
I_COND_N
I_QOP
Definition at line 973 of file Nodes.h.
Constructor & Destructor Documentation
NDIfStmt()
efd::NDIfStmt::NDIfStmt (NDId::uRef cidNode, NDInt::uRef nNode, NDQOp::uRef qopNode) protected
Definition at line 513 of file Nodes.cpp.
References efd::Node::innerAddChild().
Member Function Documentation
apply()
void efd::NDIfStmt::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Implements efd::Node.
Definition at line 555 of file Nodes.cpp.
References efd::NodeVisitor::visit().
ClassOf()
bool efd::NDIfStmt::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 580 of file Nodes.cpp.
References efd::Node::getKind().
cloneImpl()
efd::Node::uRef efd::NDIfStmt::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Implements efd::Node.
Definition at line 520 of file Nodes.cpp.
References Create().
Create()
efd::NDIfStmt::uRef efd::NDIfStmt::Create (NDId::uRef cidNode, NDInt::uRef nNode, NDQOp::uRef qopNode) static
Creates a new instance of this node.
Definition at line 584 of file Nodes.cpp.
Referenced by cloneImpl().
getChildNumber()
uint32_t efd::NDIfStmt::getChildNumber () const override virtual
Returns the number of childrem of this node.
Implements efd::Node.
Definition at line 551 of file Nodes.cpp.
getCondId()
efd::NDId::Ref efd::NDIfStmt::getCondId () const
Gets the id inside the conditional.
Definition at line 527 of file Nodes.cpp.
Referenced by efd::UsedBitsVisitor::visit().
getCondN()
efd::NDInt::Ref efd::NDIfStmt::getCondN () const
Gets the int inside the conditional.
Definition at line 535 of file Nodes.cpp.
getOperation()
std::string efd::NDIfStmt::getOperation () const override virtual
Returns a std::string representation of the operation.
Reimplemented from efd::Node.
Definition at line 576 of file Nodes.cpp.
getQOp()
efd::NDQOp::Ref efd::NDIfStmt::getQOp () const
Gets the qop.
Definition at line 543 of file Nodes.cpp.
Referenced by efd::InlineAllVisitor::visit(), efd::ReverseEdgesVisitor::visit(), efd::ArchVerifierVisitor::visit(), efd::UsedBitsVisitor::visit(), efd::StdSolutionImplPass::visit(), efd::SemanticVerifierVisitor::visit(), efd::NodeRenameVisitor::visit(), and efd::QArgsReplaceVisitor::visit().
setCondId()
void efd::NDIfStmt::setCondId (NDId::uRef ref)
Sets the id inside the conditional.
Definition at line 531 of file Nodes.cpp.
setCondN()
void efd::NDIfStmt::setCondN (NDInt::uRef ref)
Sets the int inside the conditional.
Definition at line 539 of file Nodes.cpp.
setQOp()
void efd::NDIfStmt::setQOp (NDQOp::uRef ref)
Sets the qop.
Definition at line 547 of file Nodes.cpp.
toString()
std::string efd::NDIfStmt::toString (bool pretty = false) const override virtual
Returns a std::string representation of this Node and its childrem.
Implements efd::Node.
Definition at line 559 of file Nodes.cpp.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp