Enfield: efd::ArchVerifierPass Class Reference
efd::ArchVerifierPass Class Reference
Verifies if the CNOT relations between every qubit respects the architecture constraints.
#include <ArchVerifierPass.h>
Public Types
typedef ArchVerifierPass * Ref
typedef std::unique_ptr< ArchVerifierPass > uRef
Public Types inherited from efd::PassT< bool >
typedef PassT< bool > * Ref
typedef std::shared_ptr< PassT< bool > > sRef
typedef std::unique_ptr< PassT< bool > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
ArchVerifierPass (ArchGraph::sRef ag)
bool run (QModule *qmod) override
Runs the pass in the given QModule and returns true if it has modified qmod.
Public Member Functions inherited from efd::PassT< bool >
PassT ()
bool getData () const
Gets the resulting data.
bool & getData ()
Public Member Functions inherited from efd::Pass
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create (ArchGraph::sRef ag)
Create a dynamic instance of this class.
Static Public Member Functions inherited from efd::PassT< bool >
static bool ClassOf (Pass *ref)
Additional Inherited Members
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Protected Attributes inherited from efd::PassT< bool >
bool mData
Detailed Description
Verifies if the CNOT relations between every qubit respects the architecture constraints.
Definition at line 12 of file ArchVerifierPass.h.
Member Typedef Documentation
Ref
typedef ArchVerifierPass* efd::ArchVerifierPass::Ref
Definition at line 14 of file ArchVerifierPass.h.
uRef
typedef std::unique_ptr<ArchVerifierPass> efd::ArchVerifierPass::uRef
Definition at line 15 of file ArchVerifierPass.h.
Constructor & Destructor Documentation
ArchVerifierPass()
ArchVerifierPass::ArchVerifierPass (ArchGraph::sRef ag)
Definition at line 150 of file ArchVerifierPass.cpp.
References efd::PassT< bool >::mData.
Referenced by Create().
Member Function Documentation
Create()
ArchVerifierPass::uRef ArchVerifierPass::Create (ArchGraph::sRef ag) static
Create a dynamic instance of this class.
Definition at line 167 of file ArchVerifierPass.cpp.
References ArchVerifierPass().
Referenced by efd::Compile().
run()
bool ArchVerifierPass::run (QModule * qmod) override virtual
Runs the pass in the given QModule and returns true if it has modified qmod.
Implements efd::Pass.
Definition at line 154 of file ArchVerifierPass.cpp.
References efd::PassT< bool >::mData, efd::ArchVerifierVisitor::mSuccess, efd::QModule::stmt_begin(), and efd::QModule::stmt_end().
The documentation for this class was generated from the following files:
include/enfield/Transform/ArchVerifierPass.h
lib/Transform/ArchVerifierPass.cpp