Enfield: efd::CircuitGraph::CircuitNode Struct Reference
efd::CircuitGraph::CircuitNode Struct Reference
Representation of a quantum operation.
#include <CircuitGraph.h>
Public Types
typedef CircuitNode * Ref
typedef std::unique_ptr< CircuitNode > uRef
typedef std::shared_ptr< CircuitNode > sRef
Public Member Functions
Node::Ref node ()
Returns the Node::Ref associated with this circuit node.
uint32_t numberOfXbits ()
Returns the number of Xbit's in this node.
bool isOutputNode ()
True if this node has reached the end (output node).
bool isInputNode ()
True if this node is in the beginning (input node).
bool isGateNode ()
True if this node is in the middle (gate node).
std::vector< uint32_t > getXbitsIds ()
Returns the Xbit ID's in this node.
Friends
class CircuitGraph
Detailed Description
Representation of a quantum operation.
Definition at line 36 of file CircuitGraph.h.
Member Typedef Documentation
Ref
typedef CircuitNode* efd::CircuitGraph::CircuitNode::Ref
Definition at line 38 of file CircuitGraph.h.
sRef
typedef std::shared_ptr<CircuitNode> efd::CircuitGraph::CircuitNode::sRef
Definition at line 40 of file CircuitGraph.h.
uRef
typedef std::unique_ptr<CircuitNode> efd::CircuitGraph::CircuitNode::uRef
Definition at line 39 of file CircuitGraph.h.
Member Function Documentation
getXbitsIds()
std::vector< uint32_t > CircuitGraph::CircuitNode::getXbitsIds ()
Returns the Xbit ID's in this node.
Definition at line 73 of file CircuitGraph.cpp.
Referenced by efd::GreedyCktQAllocator::executeAllocation().
isGateNode()
bool CircuitGraph::CircuitNode::isGateNode ()
True if this node is in the middle (gate node).
Definition at line 69 of file CircuitGraph.cpp.
References isInputNode(), and isOutputNode().
Referenced by efd::GreedyCktQAllocator::executeAllocation(), efd::CNOTLBOWrapperPass::generate(), and efd::SemanticVerifierVisitor::visit().
isInputNode()
bool CircuitGraph::CircuitNode::isInputNode ()
True if this node is in the beginning (input node).
Definition at line 65 of file CircuitGraph.cpp.
Referenced by efd::CircuitGraph::Iterator::back(), and isGateNode().
isOutputNode()
bool CircuitGraph::CircuitNode::isOutputNode ()
True if this node has reached the end (output node).
Definition at line 61 of file CircuitGraph.cpp.
Referenced by efd::CNOTLBOWrapperPass::generate(), isGateNode(), efd::CircuitGraph::Iterator::next(), and efd::SemanticVerifierPass::run().
node()
Node::Ref CircuitGraph::CircuitNode::node ()
Returns the Node::Ref associated with this circuit node.
Definition at line 53 of file CircuitGraph.cpp.
Referenced by efd::GreedyCktQAllocator::executeAllocation(), efd::CNOTLBOWrapperPass::generate(), and efd::SemanticVerifierVisitor::visit().
numberOfXbits()
uint32_t CircuitGraph::CircuitNode::numberOfXbits ()
Returns the number of Xbit's in this node.
Definition at line 57 of file CircuitGraph.cpp.
Referenced by efd::GreedyCktQAllocator::executeAllocation(), and efd::CNOTLBOWrapperPass::generate().
Friends And Related Function Documentation
CircuitGraph
friend class CircuitGraph friend
Definition at line 70 of file CircuitGraph.h.
The documentation for this struct was generated from the following files:
include/enfield/Transform/CircuitGraph.h
lib/Transform/CircuitGraph.cpp