Enfield: efd::ReverseEdgesPass Class Reference
efd::ReverseEdgesPass Class Reference
Pass that reverses the edges accordingly with the architecture Graph.
#include <ReverseEdgesPass.h>
Public Types
typedef ReverseEdgesPass * Ref
typedef std::unique_ptr< ReverseEdgesPass > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
bool run (QModule::Ref qmod) override
Public Member Functions inherited from efd::PassT< void >
PassT ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create (ArchGraph::sRef graph)
Create an instance of this class.
Static Public Member Functions inherited from efd::PassT< void >
static bool ClassOf (Pass *ref)
Static Public Attributes
static uint8_t ID = 0
Additional Inherited Members
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Detailed Description
Pass that reverses the edges accordingly with the architecture Graph.
Definition at line 10 of file ReverseEdgesPass.h.
Member Typedef Documentation
Ref
typedef ReverseEdgesPass* efd::ReverseEdgesPass::Ref
Definition at line 12 of file ReverseEdgesPass.h.
uRef
typedef std::unique_ptr<ReverseEdgesPass> efd::ReverseEdgesPass::uRef
Definition at line 13 of file ReverseEdgesPass.h.
Member Function Documentation
Create()
efd::ReverseEdgesPass::uRef efd::ReverseEdgesPass::Create (ArchGraph::sRef graph) static
Create an instance of this class.
Definition at line 97 of file ReverseEdgesPass.cpp.
Referenced by efd::Compile().
run()
bool efd::ReverseEdgesPass::run (QModule::Ref qmod) override
Definition at line 80 of file ReverseEdgesPass.cpp.
References efd::ReverseEdgesVisitor::mRevVector, efd::QModule::replaceStatement(), efd::QModule::stmt_begin(), and efd::QModule::stmt_end().
Member Data Documentation
ID
uint8_t efd::ReverseEdgesPass::ID = 0 static
Definition at line 15 of file ReverseEdgesPass.h.
The documentation for this class was generated from the following files:
include/enfield/Transform/ReverseEdgesPass.h
lib/Transform/ReverseEdgesPass.cpp