Enfield: efd::NDDecl Class Reference
efd::NDDecl Class Reference
Node for declaration of registers (concrete and quantum).
#include <Nodes.h>
Public Types
typedef NDDecl * Ref
typedef std::unique_ptr< NDDecl > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
NDId::Ref getId () const
Gets the id node.
void setId (NDId::uRef ref)
Sets the id node.
bool isReg () const
Returns true if this is a register declaration.
bool isGate () const
Returns true if this is a gate declaration.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
virtual std::string getOperation () const
Returns a std::string representation of the operation.
virtual uint32_t getChildNumber () const =0
Returns the number of childrem of this node.
virtual std::string toString (bool pretty=false) const =0
Returns a std::string representation of this Node and its childrem.
virtual void apply (NodeVisitor *visitor)=0
Used by visitor classes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
Protected Types
enum ChildType { I_ID = 0 }
Protected Member Functions
NDDecl (Kind k, NDId::uRef idNode)
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
virtual Node::uRef cloneImpl () const =0
Clones the current node (deep copy).
Additional Inherited Members
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
Node for declaration of registers (concrete and quantum).
Definition at line 218 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDDecl* efd::NDDecl::Ref
Definition at line 220 of file Nodes.h.
uRef
typedef std::unique_ptr<NDDecl> efd::NDDecl::uRef
Definition at line 221 of file Nodes.h.
Member Enumeration Documentation
ChildType
enum efd::NDDecl::ChildType protected
Enumerator
I_ID
Definition at line 224 of file Nodes.h.
Constructor & Destructor Documentation
NDDecl()
efd::NDDecl::NDDecl (Kind k, NDId::uRef idNode) protected
Definition at line 182 of file Nodes.cpp.
References efd::Node::innerAddChild().
Member Function Documentation
ClassOf()
bool efd::NDDecl::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 202 of file Nodes.cpp.
References efd::Node::getKind().
getId()
efd::NDId::Ref efd::NDDecl::getId () const
Gets the id node.
Definition at line 186 of file Nodes.cpp.
Referenced by efd::DependencyBuilder::getDepsVector(), efd::XbitToNumber::getQbitMap(), efd::XbitToNumber::getQStrId(), efd::XbitToNumber::getQUId(), efd::QModule::getQVar(), and efd::XbitToNumberVisitor::visit().
isGate()
bool efd::NDDecl::isGate () const
Returns true if this is a gate declaration.
Definition at line 198 of file Nodes.cpp.
isReg()
bool efd::NDDecl::isReg () const
Returns true if this is a register declaration.
Definition at line 194 of file Nodes.cpp.
setId()
void efd::NDDecl::setId (NDId::uRef ref)
Sets the id node.
Definition at line 190 of file Nodes.cpp.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp