Enfield: efd::ReverseEdgesVisitor Class Reference
efd::ReverseEdgesVisitor Class Reference
Public Member Functions
ReverseEdgesVisitor (ArchGraph::sRef g)
void visit (NDQOpCX::Ref ref) override
void visit (NDQOpGen::Ref ref) override
void visit (NDIfStmt::Ref ref) override
Public Member Functions inherited from efd::NodeVisitor
virtual void visit (NDQasmVersion::Ref ref)
virtual void visit (NDInclude::Ref ref)
virtual void visit (NDRegDecl::Ref ref)
virtual void visit (NDGateDecl::Ref ref)
virtual void visit (NDOpaque::Ref ref)
virtual void visit (NDQOpMeasure::Ref ref)
virtual void visit (NDQOpReset::Ref ref)
virtual void visit (NDQOpU::Ref ref)
virtual void visit (NDQOpBarrier::Ref ref)
virtual void visit (NDBinOp::Ref ref)
virtual void visit (NDUnaryOp::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDList::Ref ref)
virtual void visit (NDStmtList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Public Attributes
std::vector< std::pair< Node::Ref, Node::uRef > > mRevVector
Additional Inherited Members
Public Types inherited from efd::NodeVisitor
typedef NodeVisitor * Ref
Detailed Description
Definition at line 11 of file ReverseEdgesPass.cpp.
Constructor & Destructor Documentation
ReverseEdgesVisitor()
efd::ReverseEdgesVisitor::ReverseEdgesVisitor (ArchGraph::sRef g) inline
Definition at line 22 of file ReverseEdgesPass.cpp.
Member Function Documentation
visit() [1/3]
void efd::ReverseEdgesVisitor::visit (NDQOpCX::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 46 of file ReverseEdgesPass.cpp.
References efd::NDQOpCX::getLhs(), efd::NDQOpCX::getRhs(), and efd::Node::toString().
visit() [2/3]
void efd::ReverseEdgesVisitor::visit (NDQOpGen::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 55 of file ReverseEdgesPass.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), efd::Node::getChild(), efd::NDList::getChildNumber(), efd::NDQOp::getId(), efd::NDQOp::getQArgs(), efd::NDValue< T >::getVal(), efd::Node::toString(), and efd::NDQOp::toString().
visit() [3/3]
void efd::ReverseEdgesVisitor::visit (NDIfStmt::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 73 of file ReverseEdgesPass.cpp.
References efd::Node::apply(), and efd::NDIfStmt::getQOp().
Member Data Documentation
mRevVector
std::vector<std::pair<Node::Ref, Node::uRef> > efd::ReverseEdgesVisitor::mRevVector
Definition at line 21 of file ReverseEdgesPass.cpp.
Referenced by efd::ReverseEdgesPass::run().
The documentation for this class was generated from the following file:
lib/Transform/ReverseEdgesPass.cpp