Enfield: efd::WeightedGraph< T > Class Template Reference
efd::WeightedGraph< T > Class Template Reference
#include <WeightedGraph.h>
Public Types
typedef WeightedGraph< T > * Ref
typedef std::unique_ptr< WeightedGraph< T > > uRef
typedef std::shared_ptr< WeightedGraph< T > > sRef
Public Types inherited from efd::Graph
enum Kind { K_GRAPH, K_WEIGHTED, K_ARCH }
enum Type { Directed, Undirected }
typedef Graph * Ref
typedef std::unique_ptr< Graph > uRef
typedef std::shared_ptr< Graph > sRef
Public Member Functions
WeightedGraph (uint32_t n, Type ty=Undirected)
void putEdge (uint32_t i, uint32_t j, T w)
Insert the edge (i, j) with weight w(i, j) = w.
void setW (uint32_t i, uint32_t j, T w)
Sets the weight of an edge (i, j).
T getW (uint32_t i, uint32_t j) const
Gets the weight of an edge (i, j).
Public Member Functions inherited from efd::Graph
Graph (uint32_t n, Type ty=Undirected)
uint32_t inDegree (uint32_t i) const
Return the degree entering the vertex i.
uint32_t outDegree (uint32_t i) const
Return the degree leaving the vertex i.
uint32_t size () const
Return the number of vertices.
std::set< uint32_t > & succ (uint32_t i)
Return the set of succesors of some vertex i.
std::set< uint32_t > & pred (uint32_t i)
Return the set of predecessors of some vertex i.
std::set< uint32_t > adj (uint32_t i) const
Return the set of adjacent vertices of some vertex i.
void putEdge (uint32_t i, uint32_t j)
Inserts an edge (i, j) in the successor's list and an edge (j, i) in the predecessor's list.
bool hasEdge (uint32_t i, uint32_t j)
Returns true whether it has an edge (i, j).
bool isWeighted () const
Returns true if this is a weighted graph.
bool isArch () const
Returns true if this is an architecture graph.
bool isDirectedGraph () const
Returns true if this is a directed graph.
std::string dotify (std::string name="Dump") const
Converts itself to a 'dot' graph representation.
Static Public Member Functions
static bool ClassOf (const Graph *g)
Returns true if g is of this type.
static uRef Create (uint32_t n, Type ty=Undirected)
Encapsulates the creation of a new Graph.
static uRef Read (std::string filepath, Type ty=Undirected)
Parses the file filename into a Graph representation.
static uRef ReadString (std::string graphStr, Type ty=Undirected)
Parses the string graphStr into a Graph representation.
Static Public Member Functions inherited from efd::Graph
static bool ClassOf (const Graph *g)
Returns true if g is of this type.
static uRef Create (uint32_t n, Type ty=Undirected)
Encapsulates the creation of a new Graph.
static uRef Read (std::string filepath, Type ty=Undirected)
Parses the file filename into a Graph representation.
static uRef ReadString (std::string graphStr, Type ty=Undirected)
Parses the string graphStr into a Graph representation.
Protected Member Functions
std::string edgeToString (uint32_t i, uint32_t j, std::string op) const override
Protected Member Functions inherited from efd::Graph
Graph (Kind k, uint32_t n, Type ty=Undirected)
virtual std::string vertexToString (uint32_t i) const
Additional Inherited Members
Protected Attributes inherited from efd::Graph
Kind mK
uint32_t mN
Type mTy
std::vector< std::set< uint32_t > > mSuccessors
std::vector< std::set< uint32_t > > mPredecessors
Detailed Description
template<typename T>
class efd::WeightedGraph< T >
Definition at line 13 of file WeightedGraph.h.
Member Typedef Documentation
Ref
template<typename T> typedef WeightedGraph<T>* efd::WeightedGraph< T >::Ref
Definition at line 15 of file WeightedGraph.h.
sRef
template<typename T> typedef std::shared_ptr<WeightedGraph<T> > efd::WeightedGraph< T >::sRef
Definition at line 17 of file WeightedGraph.h.
uRef
template<typename T> typedef std::unique_ptr<WeightedGraph<T> > efd::WeightedGraph< T >::uRef
Definition at line 16 of file WeightedGraph.h.
Constructor & Destructor Documentation
WeightedGraph()
template<typename T > efd::WeightedGraph< T >::WeightedGraph (uint32_t n, Type ty = Undirected)
Definition at line 52 of file WeightedGraph.h.
Member Function Documentation
ClassOf()
template<typename T > bool efd::WeightedGraph< T >::ClassOf (const Graph * g) static
Returns true if g is of this type.
Definition at line 96 of file WeightedGraph.h.
References efd::Graph::isWeighted().
Create()
template<typename T > efd::WeightedGraph< T >::uRef efd::WeightedGraph< T >::Create (uint32_t n, Type ty = Undirected) static
Encapsulates the creation of a new Graph.
Definition at line 101 of file WeightedGraph.h.
Referenced by efd::DependencyGraphBuilderPass::run().
edgeToString()
template<typename T > std::string efd::WeightedGraph< T >::edgeToString (uint32_t i, uint32_t j, std::string op) const override protected virtual
Reimplemented from efd::Graph.
Definition at line 55 of file WeightedGraph.h.
References std::to_string().
getW()
template<typename T > T efd::WeightedGraph< T >::getW (uint32_t i, uint32_t j) const
Gets the weight of an edge (i, j).
Definition at line 84 of file WeightedGraph.h.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
putEdge()
template<typename T > void efd::WeightedGraph< T >::putEdge (uint32_t i, uint32_t j, T w)
Insert the edge (i, j) with weight w(i, j) = w.
Definition at line 62 of file WeightedGraph.h.
References efd::Graph::putEdge().
Read()
template<typename T > efd::WeightedGraph< T >::uRef efd::WeightedGraph< T >::Read (std::string filepath, Type ty = Undirected) static
Parses the file filename into a Graph representation.
Definition at line 120 of file WeightedGraph.h.
ReadString()
template<typename T > efd::WeightedGraph< T >::uRef efd::WeightedGraph< T >::ReadString (std::string graphStr, Type ty = Undirected) static
Parses the string graphStr into a Graph representation.
Definition at line 126 of file WeightedGraph.h.
setW()
template<typename T > void efd::WeightedGraph< T >::setW (uint32_t i, uint32_t j, T w)
Sets the weight of an edge (i, j).
Definition at line 72 of file WeightedGraph.h.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
The documentation for this class was generated from the following file:
include/enfield/Support/WeightedGraph.h