Enfield: efd::DynprogDepSolver Class Reference
efd::DynprogDepSolver Class Reference
Implementation of DepSolverQAllocator that uses dynamic programming to obtain an optimal solution.
#include <DynprogDepSolver.h>
Public Types
typedef DynprogDepSolver * Ref
typedef std::unique_ptr< DynprogDepSolver > uRef
Public Types inherited from efd::QbitAllocator
typedef QbitAllocator * Ref
typedef std::unique_ptr< QbitAllocator > uRef
typedef Solution::Mapping Mapping
typedef std::vector< std::string > BasisVector
typedef DependencyBuilder::DepsSet DepsSet
typedef DependencyBuilder::DepsSet::iterator Iterator
Public Types inherited from efd::PassT< Solution >
typedef PassT< Solution > * Ref
typedef std::shared_ptr< PassT< Solution > > sRef
typedef std::unique_ptr< PassT< Solution > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Static Public Member Functions
static uRef Create (ArchGraph::sRef archGraph)
Create a new instance of this class.
Static Public Member Functions inherited from efd::PassT< Solution >
static bool ClassOf (Pass *ref)
Protected Member Functions
DynprogDepSolver (ArchGraph::sRef archGraph)
uint32_t getIntermediateV (uint32_t u, uint32_t v)
Gets the intermediate vertex between 'u' and 'v', if there exists one.
Solution solve (DepsSet &deps) override
Solves the allocation problem, returning a solution.
Protected Member Functions inherited from efd::DepSolverQAllocator
DepSolverQAllocator (ArchGraph::sRef archGraph)
virtual Solution executeAllocation (QModule::Ref qmod) override
Executes the allocation algorithm after the preprocessing.
Protected Member Functions inherited from efd::QbitAllocator
QbitAllocator (ArchGraph::sRef archGraph)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Additional Inherited Members
Public Member Functions inherited from efd::QbitAllocator
bool run (QModule::Ref qmod) override
void setInlineAll (BasisVector basis={})
Flags the QbitAllocator to inline all gates, but those inside the basis vector, before mapping.
void setDontInline ()
Flags the QbitAllocator not to inline.
Public Member Functions inherited from efd::PassT< Solution >
PassT ()
Solution getData () const
Gets the resulting data.
Solution & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Protected Attributes inherited from efd::QbitAllocator
bool mInlineAll
ArchGraph::sRef mArchGraph
BasisVector mBasis
QModule::Ref mMod
uint32_t mVQubits
uint32_t mPQubits
Protected Attributes inherited from efd::PassT< Solution >
Solution mData
Detailed Description
Implementation of DepSolverQAllocator that uses dynamic programming to obtain an optimal solution.
Definition at line 14 of file DynprogDepSolver.h.
Member Typedef Documentation
Ref
typedef DynprogDepSolver* efd::DynprogDepSolver::Ref
Definition at line 16 of file DynprogDepSolver.h.
uRef
typedef std::unique_ptr<DynprogDepSolver> efd::DynprogDepSolver::uRef
Definition at line 17 of file DynprogDepSolver.h.
Constructor & Destructor Documentation
DynprogDepSolver()
efd::DynprogDepSolver::DynprogDepSolver (ArchGraph::sRef archGraph) protected
Definition at line 210 of file DynprogDepSolver.cpp.
References efd::DepSolverQAllocator::DepSolverQAllocator().
Referenced by Create().
Member Function Documentation
Create()
efd::DynprogDepSolver::uRef efd::DynprogDepSolver::Create (ArchGraph::sRef archGraph) static
Create a new instance of this class.
Definition at line 215 of file DynprogDepSolver.cpp.
References DynprogDepSolver().
getIntermediateV()
uint32_t efd::DynprogDepSolver::getIntermediateV (uint32_t u, uint32_t v) protected
Gets the intermediate vertex between 'u' and 'v', if there exists one.
Definition at line 41 of file DynprogDepSolver.cpp.
References efd::QbitAllocator::mArchGraph, efd::Graph::pred(), efd::Graph::succ(), and UNREACH.
solve()
efd::Solution efd::DynprogDepSolver::solve (DepsSet & deps) override protected virtual
Solves the allocation problem, returning a solution.
Implements efd::DepSolverQAllocator.
Definition at line 54 of file DynprogDepSolver.cpp.
References Val::cost, efd::BFSPathFinder::Create(), efd::ExpTSFinder::ExpTSFinder(), efd::BFSPathFinder::find(), efd::ExpTSFinder::find(), efd::GenAssignment(), efd::Dependencies::getSize(), efd::Opt< T >::getVal(), efd::Graph::hasEdge(), efd::ArchGraph::isReverseEdge(), efd::Operation::K_OP_CNOT, efd::Operation::K_OP_LCNOT, efd::Operation::K_OP_REV, efd::Operation::K_OP_SWAP, LCXCost, efd::QbitAllocator::mArchGraph, efd::ExpTSFinder::mAssigns, efd::Dependencies::mCallPoint, efd::Solution::mCost, efd::Dependencies::mDeps, efd::Dep::mFrom, efd::Solution::mInitial, efd::Solution::mOpSeqs, efd::Dep::mTo, efd::Operation::mW, efd::Dependencies::operator[](), Val::parent, Val::pId, RevCost, efd::Graph::size(), SwapCost, efd::Swap::u, UNREACH, and efd::Swap::v.
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/DynprogDepSolver.h
lib/Transform/Allocators/DynprogDepSolver.cpp