Enfield: efd::NDInclude Class Reference
efd::NDInclude Class Reference
Node used to parse another file.
#include <Nodes.h>
Public Types
typedef NDInclude * Ref
typedef std::unique_ptr< NDInclude > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
NDString::Ref getFilename () const
Gets the node that holds the filename.
void setFilename (NDString::uRef ref)
Sets the node that holds the filename.
Node::Ref getInnerAST () const
Gets the node that holds the statements.
void setInnerAST (Node::uRef ref)
Sets the node that holds the statements.
std::string getOperation () const override
Returns a std::string representation of the operation.
std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
uint32_t getChildNumber () const override
Returns the number of childrem of this node.
void apply (NodeVisitor *visitor) override
Used by visitor classes.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (NDId::uRef fNode, Node::uRef astNode)
Creates a new instance of this node.
Protected Types
enum ChildType { I_FILE = 0, I_INNER_AST }
Protected Member Functions
NDInclude (NDId::uRef fNode, Node::uRef astNode)
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
Additional Inherited Members
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
Node used to parse another file.
The AST from this other file is a child of this node.
Definition at line 461 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDInclude* efd::NDInclude::Ref
Definition at line 463 of file Nodes.h.
uRef
typedef std::unique_ptr<NDInclude> efd::NDInclude::uRef
Definition at line 464 of file Nodes.h.
Member Enumeration Documentation
ChildType
enum efd::NDInclude::ChildType protected
Enumerator
I_FILE
I_INNER_AST
Definition at line 467 of file Nodes.h.
Constructor & Destructor Documentation
NDInclude()
efd::NDInclude::NDInclude (NDId::uRef fNode, Node::uRef astNode) protected
Definition at line 652 of file Nodes.cpp.
References efd::Node::innerAddChild().
Member Function Documentation
apply()
void efd::NDInclude::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Implements efd::Node.
Definition at line 671 of file Nodes.cpp.
References efd::NodeVisitor::visit().
ClassOf()
bool efd::NDInclude::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 702 of file Nodes.cpp.
References efd::Node::getKind().
cloneImpl()
efd::Node::uRef efd::NDInclude::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Implements efd::Node.
Definition at line 658 of file Nodes.cpp.
References Create().
Create()
efd::NDInclude::uRef efd::NDInclude::Create (NDId::uRef fNode, Node::uRef astNode) static
Creates a new instance of this node.
Definition at line 706 of file Nodes.cpp.
Referenced by cloneImpl(), and efd::QModulefyVisitor::visit().
getChildNumber()
uint32_t efd::NDInclude::getChildNumber () const override virtual
Returns the number of childrem of this node.
Implements efd::Node.
Definition at line 667 of file Nodes.cpp.
getFilename()
efd::NDString::Ref efd::NDInclude::getFilename () const
Gets the node that holds the filename.
Definition at line 675 of file Nodes.cpp.
Referenced by efd::QModulefyVisitor::visit().
getInnerAST()
efd::Node::Ref efd::NDInclude::getInnerAST () const
Gets the node that holds the statements.
Definition at line 683 of file Nodes.cpp.
getOperation()
std::string efd::NDInclude::getOperation () const override virtual
Returns a std::string representation of the operation.
Reimplemented from efd::Node.
Definition at line 663 of file Nodes.cpp.
setFilename()
void efd::NDInclude::setFilename (NDString::uRef ref)
Sets the node that holds the filename.
Definition at line 679 of file Nodes.cpp.
setInnerAST()
void efd::NDInclude::setInnerAST (Node::uRef ref)
Sets the node that holds the statements.
Definition at line 687 of file Nodes.cpp.
toString()
std::string efd::NDInclude::toString (bool pretty = false) const override virtual
Returns a std::string representation of this Node and its childrem.
Implements efd::Node.
Definition at line 691 of file Nodes.cpp.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp