Enfield: efd::NDValue< T > Class Template Reference
efd::NDValue< T > Class Template Reference
Node for literal types.
#include <Nodes.h>
Public Types
typedef NDValue * Ref
typedef std::unique_ptr< NDValue > uRef
typedef std::shared_ptr< NDValue< T > > NDRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
T getVal () const
Returns a copy to the setted value.
std::string getOperation () const override
Returns a std::string representation of the operation.
std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
uint32_t getChildNumber () const override
Returns the number of childrem of this node.
void apply (NodeVisitor *visitor) override
Used by visitor classes.
template<>
bool ClassOf (const Node *node)
template<>
void apply (NodeVisitor::Ref visitor)
template<>
bool ClassOf (const Node *node)
template<>
void apply (NodeVisitor::Ref visitor)
template<>
bool ClassOf (const Node *node)
template<>
std::string getOperation () const
Returns a std::string representation of the operation.
template<>
void apply (NodeVisitor::Ref visitor)
template<>
std::string toString (bool pretty) const
Returns a std::string representation of this Node and its childrem.
template<>
bool ClassOf (const Node *node)
template<>
void apply (NodeVisitor *visitor)
Used by visitor classes.
template<>
bool ClassOf (const Node *node)
template<>
void apply (NodeVisitor *visitor)
Used by visitor classes.
template<>
bool ClassOf (const Node *node)
template<>
std::string getOperation () const
Returns a std::string representation of the operation.
template<>
std::string toString (bool pretty) const
Returns a std::string representation of this Node and its childrem.
template<>
void apply (NodeVisitor *visitor)
Used by visitor classes.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (T val)
Creates a new instance of this node.
Protected Member Functions
NDValue (T val)
bool equalsImpl (Node::Ref ref) const override
Extend the 'equals' implementation by implementing this method.
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
template<>
NDValue (efd::IntVal val)
template<>
NDValue (efd::RealVal val)
template<>
NDValue (std::string val)
template<>
NDValue (IntVal val)
template<>
NDValue (RealVal val)
template<>
NDValue (std::string val)
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
Protected Attributes
T mVal
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
template<typename T>
class efd::NDValue< T >
Node for literal types.
Definition at line 164 of file Nodes.h.
Member Typedef Documentation
NDRef
template<typename T > typedef std::shared_ptr< NDValue<T> > efd::NDValue< T >::NDRef
Definition at line 177 of file Nodes.h.
Ref
template<typename T > typedef NDValue* efd::NDValue< T >::Ref
Definition at line 166 of file Nodes.h.
uRef
template<typename T > typedef std::unique_ptr<NDValue> efd::NDValue< T >::uRef
Definition at line 167 of file Nodes.h.
Constructor & Destructor Documentation
NDValue() [1/7]
template<typename T > efd::NDValue< T >::NDValue (T val) protected
NDValue() [2/7]
template<> efd::NDValue< efd::IntVal >::NDValue (efd::IntVal val) protected
Definition at line 128 of file Nodes.cpp.
NDValue() [3/7]
template<> efd::NDValue< efd::RealVal >::NDValue (efd::RealVal val) protected
Definition at line 143 of file Nodes.cpp.
NDValue() [4/7]
template<> efd::NDValue< std::string >::NDValue (std::string val) protected
Definition at line 158 of file Nodes.cpp.
NDValue() [5/7]
template<> efd::NDValue< IntVal >::NDValue (IntVal val) protected
NDValue() [6/7]
template<> efd::NDValue< RealVal >::NDValue (RealVal val) protected
NDValue() [7/7]
template<> efd::NDValue< std::string >::NDValue (std::string val) protected
Member Function Documentation
apply() [1/7]
template<> void efd::NDValue< efd::IntVal >::apply (NodeVisitor::Ref visitor)
Definition at line 137 of file Nodes.cpp.
References efd::NodeVisitor::visit().
apply() [2/7]
template<> void efd::NDValue< efd::RealVal >::apply (NodeVisitor::Ref visitor)
Definition at line 152 of file Nodes.cpp.
References efd::NodeVisitor::visit().
apply() [3/7]
template<> void efd::NDValue< std::string >::apply (NodeVisitor::Ref visitor)
Definition at line 172 of file Nodes.cpp.
References efd::NodeVisitor::visit().
apply() [4/7]
template<typename T > void efd::NDValue< T >::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Implements efd::Node.
apply() [5/7]
template<> void efd::NDValue< IntVal >::apply (NodeVisitor * visitor) virtual
Used by visitor classes.
Implements efd::Node.
apply() [6/7]
template<> void efd::NDValue< RealVal >::apply (NodeVisitor * visitor) virtual
Used by visitor classes.
Implements efd::Node.
apply() [7/7]
template<> void efd::NDValue< std::string >::apply (NodeVisitor * visitor) virtual
Used by visitor classes.
Implements efd::Node.
ClassOf() [1/7]
template<> bool efd::NDValue< efd::IntVal >::ClassOf (const Node * node)
Definition at line 132 of file Nodes.cpp.
References efd::Node::getKind().
ClassOf() [2/7]
template<> bool efd::NDValue< efd::RealVal >::ClassOf (const Node * node)
Definition at line 147 of file Nodes.cpp.
References efd::Node::getKind().
ClassOf() [3/7]
template<> bool efd::NDValue< std::string >::ClassOf (const Node * node)
Definition at line 162 of file Nodes.cpp.
References efd::Node::getKind().
ClassOf() [4/7]
template<typename T > bool efd::NDValue< T >::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 1048 of file Nodes.h.
References efd::Node::getKind().
ClassOf() [5/7]
template<> bool efd::NDValue< IntVal >::ClassOf (const Node * node)
ClassOf() [6/7]
template<> bool efd::NDValue< RealVal >::ClassOf (const Node * node)
ClassOf() [7/7]
template<> bool efd::NDValue< std::string >::ClassOf (const Node * node)
cloneImpl()
template<typename T > efd::Node::uRef efd::NDValue< T >::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Implements efd::Node.
Definition at line 1043 of file Nodes.h.
Create()
template<typename T > efd::NDValue< T >::uRef efd::NDValue< T >::Create (T val) static
Creates a new instance of this node.
Definition at line 1055 of file Nodes.h.
Referenced by efd::XbitToNumberVisitor::visit().
equalsImpl()
template<typename T > bool efd::NDValue< T >::equalsImpl (Node::Ref ref) const override protected virtual
Extend the 'equals' implementation by implementing this method.
Reimplemented from efd::Node.
Definition at line 1014 of file Nodes.h.
References efd::dynCast().
getChildNumber()
template<typename T > uint32_t efd::NDValue< T >::getChildNumber () const override virtual
Returns the number of childrem of this node.
Implements efd::Node.
Definition at line 1038 of file Nodes.h.
getOperation() [1/3]
template<> std::string efd::NDValue< std::string >::getOperation () const virtual
Returns a std::string representation of the operation.
Reimplemented from efd::Node.
Definition at line 167 of file Nodes.cpp.
getOperation() [2/3]
template<typename T > std::string efd::NDValue< T >::getOperation () const override virtual
Returns a std::string representation of the operation.
Reimplemented from efd::Node.
Definition at line 1028 of file Nodes.h.
References std::to_string().
getOperation() [3/3]
template<> std::string efd::NDValue< std::string >::getOperation () const virtual
Returns a std::string representation of the operation.
Reimplemented from efd::Node.
getVal()
template<typename T > T efd::NDValue< T >::getVal () const
Returns a copy to the setted value.
Definition at line 1023 of file Nodes.h.
Referenced by efd::DependencyBuilder::getDepsVector(), efd::XbitToNumber::getQbitMap(), efd::XbitToNumber::getQStrId(), efd::XbitToNumber::getQUId(), efd::QModule::getQVar(), efd::InlineGate(), efd::QModule::toString(), efd::InlineAllVisitor::visit(), efd::ReverseEdgesVisitor::visit(), efd::UsedBitsVisitor::visit(), efd::XbitToNumberVisitor::visit(), and efd::DependencyBuilderVisitor::visit().
toString() [1/3]
template<> std::string efd::NDValue< std::string >::toString (bool pretty) const virtual
Returns a std::string representation of this Node and its childrem.
Implements efd::Node.
Definition at line 177 of file Nodes.cpp.
toString() [2/3]
template<typename T > std::string efd::NDValue< T >::toString (bool pretty = false) const override virtual
Returns a std::string representation of this Node and its childrem.
Implements efd::Node.
Definition at line 1033 of file Nodes.h.
References std::to_string().
toString() [3/3]
template<> std::string efd::NDValue< std::string >::toString (bool pretty) const virtual
Returns a std::string representation of this Node and its childrem.
Implements efd::Node.
Member Data Documentation
mVal
template<typename T > T efd::NDValue< T >::mVal protected
Definition at line 170 of file Nodes.h.
The documentation for this class was generated from the following file:
include/enfield/Analysis/Nodes.h