Enfield: efd::CircuitGraph Class Reference
efd::CircuitGraph Class Reference
The Circuit representation of the QModule.
#include <CircuitGraph.h>
Classes
struct CircuitNode
Representation of a quantum operation.
class Iterator
Abstracts the iteration of the CircuitGraph.
Public Member Functions
CircuitGraph ()
CircuitGraph (uint32_t qubits, uint32_t cbits)
void init (uint32_t qubits, uint32_t cbits)
Initializes the CircuitGraph.
void checkInitialized ()
Checks if the CircuitGraph is initialized. Exits with error if not.
uint32_t getQSize () const
Returns the number of qubits.
uint32_t getCSize () const
Returns the number of cbits.
uint32_t size () const
Returns the number of bits.
void append (std::vector< Xbit > xbits, Node::Ref node)
Appends a node to the bits xbits.
Iterator build_iterator ()
Builds an iterator instance for this CircuitGraph.
Detailed Description
The Circuit representation of the QModule.
Definition at line 38 of file CircuitGraph.h.
Constructor & Destructor Documentation
CircuitGraph() [1/2]
CircuitGraph::CircuitGraph ()
Definition at line 165 of file CircuitGraph.cpp.
CircuitGraph() [2/2]
CircuitGraph::CircuitGraph (uint32_t qubits, uint32_t cbits)
Definition at line 167 of file CircuitGraph.cpp.
References init().
Member Function Documentation
append()
void CircuitGraph::append (std::vector< Xbit > xbits, Node::Ref node)
Appends a node to the bits xbits.
Definition at line 207 of file CircuitGraph.cpp.
References checkInitialized().
build_iterator()
CircuitGraph::Iterator CircuitGraph::build_iterator ()
Builds an iterator instance for this CircuitGraph.
Definition at line 223 of file CircuitGraph.cpp.
References checkInitialized().
Referenced by efd::CNOTLBOWrapperPass::generate().
checkInitialized()
void CircuitGraph::checkInitialized ()
Checks if the CircuitGraph is initialized. Exits with error if not.
Definition at line 188 of file CircuitGraph.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
Referenced by append(), and build_iterator().
getCSize()
uint32_t CircuitGraph::getCSize () const
Returns the number of cbits.
Definition at line 199 of file CircuitGraph.cpp.
Referenced by efd::CNOTLBOWrapperPass::generate().
getQSize()
uint32_t CircuitGraph::getQSize () const
Returns the number of qubits.
Definition at line 195 of file CircuitGraph.cpp.
Referenced by efd::CNOTLBOWrapperPass::generate(), and efd::CircuitGraphBuilderPass::run().
init()
void CircuitGraph::init (uint32_t qubits, uint32_t cbits)
Initializes the CircuitGraph.
Definition at line 171 of file CircuitGraph.cpp.
Referenced by CircuitGraph().
size()
uint32_t CircuitGraph::size () const
Returns the number of bits.
Definition at line 203 of file CircuitGraph.cpp.
Referenced by efd::CNOTLBOWrapperPass::generate().
The documentation for this class was generated from the following files:
include/enfield/Transform/CircuitGraph.h
lib/Transform/CircuitGraph.cpp