Enfield: efd::NDBinOp Class Reference
efd::NDBinOp Class Reference
Binary operation node.
#include <Nodes.h>
Public Types
enum OpType {
OP_ADD = 0, OP_SUB, OP_MUL, OP_DIV,
OP_POW
}
The possible binary operations.
typedef NDBinOp * Ref
typedef std::unique_ptr< NDBinOp > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
Node::Ref getLhs () const
Gets the left hand side argument.
void setLhs (Node::uRef ref)
Sets the left hand side argument.
Node::Ref getRhs () const
Gets the right hand side argument.
void setRhs (Node::uRef ref)
Sets the right hand side argument.
OpType getOpType () const
Returns the type of the binary operation of this node.
bool isAdd () const
Returns whether this is an add operation.
bool isSub () const
Returns whether this is an sub operation.
bool isMul () const
Returns whether this is an mul operation.
bool isDiv () const
Returns whether this is an div operation.
bool isPow () const
Returns whether this is an pow operation.
std::string getOperation () const override
Returns a std::string representation of the operation.
std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
uint32_t getChildNumber () const override
Returns the number of childrem of this node.
void apply (NodeVisitor *visitor) override
Used by visitor classes.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (OpType t, Node::uRef lhsNode, Node::uRef rhsNode)
Creates a new instance of this node.
static uRef CreateAdd (Node::uRef lhsNode, Node::uRef rhsNode)
Creates a new binary adition node.
static uRef CreateSub (Node::uRef lhsNode, Node::uRef rhsNode)
Creates a new binary subtraction node.
static uRef CreateMul (Node::uRef lhsNode, Node::uRef rhsNode)
Creates a new binary multiplication node.
static uRef CreateDiv (Node::uRef lhsNode, Node::uRef rhsNode)
Creates a new binary division node.
static uRef CreatePow (Node::uRef lhsNode, Node::uRef rhsNode)
Creates a new binary power node.
Protected Types
enum ChildType { I_LHS = 0, I_RHS }
Protected Member Functions
NDBinOp (OpType t, Node::uRef lhsNode, Node::uRef rhsNode)
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
Protected Attributes
OpType mT
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
Binary operation node.
Definition at line 777 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDBinOp* efd::NDBinOp::Ref
Definition at line 785 of file Nodes.h.
uRef
typedef std::unique_ptr<NDBinOp> efd::NDBinOp::uRef
Definition at line 786 of file Nodes.h.
Member Enumeration Documentation
ChildType
enum efd::NDBinOp::ChildType protected
Enumerator
I_LHS
I_RHS
Definition at line 779 of file Nodes.h.
OpType
enum efd::NDBinOp::OpType
The possible binary operations.
Enumerator
OP_ADD
OP_SUB
OP_MUL
OP_DIV
OP_POW
Definition at line 789 of file Nodes.h.
Constructor & Destructor Documentation
NDBinOp()
efd::NDBinOp::NDBinOp (OpType t, Node::uRef lhsNode, Node::uRef rhsNode) protected
Definition at line 1182 of file Nodes.cpp.
References efd::Node::innerAddChild().
Member Function Documentation
apply()
void efd::NDBinOp::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Implements efd::Node.
Definition at line 1249 of file Nodes.cpp.
References efd::NodeVisitor::visit().
ClassOf()
bool efd::NDBinOp::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 1265 of file Nodes.cpp.
References efd::Node::getKind().
cloneImpl()
efd::Node::uRef efd::NDBinOp::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Implements efd::Node.
Definition at line 1188 of file Nodes.cpp.
References Create().
Create()
efd::NDBinOp::uRef efd::NDBinOp::Create (OpType t, Node::uRef lhsNode, Node::uRef rhsNode) static
Creates a new instance of this node.
Definition at line 1269 of file Nodes.cpp.
Referenced by cloneImpl().
CreateAdd()
efd::NDBinOp::uRef efd::NDBinOp::CreateAdd (Node::uRef lhsNode, Node::uRef rhsNode) static
Creates a new binary adition node.
Definition at line 1273 of file Nodes.cpp.
CreateDiv()
efd::NDBinOp::uRef efd::NDBinOp::CreateDiv (Node::uRef lhsNode, Node::uRef rhsNode) static
Creates a new binary division node.
Definition at line 1285 of file Nodes.cpp.
CreateMul()
efd::NDBinOp::uRef efd::NDBinOp::CreateMul (Node::uRef lhsNode, Node::uRef rhsNode) static
Creates a new binary multiplication node.
Definition at line 1281 of file Nodes.cpp.
CreatePow()
efd::NDBinOp::uRef efd::NDBinOp::CreatePow (Node::uRef lhsNode, Node::uRef rhsNode) static
Creates a new binary power node.
Definition at line 1289 of file Nodes.cpp.
CreateSub()
efd::NDBinOp::uRef efd::NDBinOp::CreateSub (Node::uRef lhsNode, Node::uRef rhsNode) static
Creates a new binary subtraction node.
Definition at line 1277 of file Nodes.cpp.
getChildNumber()
uint32_t efd::NDBinOp::getChildNumber () const override virtual
Returns the number of childrem of this node.
Implements efd::Node.
Definition at line 1245 of file Nodes.cpp.
getLhs()
efd::Node::Ref efd::NDBinOp::getLhs () const
Gets the left hand side argument.
Definition at line 1192 of file Nodes.cpp.
Referenced by efd::QArgsReplaceVisitor::visit().
getOperation()
std::string efd::NDBinOp::getOperation () const override virtual
Returns a std::string representation of the operation.
Reimplemented from efd::Node.
Definition at line 1232 of file Nodes.cpp.
References ERR, efd::EXIT_unknown_resource, and efd::ExitWith().
getOpType()
efd::NDBinOp::OpType efd::NDBinOp::getOpType () const
Returns the type of the binary operation of this node.
Definition at line 1208 of file Nodes.cpp.
getRhs()
efd::Node::Ref efd::NDBinOp::getRhs () const
Gets the right hand side argument.
Definition at line 1200 of file Nodes.cpp.
Referenced by efd::QArgsReplaceVisitor::visit().
isAdd()
bool efd::NDBinOp::isAdd () const
Returns whether this is an add operation.
Definition at line 1212 of file Nodes.cpp.
isDiv()
bool efd::NDBinOp::isDiv () const
Returns whether this is an div operation.
Definition at line 1224 of file Nodes.cpp.
isMul()
bool efd::NDBinOp::isMul () const
Returns whether this is an mul operation.
Definition at line 1220 of file Nodes.cpp.
isPow()
bool efd::NDBinOp::isPow () const
Returns whether this is an pow operation.
Definition at line 1228 of file Nodes.cpp.
isSub()
bool efd::NDBinOp::isSub () const
Returns whether this is an sub operation.
Definition at line 1216 of file Nodes.cpp.
setLhs()
void efd::NDBinOp::setLhs (Node::uRef ref)
Sets the left hand side argument.
Definition at line 1196 of file Nodes.cpp.
setRhs()
void efd::NDBinOp::setRhs (Node::uRef ref)
Sets the right hand side argument.
Definition at line 1204 of file Nodes.cpp.
toString()
std::string efd::NDBinOp::toString (bool pretty = false) const override virtual
Returns a std::string representation of this Node and its childrem.
Implements efd::Node.
Definition at line 1253 of file Nodes.cpp.
Member Data Documentation
mT
OpType efd::NDBinOp::mT protected
Definition at line 798 of file Nodes.h.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp