Enfield: efd::QArgsReplaceVisitor Class Reference
efd::QArgsReplaceVisitor Class Reference
Public Member Functions
QArgsReplaceVisitor (VarMap &varMap)
void substituteChildrem (Node::Ref ref)
Node::uRef replaceChild (Node::Ref ref)
void visit (NDQOpU::Ref ref) override
void visit (NDQOpCX::Ref ref) override
void visit (NDList::Ref ref) override
void visit (NDQOpBarrier::Ref ref) override
void visit (NDQOpGen::Ref ref) override
void visit (NDBinOp::Ref ref) override
void visit (NDUnaryOp::Ref ref) override
void visit (NDIfStmt::Ref ref) override
Public Member Functions inherited from efd::NodeVisitor
virtual void visit (NDQasmVersion::Ref ref)
virtual void visit (NDInclude::Ref ref)
virtual void visit (NDRegDecl::Ref ref)
virtual void visit (NDGateDecl::Ref ref)
virtual void visit (NDOpaque::Ref ref)
virtual void visit (NDQOpMeasure::Ref ref)
virtual void visit (NDQOpReset::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDStmtList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Public Attributes
VarMap & varMap
Additional Inherited Members
Public Types inherited from efd::NodeVisitor
typedef NodeVisitor * Ref
Detailed Description
Definition at line 351 of file Utils.cpp.
Constructor & Destructor Documentation
QArgsReplaceVisitor()
efd::QArgsReplaceVisitor::QArgsReplaceVisitor (VarMap & varMap) inline
Definition at line 355 of file Utils.cpp.
Member Function Documentation
replaceChild()
Node::uRef efd::QArgsReplaceVisitor::replaceChild (Node::Ref ref)
Definition at line 371 of file Utils.cpp.
References efd::Node::toString().
substituteChildrem()
void efd::QArgsReplaceVisitor::substituteChildrem (Node::Ref ref)
Definition at line 381 of file Utils.cpp.
References efd::Node::getChild(), efd::Node::getChildNumber(), and efd::Node::setChild().
visit() [1/8]
void efd::QArgsReplaceVisitor::visit (NDQOpU::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 395 of file Utils.cpp.
visit() [2/8]
void efd::QArgsReplaceVisitor::visit (NDQOpCX::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 399 of file Utils.cpp.
visit() [3/8]
void efd::QArgsReplaceVisitor::visit (NDList::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 390 of file Utils.cpp.
visit() [4/8]
void efd::QArgsReplaceVisitor::visit (NDQOpBarrier::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 403 of file Utils.cpp.
visit() [5/8]
void efd::QArgsReplaceVisitor::visit (NDQOpGen::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 407 of file Utils.cpp.
visit() [6/8]
void efd::QArgsReplaceVisitor::visit (NDBinOp::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 411 of file Utils.cpp.
References efd::Node::apply(), efd::NDBinOp::getLhs(), and efd::NDBinOp::getRhs().
visit() [7/8]
void efd::QArgsReplaceVisitor::visit (NDUnaryOp::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 417 of file Utils.cpp.
visit() [8/8]
void efd::QArgsReplaceVisitor::visit (NDIfStmt::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 422 of file Utils.cpp.
References efd::Node::apply(), and efd::NDIfStmt::getQOp().
Member Data Documentation
varMap
VarMap& efd::QArgsReplaceVisitor::varMap
Definition at line 353 of file Utils.cpp.
The documentation for this class was generated from the following file:
lib/Transform/Utils.cpp