Enfield: efd::Xbit Class Reference
efd::Xbit Class Reference
Represents the id of one Quantum or Classical bit.
#include <CircuitGraph.h>
Public Types
enum Type { Type::QUANTUM, Type::CLASSIC }
Public Member Functions
Xbit (uint32_t realId, uint32_t qubits, uint32_t cbits)
bool isQuantum ()
bool isClassic ()
uint32_t getRealId (uint32_t qubits, uint32_t cbits)
Gets the real id for this bit.
Static Public Member Functions
static Xbit Q (uint32_t id)
Creates a quantum Xbit with id.
static Xbit C (uint32_t id)
Creates a classical Xbit with id.
Public Attributes
Type mType
uint32_t mId
Detailed Description
Represents the id of one Quantum or Classical bit.
Definition at line 10 of file CircuitGraph.h.
Member Enumeration Documentation
Type
enum efd::Xbit::Type strong
Enumerator
QUANTUM
CLASSIC
Definition at line 12 of file CircuitGraph.h.
Constructor & Destructor Documentation
Xbit()
Xbit::Xbit (uint32_t realId, uint32_t qubits, uint32_t cbits)
Definition at line 12 of file CircuitGraph.cpp.
References CLASSIC, ERR, efd::EXIT_unreachable, efd::ExitWith(), mId, mType, and QUANTUM.
Member Function Documentation
C()
Xbit Xbit::C (uint32_t id) static
Creates a classical Xbit with id.
Definition at line 60 of file CircuitGraph.cpp.
References CLASSIC.
Referenced by efd::CNOTLBOWrapperPass::generate(), and efd::CircuitGraphBuilderPass::run().
getRealId()
uint32_t Xbit::getRealId (uint32_t qubits, uint32_t cbits)
Gets the real id for this bit.
If it is a classical bit, we sum qubits to it.
Definition at line 31 of file CircuitGraph.cpp.
References CLASSIC, ERR, efd::EXIT_unreachable, efd::ExitWith(), mId, mType, and QUANTUM.
Referenced by efd::CircuitGraph::Iterator::back(), efd::CircuitGraph::Iterator::get(), efd::CircuitGraph::Iterator::next(), and efd::CircuitGraph::Iterator::operator[]().
isClassic()
bool Xbit::isClassic ()
Definition at line 29 of file CircuitGraph.cpp.
References CLASSIC, and mType.
isQuantum()
bool Xbit::isQuantum ()
Definition at line 28 of file CircuitGraph.cpp.
References mType, and QUANTUM.
Q()
Xbit Xbit::Q (uint32_t id) static
Creates a quantum Xbit with id.
Definition at line 56 of file CircuitGraph.cpp.
References QUANTUM.
Referenced by efd::CNOTLBOWrapperPass::generate(), and efd::CircuitGraphBuilderPass::run().
Member Data Documentation
mId
uint32_t efd::Xbit::mId
Definition at line 15 of file CircuitGraph.h.
Referenced by getRealId(), and Xbit().
mType
Type efd::Xbit::mType
Definition at line 14 of file CircuitGraph.h.
Referenced by getRealId(), isClassic(), isQuantum(), and Xbit().
The documentation for this class was generated from the following files:
include/enfield/Transform/CircuitGraph.h
lib/Transform/CircuitGraph.cpp