Enfield: efd::Node Class Reference
efd::Node Class Reference abstract
Base class for AST nodes.
#include <Nodes.h>
Public Types
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
virtual std::string getOperation () const
Returns a std::string representation of the operation.
virtual uint32_t getChildNumber () const =0
Returns the number of childrem of this node.
virtual std::string toString (bool pretty=false) const =0
Returns a std::string representation of this Node and its childrem.
virtual void apply (NodeVisitor *visitor)=0
Used by visitor classes.
Node::uRef clone () const
Clones the current node (deep copy).
Protected Member Functions
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
virtual Node::uRef cloneImpl () const =0
Clones the current node (deep copy).
Protected Attributes
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Friends
class QModule
Detailed Description
Base class for AST nodes.
Definition at line 39 of file Nodes.h.
Member Typedef Documentation
ConstIterator
typedef std::vector<uRef>::const_iterator efd::Node::ConstIterator
Definition at line 46 of file Nodes.h.
Iterator
typedef std::vector<uRef>::iterator efd::Node::Iterator
Definition at line 45 of file Nodes.h.
Ref
typedef Node* efd::Node::Ref
Definition at line 41 of file Nodes.h.
sRef
typedef std::shared_ptr<Node> efd::Node::sRef
Definition at line 43 of file Nodes.h.
uRef
typedef std::unique_ptr<Node> efd::Node::uRef
Definition at line 42 of file Nodes.h.
Member Enumeration Documentation
Kind
enum efd::Node::Kind
Enumerator
K_QASM_VERSION
K_INCLUDE
K_REG_DECL
K_GATE_DECL
K_GATE_OPAQUE
K_QOP
K_QOP_MEASURE
K_QOP_RESET
K_QOP_BARRIER
K_QOP_CX
K_QOP_U
K_QOP_GEN
K_BINOP
K_UNARYOP
K_ID_REF
K_LIST
K_STMT_LIST
K_GOP_LIST
K_IF_STMT
K_LIT_INT
K_LIT_REAL
K_LIT_STRING
Definition at line 48 of file Nodes.h.
Constructor & Destructor Documentation
Node()
efd::Node::Node (Kind k, bool empty = false) protected
Constructs the node, initially empty (with no information).
Definition at line 9 of file Nodes.cpp.
~Node()
efd::Node::~Node () virtual
Definition at line 18 of file Nodes.cpp.
Member Function Documentation
apply()
virtual void efd::Node::apply (NodeVisitor * visitor) pure virtual
Used by visitor classes.
Implemented in efd::NDIfStmt, efd::NDQOpGen, efd::NDUnaryOp, efd::NDBinOp, efd::NDQOpCX, efd::NDQOpU, efd::NDQOpMeasure, efd::NDQOpBarrier, efd::NDQOpReset, efd::NDGateDecl, efd::NDGateSign, efd::NDInclude, efd::NDQasmVersion, efd::NDGOpList, efd::NDStmtList, efd::NDList, efd::NDIdRef, efd::NDRegDecl, efd::NDValue< T >, efd::NDValue< T >, efd::NDValue< T >, and efd::NDValue< T >.
Referenced by efd::InlineGate(), efd::ProcessAST(), efd::InlineAllVisitor::visit(), efd::ReverseEdgesVisitor::visit(), efd::NodeRenameVisitor::visit(), and efd::QArgsReplaceVisitor::visit().
begin() [1/2]
efd::Node::Iterator efd::Node::begin ()
Returns a iterator to the beginning of the vector.
Definition at line 38 of file Nodes.cpp.
begin() [2/2]
efd::Node::ConstIterator efd::Node::begin () const
Returns a const iterator to the beginning of the vector.
Definition at line 46 of file Nodes.cpp.
clone()
efd::Node::uRef efd::Node::clone () const
Clones the current node (deep copy).
Definition at line 114 of file Nodes.cpp.
Referenced by efd::InlineGate(), efd::XbitToNumberVisitor::visit(), efd::QModulefyVisitor::visit(), and efd::NodeRenameVisitor::visitNDQOp().
cloneImpl()
virtual Node::uRef efd::Node::cloneImpl () const protected pure virtual
Clones the current node (deep copy).
Implemented in efd::NDIfStmt, efd::NDQOpGen, efd::NDUnaryOp, efd::NDBinOp, efd::NDQOpCX, efd::NDQOpU, efd::NDQOpMeasure, efd::NDQOpBarrier, efd::NDQOpReset, efd::NDGateDecl, efd::NDGateSign, efd::NDInclude, efd::NDQasmVersion, efd::NDGOpList, efd::NDStmtList, efd::NDList, efd::NDIdRef, efd::NDRegDecl, and efd::NDValue< T >.
end() [1/2]
efd::Node::Iterator efd::Node::end ()
Returns a iterator to the end of the vector.
Definition at line 42 of file Nodes.cpp.
end() [2/2]
efd::Node::ConstIterator efd::Node::end () const
Returns a const iterator to the end of the vector.
Definition at line 50 of file Nodes.cpp.
equals()
bool efd::Node::equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
One Node is said to be equal to another one if, and only if, all its operands and names are equal.
Definition at line 96 of file Nodes.cpp.
References getChild(), getChildNumber(), getKind(), and getOperation().
equalsImpl()
bool efd::Node::equalsImpl (Node::Ref ref) const protected virtual
Extend the 'equals' implementation by implementing this method.
Reimplemented in efd::NDValue< T >.
Definition at line 94 of file Nodes.cpp.
findChild()
efd::Node::Iterator efd::Node::findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Definition at line 30 of file Nodes.cpp.
Referenced by efd::QModule::inlineCall().
getChild()
efd::Node::Ref efd::Node::getChild (uint32_t i) const
Gets the i-th child.
Definition at line 21 of file Nodes.cpp.
Referenced by equals(), efd::NDQOpCX::getLhs(), efd::NDQOpReset::getQArg(), efd::NDQOpU::getQArg(), efd::NDQOpMeasure::getQBit(), efd::NDQOpCX::getRhs(), efd::InlineGate(), efd::QArgsReplaceVisitor::substituteChildrem(), efd::ReverseEdgesVisitor::visit(), efd::RenameQbitVisitor::visit(), and efd::StdSolutionImplPass::visit().
getChildNumber()
virtual uint32_t efd::Node::getChildNumber () const pure virtual
Returns the number of childrem of this node.
Implemented in efd::NDIfStmt, efd::NDUnaryOp, efd::NDBinOp, efd::NDQOpMeasure, efd::NDQOp, efd::NDGateDecl, efd::NDGateSign, efd::NDInclude, efd::NDQasmVersion, efd::NDList, efd::NDIdRef, efd::NDRegDecl, and efd::NDValue< T >.
Referenced by equals(), efd::InlineGate(), and efd::QArgsReplaceVisitor::substituteChildrem().
getKind()
efd::Node::Kind efd::Node::getKind () const
Returns the kind of this node.
Definition at line 54 of file Nodes.cpp.
Referenced by efd::NDValue< T >::ClassOf(), efd::NDDecl::ClassOf(), efd::NDRegDecl::ClassOf(), efd::NDIdRef::ClassOf(), efd::NDList::ClassOf(), efd::NDStmtList::ClassOf(), efd::NDGOpList::ClassOf(), efd::NDQasmVersion::ClassOf(), efd::NDInclude::ClassOf(), efd::NDGateSign::ClassOf(), efd::NDGateDecl::ClassOf(), efd::NDQOp::ClassOf(), efd::NDQOpReset::ClassOf(), efd::NDQOpBarrier::ClassOf(), efd::NDQOpMeasure::ClassOf(), efd::NDQOpU::ClassOf(), efd::NDQOpCX::ClassOf(), efd::NDBinOp::ClassOf(), efd::NDUnaryOp::ClassOf(), efd::NDQOpGen::ClassOf(), efd::NDIfStmt::ClassOf(), equals(), efd::IsCNOTGateCall(), and efd::SemanticVerifierVisitor::visit().
getOperation()
std::string efd::Node::getOperation () const virtual
Returns a std::string representation of the operation.
Reimplemented in efd::NDIfStmt, efd::NDUnaryOp, efd::NDBinOp, efd::NDQOp, efd::NDGateDecl, efd::NDGateSign, efd::NDInclude, efd::NDQasmVersion, efd::NDRegDecl, efd::NDValue< T >, efd::NDValue< T >, and efd::NDValue< T >.
Definition at line 110 of file Nodes.cpp.
Referenced by equals(), efd::GetIntrinsicKind(), and efd::IsCNOTGateCall().
getParent()
efd::Node::Ref efd::Node::getParent () const
Returns the parent node of the current node.
Definition at line 86 of file Nodes.cpp.
Referenced by efd::QModule::inlineCall(), and efd::InlineGate().
innerAddChild()
void efd::Node::innerAddChild (uRef ref) protected
Adds a child to this node. It should be used only for construction of each derived class.
Definition at line 13 of file Nodes.cpp.
Referenced by efd::NDBinOp::NDBinOp(), efd::NDDecl::NDDecl(), efd::NDGateDecl::NDGateDecl(), efd::NDGateSign::NDGateSign(), efd::NDIdRef::NDIdRef(), efd::NDIfStmt::NDIfStmt(), efd::NDInclude::NDInclude(), efd::NDQasmVersion::NDQasmVersion(), efd::NDQOp::NDQOp(), efd::NDQOpMeasure::NDQOpMeasure(), efd::NDRegDecl::NDRegDecl(), and efd::NDUnaryOp::NDUnaryOp().
isEmpty()
bool efd::Node::isEmpty () const
Returns whether this node has any information.
Definition at line 66 of file Nodes.cpp.
Referenced by efd::NDGateSign::toString(), efd::NDGateDecl::toString(), and efd::NDQOp::toString().
isInInclude()
bool efd::Node::isInInclude () const
Returns whether this node is in a include node.
Definition at line 78 of file Nodes.cpp.
print() [1/2]
void efd::Node::print (std::ostream & O = std::cout, bool pretty = false)
Prints from this node, recursively to O.
Definition at line 58 of file Nodes.cpp.
print() [2/2]
void efd::Node::print (bool pretty = false)
Prints to the standard output.
Definition at line 62 of file Nodes.cpp.
setChild()
void efd::Node::setChild (uint32_t i, uRef ref)
Sets the i-th child.
Definition at line 25 of file Nodes.cpp.
Referenced by efd::QArgsReplaceVisitor::substituteChildrem(), efd::RenameQbitVisitor::visit(), and efd::StdSolutionImplPass::visit().
setGenerated()
void efd::Node::setGenerated ()
Definition at line 74 of file Nodes.cpp.
setInInclude()
void efd::Node::setInInclude ()
Definition at line 82 of file Nodes.cpp.
setParent()
void efd::Node::setParent (Ref ref)
Sets the parent node of the current node.
Definition at line 90 of file Nodes.cpp.
toString()
virtual std::string efd::Node::toString (bool pretty = false) const pure virtual
Returns a std::string representation of this Node and its childrem.
Implemented in efd::NDIfStmt, efd::NDUnaryOp, efd::NDBinOp, efd::NDQOpMeasure, efd::NDQOp, efd::NDGateDecl, efd::NDGateSign, efd::NDInclude, efd::NDQasmVersion, efd::NDGOpList, efd::NDStmtList, efd::NDList, efd::NDIdRef, efd::NDRegDecl, efd::NDValue< T >, efd::NDValue< T >, and efd::NDValue< T >.
Referenced by efd::QModule::findStatement(), efd::DependencyBuilder::getDeps(), efd::GetIntrinsicKind(), efd::LayerBasedOrderingWrapperPass::getNodeId(), efd::DependencyBuilder::getUId(), efd::InlineGate(), efd::QArgsReplaceVisitor::replaceChild(), efd::QModule::replaceStatement(), efd::SeqNCandidatesGenerator::signalProcessed(), efd::NDGateSign::toString(), efd::NDGateDecl::toString(), efd::NDQOp::toString(), efd::NDUnaryOp::toString(), efd::ReverseEdgesVisitor::visit(), efd::UsedBitsVisitor::visit(), efd::SemanticVerifierVisitor::visit(), and efd::DependencyBuilderVisitor::visit().
wasGenerated()
bool efd::Node::wasGenerated () const
Returns whether this node was generated by the compiler.
Definition at line 70 of file Nodes.cpp.
Friends And Related Function Documentation
QModule
friend class QModule friend
Definition at line 159 of file Nodes.h.
Member Data Documentation
mChild
std::vector<uRef> efd::Node::mChild protected
The childrem nodes.
Definition at line 83 of file Nodes.h.
mInInclude
bool efd::Node::mInInclude protected
True if it is a node inside an include node.
Definition at line 81 of file Nodes.h.
mIsEmpty
bool efd::Node::mIsEmpty protected
Holds whether this node has no information.
Definition at line 77 of file Nodes.h.
Referenced by efd::NDList::addChild(), efd::NDList::addChildren(), and efd::NDList::removeChild().
mK
Kind efd::Node::mK protected
The kind of the node.
Definition at line 75 of file Nodes.h.
mParent
Ref efd::Node::mParent protected
Definition at line 84 of file Nodes.h.
mWasGenerated
bool efd::Node::mWasGenerated protected
True if it was generated by the compiler.
Definition at line 79 of file Nodes.h.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp