Enfield: efd::WeightedSIFinder< T > Class Template Reference
efd::WeightedSIFinder< T > Class Template Reference
Extends the SIFinder class for weighted graphs.
#include <WeightedSIFinder.h>
Public Types
typedef WeightedSIFinder< T > * Ref
typedef std::unique_ptr< WeightedSIFinder< T > > uRef
typedef std::shared_ptr< WeightedSIFinder< T > > sRef
Public Types inherited from efd::SIFinder
typedef SIFinder * Ref
typedef std::unique_ptr< SIFinder > uRef
typedef std::shared_ptr< SIFinder > sRef
Public Member Functions
virtual Result find (Graph::Ref g, Graph::Ref h) override
Returns a valid matching of h in g.
Static Public Member Functions
static uRef Create ()
Creates an instance of this class.
Protected Member Functions
WeightedSIFinder ()
uint32_t findBestVertex (uint32_t a, uint32_t b)
uint32_t getFirstFree ()
Protected Attributes
Graph::Ref mG
WeightedGraph< T >::Ref mH
std::vector< bool > matched
std::vector< uint32_t > matching
std::vector< uint32_t > gOutDegree
Detailed Description
template<typename T>
class efd::WeightedSIFinder< T >
Extends the SIFinder class for weighted graphs.
This class finds a graph matching M=(Vm, Em) of G=(Vg, Eg) and H=(Vh, Eh) such that Eh is weighted.
So, the idea is to try to maximize the value of the edges matched.
Definition at line 21 of file WeightedSIFinder.h.
Member Typedef Documentation
Ref
template<typename T> typedef WeightedSIFinder<T>* efd::WeightedSIFinder< T >::Ref
Definition at line 23 of file WeightedSIFinder.h.
sRef
template<typename T> typedef std::shared_ptr<WeightedSIFinder<T> > efd::WeightedSIFinder< T >::sRef
Definition at line 25 of file WeightedSIFinder.h.
uRef
template<typename T> typedef std::unique_ptr<WeightedSIFinder<T> > efd::WeightedSIFinder< T >::uRef
Definition at line 24 of file WeightedSIFinder.h.
Constructor & Destructor Documentation
WeightedSIFinder()
template<typename T > efd::WeightedSIFinder< T >::WeightedSIFinder () protected
Definition at line 56 of file WeightedSIFinder.h.
Member Function Documentation
Create()
template<typename T > efd::WeightedSIFinder< T >::uRef efd::WeightedSIFinder< T >::Create () static
Creates an instance of this class.
Definition at line 209 of file WeightedSIFinder.h.
find()
template<typename T > efd::SIFinder::Result efd::WeightedSIFinder< T >::find (Graph::Ref g, Graph::Ref h) override virtual
Returns a valid matching of h in g.
Note that this is not necessairly an exact match (exact subgraph isomorphism). That is because this is a NP-Complete problem.
Implements efd::SIFinder.
Definition at line 119 of file WeightedSIFinder.h.
References ERR, efd::ExitWith(), and efd::Graph::isWeighted().
findBestVertex()
template<typename T > uint32_t efd::WeightedSIFinder< T >::findBestVertex (uint32_t a, uint32_t b) protected
Definition at line 59 of file WeightedSIFinder.h.
getFirstFree()
template<typename T > uint32_t efd::WeightedSIFinder< T >::getFirstFree () protected
Definition at line 107 of file WeightedSIFinder.h.
References ERR, and efd::ExitWith().
Member Data Documentation
gOutDegree
template<typename T> std::vector<uint32_t> efd::WeightedSIFinder< T >::gOutDegree protected
Definition at line 33 of file WeightedSIFinder.h.
matched
template<typename T> std::vector<bool> efd::WeightedSIFinder< T >::matched protected
Definition at line 31 of file WeightedSIFinder.h.
matching
template<typename T> std::vector<uint32_t> efd::WeightedSIFinder< T >::matching protected
Definition at line 32 of file WeightedSIFinder.h.
mG
template<typename T> Graph::Ref efd::WeightedSIFinder< T >::mG protected
Definition at line 28 of file WeightedSIFinder.h.
mH
template<typename T> WeightedGraph<T>::Ref efd::WeightedSIFinder< T >::mH protected
Definition at line 29 of file WeightedSIFinder.h.
The documentation for this class was generated from the following file:
include/enfield/Support/WeightedSIFinder.h