Enfield: efd::CNOTLBOWrapperPass Class Reference
efd::CNOTLBOWrapperPass Class Reference
Layer-based Ordering with CNOT priority.
#include <CNOTLBOWrapperPass.h>
Public Types
typedef std::unique_ptr< CNOTLBOWrapperPass > uRef
typedef CNOTLBOWrapperPass * Ref
Public Types inherited from efd::LayerBasedOrderingWrapperPass
typedef std::unique_ptr< LayerBasedOrderingWrapperPass > uRef
typedef LayerBasedOrderingWrapperPass * Ref
Public Types inherited from efd::PassT< LayerBasedOrdering >
typedef PassT< LayerBasedOrdering > * Ref
typedef std::shared_ptr< PassT< LayerBasedOrdering > > sRef
typedef std::unique_ptr< PassT< LayerBasedOrdering > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Static Public Member Functions
static uRef Create ()
Static Public Member Functions inherited from efd::PassT< LayerBasedOrdering >
static bool ClassOf (Pass *ref)
Static Public Attributes
static uint8_t ID = 0
Protected Member Functions
Ordering generate (CircuitGraph &graph) override
Protected Member Functions inherited from efd::LayerBasedOrderingWrapperPass
uint32_t getNodeId (Node::Ref ref)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Additional Inherited Members
Public Member Functions inherited from efd::LayerBasedOrderingWrapperPass
bool run (QModule *qmod) override
Runs the pass in the given QModule and returns true if it has modified qmod.
Public Member Functions inherited from efd::PassT< LayerBasedOrdering >
PassT ()
LayerBasedOrdering getData () const
Gets the resulting data.
LayerBasedOrdering & getData ()
Public Member Functions inherited from efd::Pass
Kind getKind () const
Gets the kind of this pass.
Protected Attributes inherited from efd::LayerBasedOrderingWrapperPass
std::unordered_map< Node::Ref, uint32_t > mStmtId
Protected Attributes inherited from efd::PassT< LayerBasedOrdering >
LayerBasedOrdering mData
Detailed Description
Layer-based Ordering with CNOT priority.
Definition at line 8 of file CNOTLBOWrapperPass.h.
Member Typedef Documentation
Ref
typedef CNOTLBOWrapperPass* efd::CNOTLBOWrapperPass::Ref
Definition at line 11 of file CNOTLBOWrapperPass.h.
uRef
typedef std::unique_ptr<CNOTLBOWrapperPass> efd::CNOTLBOWrapperPass::uRef
Definition at line 10 of file CNOTLBOWrapperPass.h.
Member Function Documentation
Create()
efd::CNOTLBOWrapperPass::uRef efd::CNOTLBOWrapperPass::Create () static
Definition at line 111 of file CNOTLBOWrapperPass.cpp.
generate()
efd::Ordering efd::CNOTLBOWrapperPass::generate (CircuitGraph & graph) override protected virtual
Implements efd::LayerBasedOrderingWrapperPass.
Definition at line 7 of file CNOTLBOWrapperPass.cpp.
References efd::CircuitGraph::build_iterator(), efd::Xbit::C(), efd::CircuitGraph::getCSize(), efd::LayerBasedOrderingWrapperPass::getNodeId(), efd::CircuitGraph::getQSize(), efd::LayerBasedOrdering::layers, efd::PassT< LayerBasedOrdering >::mData, efd::CircuitGraph::Iterator::next(), efd::Xbit::Q(), and efd::CircuitGraph::size().
Member Data Documentation
ID
uint8_t efd::CNOTLBOWrapperPass::ID = 0 static
Definition at line 13 of file CNOTLBOWrapperPass.h.
The documentation for this class was generated from the following files:
include/enfield/Transform/CNOTLBOWrapperPass.h
lib/Transform/CNOTLBOWrapperPass.cpp