Enfield: tools/Enfield.cpp File Reference
Enfield.cpp File Reference
#include "enfield/Support/CommandLine.h"
#include "enfield/Transform/QModule.h"
#include "enfield/Transform/Driver.h"
#include "enfield/Transform/PassCache.h"
#include "enfield/Transform/IntrinsicGateCostPass.h"
#include "enfield/Transform/QModuleQualityEvalPass.h"
#include "enfield/Transform/InlineAllPass.h"
#include "enfield/Transform/ReverseEdgesPass.h"
#include "enfield/Transform/Allocators/Allocators.h"
#include "enfield/Arch/Architectures.h"
#include "enfield/Support/Stats.h"
#include "enfield/Support/Defs.h"
#include <fstream>
#include <cassert>
#include <cctype>
#include <sstream>
#include <map>
Classes
struct efd::ParseOptTrait< MapGateUInt >
Namespaces
efd
Typedefs
typedef std::map< std::string, uint32_t > MapGateUInt
Functions
int main (int argc, char **argv)
Typedef Documentation
MapGateUInt
typedef std::map<std::string, uint32_t> MapGateUInt
Definition at line 22 of file Enfield.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 128 of file Enfield.cpp.
References efd::InitializeAllArchitectures(), efd::InitializeAllQbitAllocators(), efd::ParseArguments(), and efd::ParseFile().