Enfield: efd::ExpTSFinder Class Reference
efd::ExpTSFinder Class Reference
#include <ExpTSFinder.h>
Public Types
typedef std::unique_ptr< ExpTSFinder > uRef
Public Types inherited from efd::TokenSwapFinder
typedef TokenSwapFinder * Ref
typedef std::unique_ptr< TokenSwapFinder > uRef
Public Member Functions
ExpTSFinder (Graph::sRef graph)
SwapSeq find (Assign from, Assign to) override
Finds a swap sequence to reach to from from.
SwapSeq find (Graph::Ref graph, Assign from, Assign to) override
Finds a swap sequence to reach to from from in graph.
Static Public Member Functions
static uRef Create (Graph::sRef graph=nullptr)
Creates an instance of this class.
Public Attributes
std::vector< Assign > mAssigns
Additional Inherited Members
Protected Member Functions inherited from efd::TokenSwapFinder
TokenSwapFinder (Graph::sRef graph)
Protected Attributes inherited from efd::TokenSwapFinder
Graph::sRef mG
Detailed Description
Definition at line 8 of file ExpTSFinder.h.
Member Typedef Documentation
uRef
typedef std::unique_ptr<ExpTSFinder> efd::ExpTSFinder::uRef
Definition at line 10 of file ExpTSFinder.h.
Constructor & Destructor Documentation
ExpTSFinder()
efd::ExpTSFinder::ExpTSFinder (Graph::sRef graph)
Definition at line 93 of file ExpTSFinder.cpp.
References efd::TokenSwapFinder::TokenSwapFinder().
Referenced by Create(), and efd::DynprogDepSolver::solve().
Member Function Documentation
Create()
efd::ExpTSFinder::uRef efd::ExpTSFinder::Create (Graph::sRef graph = nullptr) static
Creates an instance of this class.
Definition at line 108 of file ExpTSFinder.cpp.
References ExpTSFinder().
find() [1/2]
efd::SwapSeq efd::ExpTSFinder::find (Assign from, Assign to) override virtual
Finds a swap sequence to reach to from from.
Implements efd::TokenSwapFinder.
Definition at line 97 of file ExpTSFinder.cpp.
References efd::TokenSwapFinder::mG.
Referenced by efd::DynprogDepSolver::solve().
find() [2/2]
efd::SwapSeq efd::ExpTSFinder::find (Graph::Ref graph, Assign from, Assign to) override virtual
Finds a swap sequence to reach to from from in graph.
Implements efd::TokenSwapFinder.
Definition at line 102 of file ExpTSFinder.cpp.
References efd::TokenSwapFinder::mG.
Member Data Documentation
mAssigns
std::vector<Assign> efd::ExpTSFinder::mAssigns
Definition at line 21 of file ExpTSFinder.h.
Referenced by efd::DynprogDepSolver::solve().
The documentation for this class was generated from the following files:
include/enfield/Support/ExpTSFinder.h
lib/Support/ExpTSFinder.cpp