Enfield: efd::DependencyBuilderWrapperPass Class Reference
efd::DependencyBuilderWrapperPass Class Reference
WrapperPass that yields a DependencyBuilder structure.
#include <DependencyBuilderPass.h>
Public Types
typedef DependencyBuilderWrapperPass * Ref
typedef std::unique_ptr< DependencyBuilderWrapperPass > uRef
typedef std::shared_ptr< DependencyBuilderWrapperPass > sRef
Public Types inherited from efd::PassT< DependencyBuilder >
typedef PassT< DependencyBuilder > * Ref
typedef std::shared_ptr< PassT< DependencyBuilder > > sRef
typedef std::unique_ptr< PassT< DependencyBuilder > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
bool run (QModule::Ref qmod) override
Public Member Functions inherited from efd::PassT< DependencyBuilder >
PassT ()
DependencyBuilder getData () const
Gets the resulting data.
DependencyBuilder & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create ()
Returns a new instance of this class.
Static Public Member Functions inherited from efd::PassT< DependencyBuilder >
static bool ClassOf (Pass *ref)
Static Public Attributes
static uint8_t ID = 0
Additional Inherited Members
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Protected Attributes inherited from efd::PassT< DependencyBuilder >
DependencyBuilder mData
Detailed Description
WrapperPass that yields a DependencyBuilder structure.
Definition at line 93 of file DependencyBuilderPass.h.
Member Typedef Documentation
Ref
typedef DependencyBuilderWrapperPass* efd::DependencyBuilderWrapperPass::Ref
Definition at line 95 of file DependencyBuilderPass.h.
sRef
typedef std::shared_ptr<DependencyBuilderWrapperPass> efd::DependencyBuilderWrapperPass::sRef
Definition at line 97 of file DependencyBuilderPass.h.
uRef
typedef std::unique_ptr<DependencyBuilderWrapperPass> efd::DependencyBuilderWrapperPass::uRef
Definition at line 96 of file DependencyBuilderPass.h.
Member Function Documentation
Create()
efd::DependencyBuilderWrapperPass::uRef efd::DependencyBuilderWrapperPass::Create () static
Returns a new instance of this class.
Definition at line 245 of file DependencyBuilderPass.cpp.
run()
bool efd::DependencyBuilderWrapperPass::run (QModule::Ref qmod) override
Definition at line 224 of file DependencyBuilderPass.cpp.
References efd::QModule::gates_begin(), efd::QModule::gates_end(), efd::QModule::stmt_begin(), and efd::QModule::stmt_end().
Member Data Documentation
ID
uint8_t efd::DependencyBuilderWrapperPass::ID = 0 static
Definition at line 99 of file DependencyBuilderPass.h.
The documentation for this class was generated from the following files:
include/enfield/Transform/DependencyBuilderPass.h
lib/Transform/DependencyBuilderPass.cpp