Enfield: efd::SolutionImplPass Class Reference
efd::SolutionImplPass Class Reference
Public Member Functions
SolutionImplPass (Solution &sol)
bool run (QModule::Ref qmod) override
void visit (NDQOpMeasure::Ref ref) override
void visit (NDQOpReset::Ref ref) override
void visit (NDQOpU::Ref ref) override
void visit (NDQOpBarrier::Ref ref) override
void visit (NDIfStmt::Ref ref) override
void visit (NDList::Ref ref) override
void visit (NDQOpCX::Ref ref) override
void visit (NDQOpGen::Ref ref) override
Public Member Functions inherited from efd::PassT< void >
PassT ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Public Member Functions inherited from efd::NodeVisitor
virtual void visit (NDQasmVersion::Ref ref)
virtual void visit (NDInclude::Ref ref)
virtual void visit (NDRegDecl::Ref ref)
virtual void visit (NDGateDecl::Ref ref)
virtual void visit (NDOpaque::Ref ref)
virtual void visit (NDBinOp::Ref ref)
virtual void visit (NDUnaryOp::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDStmtList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Additional Inherited Members
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Types inherited from efd::NodeVisitor
typedef NodeVisitor * Ref
Static Public Member Functions inherited from efd::PassT< void >
static bool ClassOf (Pass *ref)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Detailed Description
Definition at line 17 of file QbitAllocator.cpp.
Constructor & Destructor Documentation
SolutionImplPass()
efd::SolutionImplPass::SolutionImplPass (Solution & sol) inline
Definition at line 36 of file QbitAllocator.cpp.
Referenced by efd::QbitAllocator::run().
Member Function Documentation
run()
bool efd::SolutionImplPass::run (QModule::Ref qmod) override
Definition at line 139 of file QbitAllocator.cpp.
References efd::Node::apply(), efd::PassCache::Get(), efd::PassT< T >::getData(), efd::XbitToNumber::getQNode(), efd::XbitToNumber::getQSize(), efd::MappingToString(), efd::Solution::mInitial, efd::QModule::replaceStatement(), efd::QModule::stmt_begin(), and efd::QModule::stmt_end().
visit() [1/8]
void efd::SolutionImplPass::visit (NDQOpMeasure::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 163 of file QbitAllocator.cpp.
visit() [2/8]
void efd::SolutionImplPass::visit (NDQOpReset::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 167 of file QbitAllocator.cpp.
visit() [3/8]
void efd::SolutionImplPass::visit (NDQOpU::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 171 of file QbitAllocator.cpp.
visit() [4/8]
void efd::SolutionImplPass::visit (NDQOpBarrier::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 175 of file QbitAllocator.cpp.
visit() [5/8]
void efd::SolutionImplPass::visit (NDIfStmt::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 179 of file QbitAllocator.cpp.
References efd::NDIfStmt::getQOp().
visit() [6/8]
void efd::SolutionImplPass::visit (NDList::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 183 of file QbitAllocator.cpp.
References efd::Node::getChild(), efd::NDList::getChildNumber(), and efd::Node::setChild().
visit() [7/8]
void efd::SolutionImplPass::visit (NDQOpCX::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 189 of file QbitAllocator.cpp.
visit() [8/8]
void efd::SolutionImplPass::visit (NDQOpGen::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 193 of file QbitAllocator.cpp.
The documentation for this class was generated from the following file:
lib/Transform/Allocators/QbitAllocator.cpp