Enfield: efd::XbitToNumberWrapperPass Class Reference
efd::XbitToNumberWrapperPass Class Reference
WrapperPass that yields a XbitToNumber structure.
#include <XbitToNumberPass.h>
Public Types
typedef XbitToNumberWrapperPass * Ref
typedef std::unique_ptr< XbitToNumberWrapperPass > uRef
typedef std::shared_ptr< XbitToNumberWrapperPass > sRef
Public Types inherited from efd::PassT< XbitToNumber >
typedef PassT< XbitToNumber > * Ref
typedef std::shared_ptr< PassT< XbitToNumber > > sRef
typedef std::unique_ptr< PassT< XbitToNumber > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
bool run (QModule::Ref qmod) override
Public Member Functions inherited from efd::PassT< XbitToNumber >
PassT ()
XbitToNumber getData () const
Gets the resulting data.
XbitToNumber & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create ()
Returns a new instance of this class.
Static Public Member Functions inherited from efd::PassT< XbitToNumber >
static bool ClassOf (Pass *ref)
Static Public Attributes
static uint8_t ID = 0
Additional Inherited Members
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Protected Attributes inherited from efd::PassT< XbitToNumber >
XbitToNumber mData
Detailed Description
WrapperPass that yields a XbitToNumber structure.
Definition at line 69 of file XbitToNumberPass.h.
Member Typedef Documentation
Ref
typedef XbitToNumberWrapperPass* efd::XbitToNumberWrapperPass::Ref
Definition at line 71 of file XbitToNumberPass.h.
sRef
typedef std::shared_ptr<XbitToNumberWrapperPass> efd::XbitToNumberWrapperPass::sRef
Definition at line 73 of file XbitToNumberPass.h.
uRef
typedef std::unique_ptr<XbitToNumberWrapperPass> efd::XbitToNumberWrapperPass::uRef
Definition at line 72 of file XbitToNumberPass.h.
Member Function Documentation
Create()
efd::XbitToNumberWrapperPass::uRef efd::XbitToNumberWrapperPass::Create () static
Returns a new instance of this class.
Definition at line 175 of file XbitToNumberPass.cpp.
run()
bool efd::XbitToNumberWrapperPass::run (QModule::Ref qmod) override
Definition at line 157 of file XbitToNumberPass.cpp.
References efd::QModule::gates_begin(), efd::QModule::gates_end(), efd::QModule::reg_begin(), and efd::QModule::reg_end().
Member Data Documentation
ID
uint8_t efd::XbitToNumberWrapperPass::ID = 0 static
Definition at line 75 of file XbitToNumberPass.h.
The documentation for this class was generated from the following files:
include/enfield/Transform/XbitToNumberPass.h
lib/Transform/XbitToNumberPass.cpp