#ifndef __EFD_QBIT_ALLOCATOR_H__
#define __EFD_QBIT_ALLOCATOR_H__

#include "enfield/Arch/ArchGraph.h"
#include "enfield/Transform/DependencyBuilderPass.h"
#include "enfield/Support/CommandLine.h"
#include "enfield/Support/Stats.h"

namespace efd {
    /// \brief Base abstract class that allocates the qbits used in the program to
    /// the qbits that are in the physical architecture.
    class QbitAllocator : public PassT<Mapping> {
        public:
            typedef QbitAllocator* Ref;
            typedef std::unique_ptr<QbitAllocator> uRef;

            typedef std::vector<std::string> BasisVector;
            typedef DependencyBuilder::DepsSet DepsSet;
            typedef DependencyBuilder::DepsSet::iterator Iterator;

        private:
            /// \brief Inlines all gates, but those flagged.
            void inlineAllGates();

            /// \brief Replace all qbits from the program with the architecture's qbits. 
            void replaceWithArchSpecs();

            /// \brief Rename all the qbits, taking into account the \em mMapping, and
            /// the swaps generated by the compiler.
            void renameQbits();

        protected:
            bool mInlineAll;
            ArchGraph::sRef mArchGraph;
            BasisVector mBasis;
            QModule::Ref mMod;

            uint32_t mVQubits;
            uint32_t mPQubits;

            QbitAllocator(ArchGraph::sRef archGraph);

            /// \brief Executes the allocation algorithm after the preprocessing.
            virtual Mapping allocate(QModule::Ref qmod) = 0;

        public:
            bool run(QModule::Ref qmod) override;

            /// \brief Flags the QbitAllocator to inline all gates, but those inside the
            /// \p basis vector, before mapping.
            void setInlineAll(BasisVector basis = {});
            /// \brief Flags the QbitAllocator not to inline.
            void setDontInline();
    };

    /// \brief Generates an assignment mapping (maps the architecture's qubits
    /// to the logical ones) of size \p archQ.
    Assign GenAssignment(uint32_t archQ, Mapping mapping, bool fill = true);

    /// \brief Fills the unmapped qubits with the ones missing.
    void Fill(uint32_t archQ, Mapping& mapping);
    void Fill(Mapping& mapping, Assign& assign);

    /// \brief Returns an identity mapping.
    Mapping IdentityMapping(uint32_t progQ);

    /// \brief Prints the mapping \p m to a string and returns it.
    std::string MappingToString(Mapping m);
}

extern efd::Stat<uint32_t> TotalCost;
extern efd::Opt<uint32_t> SwapCost;
extern efd::Opt<uint32_t> RevCost;
extern efd::Opt<uint32_t> LCXCost;

#endif
