Enfield: efd::BoundedSIDepSolver Class Reference
efd::BoundedSIDepSolver Class Reference
Implementation of DepSolverQAllocator that bounds the subgraph isomorphism search.
#include <BoundedSIDepSolver.h>
Public Types
typedef BoundedSIDepSolver * Ref
typedef std::unique_ptr< BoundedSIDepSolver > uRef
Public Types inherited from efd::QbitAllocator
typedef QbitAllocator * Ref
typedef std::unique_ptr< QbitAllocator > uRef
typedef Solution::Mapping Mapping
typedef std::vector< std::string > BasisVector
typedef DependencyBuilder::DepsSet DepsSet
typedef DependencyBuilder::DepsSet::iterator Iterator
Public Types inherited from efd::PassT< Solution >
typedef PassT< Solution > * Ref
typedef std::shared_ptr< PassT< Solution > > sRef
typedef std::unique_ptr< PassT< Solution > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Static Public Member Functions
static uRef Create (ArchGraph::sRef archGraph)
Create a new instance of this class.
Static Public Member Functions inherited from efd::PassT< Solution >
static bool ClassOf (Pass *ref)
Protected Member Functions
BoundedSIDepSolver (ArchGraph::sRef archGraph)
Solution solve (DepsSet &deps) override
Solves the allocation problem, returning a solution.
Protected Member Functions inherited from efd::DepSolverQAllocator
DepSolverQAllocator (ArchGraph::sRef archGraph)
virtual Solution executeAllocation (QModule::Ref qmod) override
Executes the allocation algorithm after the preprocessing.
Protected Member Functions inherited from efd::QbitAllocator
QbitAllocator (ArchGraph::sRef archGraph)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Additional Inherited Members
Public Member Functions inherited from efd::QbitAllocator
bool run (QModule::Ref qmod) override
void setInlineAll (BasisVector basis={})
Flags the QbitAllocator to inline all gates, but those inside the basis vector, before mapping.
void setDontInline ()
Flags the QbitAllocator not to inline.
Public Member Functions inherited from efd::PassT< Solution >
PassT ()
Solution getData () const
Gets the resulting data.
Solution & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Protected Attributes inherited from efd::QbitAllocator
bool mInlineAll
ArchGraph::sRef mArchGraph
BasisVector mBasis
QModule::Ref mMod
uint32_t mVQubits
uint32_t mPQubits
Protected Attributes inherited from efd::PassT< Solution >
Solution mData
Detailed Description
Implementation of DepSolverQAllocator that bounds the subgraph isomorphism search.
Definition at line 14 of file BoundedSIDepSolver.h.
Member Typedef Documentation
Ref
typedef BoundedSIDepSolver* efd::BoundedSIDepSolver::Ref
Definition at line 16 of file BoundedSIDepSolver.h.
uRef
typedef std::unique_ptr<BoundedSIDepSolver> efd::BoundedSIDepSolver::uRef
Definition at line 17 of file BoundedSIDepSolver.h.
Constructor & Destructor Documentation
BoundedSIDepSolver()
BoundedSIDepSolver::BoundedSIDepSolver (ArchGraph::sRef archGraph) protected
Definition at line 56 of file BoundedSIDepSolver.cpp.
References efd::DepSolverQAllocator::DepSolverQAllocator().
Referenced by Create().
Member Function Documentation
Create()
BoundedSIDepSolver::uRef BoundedSIDepSolver::Create (ArchGraph::sRef archGraph) static
Create a new instance of this class.
Definition at line 59 of file BoundedSIDepSolver.cpp.
References BoundedSIDepSolver().
solve()
Solution BoundedSIDepSolver::solve (DepsSet & deps) override protected virtual
Solves the allocation problem, returning a solution.
Implements efd::DepSolverQAllocator.
Definition at line 63 of file BoundedSIDepSolver.cpp.
References efd::ApproxTSFinder::ApproxTSFinder(), bsi::TracebackInfo::cost, efd::EXIT_multi_deps, efd::EXIT_unreachable, efd::Fill(), efd::ApproxTSFinder::find(), efd::GenAssignment(), efd::Timer::getMilliseconds(), efd::Dependencies::getSize(), efd::Opt< T >::getVal(), efd::Graph::hasEdge(), efd::IdentityMapping(), efd::Operation::K_OP_CNOT, efd::Operation::K_OP_REV, efd::Operation::K_OP_SWAP, bsi::TracebackInfo::m, efd::MappingToString(), efd::QbitAllocator::mArchGraph, efd::Dependencies::mCallPoint, efd::Solution::mCost, efd::Dep::mFrom, efd::Solution::mInitial, efd::Operation::mK, efd::Solution::mOpSeqs, efd::QbitAllocator::mPQubits, efd::Dep::mTo, efd::Operation::mU, efd::Operation::mV, efd::QbitAllocator::mVQubits, efd::Dependencies::operator[](), bsi::TracebackInfo::parent, RevCost, efd::Timer::start(), efd::Timer::stop(), SwapCost, efd::Node::toString(), efd::Swap::u, and efd::Swap::v.
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/BoundedSIDepSolver.h
lib/Transform/Allocators/BoundedSIDepSolver.cpp