Enfield: efd::SemanticVerifierVisitor Class Reference
efd::SemanticVerifierVisitor Class Reference
Public Member Functions
SemanticVerifierVisitor (XbitToNumber &xtonsrc, XbitToNumber &xtontgt, CircuitGraph::Iterator &it, Mapping initial)
void visit (NDQOpMeasure::Ref ref) override
void visit (NDQOpReset::Ref ref) override
void visit (NDQOpU::Ref ref) override
void visit (NDQOpCX::Ref ref) override
void visit (NDQOpBarrier::Ref ref) override
void visit (NDQOpGen::Ref ref) override
void visit (NDIfStmt::Ref ref) override
Public Member Functions inherited from efd::NodeVisitor
virtual void visit (NDQasmVersion::Ref ref)
virtual void visit (NDInclude::Ref ref)
virtual void visit (NDRegDecl::Ref ref)
virtual void visit (NDGateDecl::Ref ref)
virtual void visit (NDOpaque::Ref ref)
virtual void visit (NDBinOp::Ref ref)
virtual void visit (NDUnaryOp::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDList::Ref ref)
virtual void visit (NDStmtList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Public Attributes
bool mSuccess
Additional Inherited Members
Public Types inherited from efd::NodeVisitor
typedef NodeVisitor * Ref
Detailed Description
Definition at line 33 of file SemanticVerifierPass.cpp.
Constructor & Destructor Documentation
SemanticVerifierVisitor()
SemanticVerifierVisitor::SemanticVerifierVisitor (XbitToNumber & xtonsrc, XbitToNumber & xtontgt, CircuitGraph::Iterator & it, Mapping initial)
Definition at line 75 of file SemanticVerifierPass.cpp.
References efd::CircuitGraph::Iterator::next().
Member Function Documentation
visit() [1/7]
void SemanticVerifierVisitor::visit (NDQOpMeasure::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 287 of file SemanticVerifierPass.cpp.
References efd::NDQOpMeasure::getCBit(), efd::XbitToNumber::getCUId(), efd::Node::getKind(), efd::NDQOpMeasure::getQBit(), efd::XbitToNumber::getQUId(), mSuccess, and efd::Node::toString().
visit() [2/7]
void SemanticVerifierVisitor::visit (NDQOpReset::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 310 of file SemanticVerifierPass.cpp.
visit() [3/7]
void SemanticVerifierVisitor::visit (NDQOpU::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 314 of file SemanticVerifierPass.cpp.
visit() [4/7]
void SemanticVerifierVisitor::visit (NDQOpCX::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 318 of file SemanticVerifierPass.cpp.
visit() [5/7]
void SemanticVerifierVisitor::visit (NDQOpBarrier::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 322 of file SemanticVerifierPass.cpp.
visit() [6/7]
void SemanticVerifierVisitor::visit (NDQOpGen::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 326 of file SemanticVerifierPass.cpp.
References efd::NDQOpGen::getIntrinsicKind(), efd::NDQOp::getQArgs(), efd::XbitToNumber::getQUId(), efd::NDQOpGen::isIntrinsic(), and efd::NDQOpGen::K_INTRINSIC_SWAP.
visit() [7/7]
void SemanticVerifierVisitor::visit (NDIfStmt::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 343 of file SemanticVerifierPass.cpp.
References efd::NDIfStmt::getQOp().
Member Data Documentation
mSuccess
bool efd::SemanticVerifierVisitor::mSuccess
Definition at line 71 of file SemanticVerifierPass.cpp.
Referenced by visit().
The documentation for this class was generated from the following file:
lib/Transform/SemanticVerifierPass.cpp