Enfield: efd::BFSPathFinder Class Reference
efd::BFSPathFinder Class Reference
Finds swaps for one restriction only.
#include <BFSPathFinder.h>
Public Types
typedef BFSPathFinder * Ref
typedef std::unique_ptr< BFSPathFinder > uRef
typedef std::shared_ptr< BFSPathFinder > sRef
Public Types inherited from efd::PathFinder
typedef PathFinder * Ref
typedef std::shared_ptr< PathFinder > sRef
Public Member Functions
BFSPathFinder ()
std::vector< uint32_t > find (Graph::Ref g, uint32_t u, uint32_t v) override
Searches for a path from u to v in the graph g.
Static Public Member Functions
static uRef Create ()
Creates one instance of this finder.
Detailed Description
Finds swaps for one restriction only.
Definition at line 8 of file BFSPathFinder.h.
Member Typedef Documentation
Ref
typedef BFSPathFinder* efd::BFSPathFinder::Ref
Definition at line 10 of file BFSPathFinder.h.
sRef
typedef std::shared_ptr<BFSPathFinder> efd::BFSPathFinder::sRef
Definition at line 12 of file BFSPathFinder.h.
uRef
typedef std::unique_ptr<BFSPathFinder> efd::BFSPathFinder::uRef
Definition at line 11 of file BFSPathFinder.h.
Constructor & Destructor Documentation
BFSPathFinder()
efd::BFSPathFinder::BFSPathFinder ()
Definition at line 8 of file BFSPathFinder.cpp.
Member Function Documentation
Create()
efd::BFSPathFinder::uRef efd::BFSPathFinder::Create () static
Creates one instance of this finder.
Definition at line 59 of file BFSPathFinder.cpp.
Referenced by efd::PathGuidedSolBuilder::build(), and efd::DynprogQAllocator::buildStdSolution().
find()
std::vector< uint32_t > efd::BFSPathFinder::find (Graph::Ref g, uint32_t u, uint32_t v) override virtual
Searches for a path from u to v in the graph g.
This function is to be implemented by the concrete classes. It should return the path from u to v (including them both).
Implements efd::PathFinder.
Definition at line 11 of file BFSPathFinder.cpp.
Referenced by efd::GreedyCktQAllocator::buildStdSolution(), and efd::IBMQAllocator::buildStdSolution().
The documentation for this class was generated from the following files:
include/enfield/Support/BFSPathFinder.h
lib/Support/BFSPathFinder.cpp