Enfield: lib/Transform/IntrinsicGateCostPass.cpp File Reference
IntrinsicGateCostPass.cpp File Reference
#include "enfield/Transform/IntrinsicGateCostPass.h"
#include "enfield/Support/CommandLine.h"
Variables
efd::Opt< uint32_t > SwapCost ("-swap-cost", "Cost of using a swap function.", 7, false)
efd::Opt< uint32_t > RevCost ("-rev-cost", "Cost of using a reverse edge.", 4, false)
efd::Opt< uint32_t > LCXCost ("-lcx-cost", "Cost of using long cnot gate.", 10, false)
Variable Documentation
LCXCost
efd::Opt<uint32_t> LCXCost("-lcx-cost", "Cost of using long cnot gate.", 10, false)
Referenced by efd::QbitterSolBuilder::build(), efd::DynprogQAllocator::buildStdSolution(), and efd::IntrinsicGateCostPass::run().
RevCost
efd::Opt<uint32_t> RevCost("-rev-cost", "Cost of using a reverse edge.", 4, false)
Referenced by efd::QbitterSolBuilder::build(), efd::GreedyCktQAllocator::buildStdSolution(), efd::DynprogQAllocator::buildStdSolution(), efd::IBMQAllocator::buildStdSolution(), and efd::IntrinsicGateCostPass::run().
SwapCost
efd::Opt<uint32_t> SwapCost("-swap-cost", "Cost of using a swap function.", 7, false)
Referenced by efd::GreedyCktQAllocator::buildStdSolution(), efd::DynprogQAllocator::buildStdSolution(), efd::IBMQAllocator::buildStdSolution(), and efd::IntrinsicGateCostPass::run().