Enfield: efd::DepSolverQAllocator Class Reference
efd::DepSolverQAllocator Class Reference abstract
Wrapper for making it easier to implement algorithms for Qubit Allocation.
#include <DepSolverQAllocator.h>
Protected Member Functions
DepSolverQAllocator (ArchGraph::sRef archGraph)
virtual Solution solve (DepsSet &deps)=0
Solves the allocation problem, returning a solution.
virtual Solution executeAllocation (QModule::Ref qmod) override
Executes the allocation algorithm after the preprocessing.
Protected Member Functions inherited from efd::QbitAllocator
QbitAllocator (ArchGraph::sRef archGraph)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Additional Inherited Members
Public Types inherited from efd::QbitAllocator
typedef QbitAllocator * Ref
typedef std::unique_ptr< QbitAllocator > uRef
typedef Solution::Mapping Mapping
typedef std::vector< std::string > BasisVector
typedef DependencyBuilder::DepsSet DepsSet
typedef DependencyBuilder::DepsSet::iterator Iterator
Public Types inherited from efd::PassT< Solution >
typedef PassT< Solution > * Ref
typedef std::shared_ptr< PassT< Solution > > sRef
typedef std::unique_ptr< PassT< Solution > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions inherited from efd::QbitAllocator
bool run (QModule::Ref qmod) override
void setInlineAll (BasisVector basis={})
Flags the QbitAllocator to inline all gates, but those inside the basis vector, before mapping.
void setDontInline ()
Flags the QbitAllocator not to inline.
Public Member Functions inherited from efd::PassT< Solution >
PassT ()
Solution getData () const
Gets the resulting data.
Solution & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions inherited from efd::PassT< Solution >
static bool ClassOf (Pass *ref)
Protected Attributes inherited from efd::QbitAllocator
bool mInlineAll
ArchGraph::sRef mArchGraph
BasisVector mBasis
QModule::Ref mMod
uint32_t mVQubits
uint32_t mPQubits
Protected Attributes inherited from efd::PassT< Solution >
Solution mData
Detailed Description
Wrapper for making it easier to implement algorithms for Qubit Allocation.
It just gives a set of dependencies (note that it can be nested) and outputs a solution for the current instance.
Definition at line 11 of file DepSolverQAllocator.h.
Constructor & Destructor Documentation
DepSolverQAllocator()
DepSolverQAllocator::DepSolverQAllocator (ArchGraph::sRef archGraph) protected
Definition at line 6 of file DepSolverQAllocator.cpp.
References efd::QbitAllocator::QbitAllocator().
Referenced by efd::BoundedSIDepSolver::BoundedSIDepSolver(), efd::DynprogDepSolver::DynprogDepSolver(), and efd::SimpleDepSolver::SimpleDepSolver().
Member Function Documentation
executeAllocation()
Solution DepSolverQAllocator::executeAllocation (QModule::Ref qmod) override protected virtual
Executes the allocation algorithm after the preprocessing.
Implements efd::QbitAllocator.
Definition at line 8 of file DepSolverQAllocator.cpp.
References efd::PassCache::Get(), efd::PassT< T >::getData(), efd::DependencyBuilder::getDependencies(), efd::QbitAllocator::mMod, and solve().
solve()
virtual Solution efd::DepSolverQAllocator::solve (DepsSet & deps) protected pure virtual
Solves the allocation problem, returning a solution.
Implemented in efd::DynprogDepSolver, efd::SimpleDepSolver, and efd::BoundedSIDepSolver.
Referenced by executeAllocation().
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/DepSolverQAllocator.h
lib/Transform/Allocators/DepSolverQAllocator.cpp