Enfield: efd::FlattenPass Class Reference
efd::FlattenPass Class Reference
Flattens the given QModule.
#include <FlattenPass.h>
Public Types
typedef FlattenPass * Ref
typedef std::unique_ptr< FlattenPass > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
bool run (QModule::Ref qmod) override
Public Member Functions inherited from efd::PassT< void >
PassT ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create ()
Static Public Member Functions inherited from efd::PassT< void >
static bool ClassOf (Pass *ref)
Static Public Attributes
static uint8_t ID = 0
Additional Inherited Members
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Detailed Description
Flattens the given QModule.
It will expand all implicit operations. e.g.: qreg b[2]; x b; -> qreg b[2]; x b[0]; x b[1];
Definition at line 12 of file FlattenPass.h.
Member Typedef Documentation
Ref
typedef FlattenPass* efd::FlattenPass::Ref
Definition at line 14 of file FlattenPass.h.
uRef
typedef std::unique_ptr<FlattenPass> efd::FlattenPass::uRef
Definition at line 15 of file FlattenPass.h.
Member Function Documentation
Create()
FlattenPass::uRef efd::FlattenPass::Create () static
Definition at line 119 of file FlattenPass.cpp.
run()
bool efd::FlattenPass::run (QModule::Ref qmod) override
Definition at line 105 of file FlattenPass.cpp.
References efd::FlattenVisitor::mRepMap, efd::QModule::replaceStatement(), efd::QModule::stmt_begin(), and efd::QModule::stmt_end().
Member Data Documentation
ID
uint8_t efd::FlattenPass::ID = 0 static
Definition at line 17 of file FlattenPass.h.
The documentation for this class was generated from the following files:
include/enfield/Transform/FlattenPass.h
lib/Transform/FlattenPass.cpp