Enfield: efd::NDGOpList Class Reference
efd::NDGOpList Class Reference
Node for list of qubit operation sequences inside gate declarations.
#include <Nodes.h>
Public Types
typedef NDGOpList * Ref
typedef std::unique_ptr< NDGOpList > uRef
Public Types inherited from efd::NDList
typedef NDList * Ref
typedef std::unique_ptr< NDList > uRef
Public Types inherited from efd::Node
enum Kind {
K_QASM_VERSION, K_INCLUDE, K_REG_DECL, K_GATE_DECL,
K_GATE_OPAQUE, K_QOP, K_QOP_MEASURE, K_QOP_RESET,
K_QOP_BARRIER, K_QOP_CX, K_QOP_U, K_QOP_GEN,
K_BINOP, K_UNARYOP, K_ID_REF, K_LIST,
K_STMT_LIST, K_GOP_LIST, K_IF_STMT, K_LIT_INT,
K_LIT_REAL, K_LIT_STRING
}
typedef Node * Ref
typedef std::unique_ptr< Node > uRef
typedef std::shared_ptr< Node > sRef
typedef std::vector< uRef >::iterator Iterator
typedef std::vector< uRef >::const_iterator ConstIterator
Public Member Functions
std::string toString (bool pretty=false) const override
Returns a std::string representation of this Node and its childrem.
void apply (NodeVisitor *visitor) override
Used by visitor classes.
Public Member Functions inherited from efd::NDList
virtual ~NDList ()
void cloneChildrem (const NDList *list)
Deep-copies the childrem of list.
Iterator addChild (Node::uRef child)
Appends a child to the end of the list.
Iterator addChild (Iterator it, Node::uRef child)
Inserts a child in the iterator it. The iterator goes to the new inserted element.
Iterator addChildren (std::vector< Node::uRef > children)
Appends children to the end of the list.
Iterator addChildren (Iterator it, std::vector< Node::uRef > children)
Inserts children in the iterator it. The iterator goes to the first new inserted element.
Iterator removeChild (Iterator it)
Removes the child in the iterator it. The iterator moves to the next element.
void removeChild (Node::Ref child)
Removes the child (must exist).
void clear ()
Clears all the childrem.
uint32_t getChildNumber () const override
Returns the number of childrem of this node.
Public Member Functions inherited from efd::Node
virtual ~Node ()
Ref getChild (uint32_t i) const
Gets the i-th child.
void setChild (uint32_t i, uRef ref)
Sets the i-th child.
Iterator findChild (Node::Ref ref)
Returns a iterator pointing to the given child.
Iterator begin ()
Returns a iterator to the beginning of the vector.
Iterator end ()
Returns a iterator to the end of the vector.
ConstIterator begin () const
Returns a const iterator to the beginning of the vector.
ConstIterator end () const
Returns a const iterator to the end of the vector.
Kind getKind () const
Returns the kind of this node.
void print (std::ostream &O=std::cout, bool pretty=false)
Prints from this node, recursively to O.
void print (bool pretty=false)
Prints to the standard output.
bool isEmpty () const
Returns whether this node has any information.
bool wasGenerated () const
Returns whether this node was generated by the compiler.
void setGenerated ()
bool isInInclude () const
Returns whether this node is in a include node.
void setInInclude ()
Ref getParent () const
Returns the parent node of the current node.
void setParent (Ref ref)
Sets the parent node of the current node.
bool equals (Node::Ref ref) const
Compares recursively the equality between two nodes.
virtual std::string getOperation () const
Returns a std::string representation of the operation.
Node::uRef clone () const
Clones the current node (deep copy).
Static Public Member Functions
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create ()
Creates a new instance of this node.
Static Public Member Functions inherited from efd::NDList
static bool ClassOf (const Node *node)
Returns whether the node is an instance of this class.
static uRef Create (Kind k)
Creates a new instance of this node with a specific k.
static uRef Create ()
Creates a new instance of this node with the kind K_LIST.
Protected Member Functions
NDGOpList ()
Node::uRef cloneImpl () const override
Clones the current node (deep copy).
Protected Member Functions inherited from efd::NDList
NDList (Kind k)
Protected Member Functions inherited from efd::Node
Node (Kind k, bool empty=false)
Constructs the node, initially empty (with no information).
void innerAddChild (uRef ref)
Adds a child to this node. It should be used only for construction of each derived class.
virtual bool equalsImpl (Node::Ref ref) const
Extend the 'equals' implementation by implementing this method.
Additional Inherited Members
Protected Attributes inherited from efd::Node
Kind mK
The kind of the node.
bool mIsEmpty
Holds whether this node has no information.
bool mWasGenerated
True if it was generated by the compiler.
bool mInInclude
True if it is a node inside an include node.
std::vector< uRef > mChild
The childrem nodes.
Ref mParent
Detailed Description
Node for list of qubit operation sequences inside gate declarations.
Definition at line 399 of file Nodes.h.
Member Typedef Documentation
Ref
typedef NDGOpList* efd::NDGOpList::Ref
Definition at line 401 of file Nodes.h.
uRef
typedef std::unique_ptr<NDGOpList> efd::NDGOpList::uRef
Definition at line 402 of file Nodes.h.
Constructor & Destructor Documentation
NDGOpList()
efd::NDGOpList::NDGOpList () protected
Definition at line 478 of file Nodes.cpp.
Member Function Documentation
apply()
void efd::NDGOpList::apply (NodeVisitor * visitor) override virtual
Used by visitor classes.
Reimplemented from efd::NDList.
Definition at line 487 of file Nodes.cpp.
References efd::NodeVisitor::visit().
ClassOf()
bool efd::NDGOpList::ClassOf (const Node * node) static
Returns whether the node is an instance of this class.
Definition at line 504 of file Nodes.cpp.
References efd::Node::getKind().
cloneImpl()
efd::Node::uRef efd::NDGOpList::cloneImpl () const override protected virtual
Clones the current node (deep copy).
Reimplemented from efd::NDList.
Definition at line 481 of file Nodes.cpp.
References Create().
Create()
efd::NDGOpList::uRef efd::NDGOpList::Create () static
Creates a new instance of this node.
Definition at line 508 of file Nodes.cpp.
Referenced by cloneImpl().
toString()
std::string efd::NDGOpList::toString (bool pretty = false) const override virtual
Returns a std::string representation of this Node and its childrem.
Reimplemented from efd::NDList.
Definition at line 491 of file Nodes.cpp.
The documentation for this class was generated from the following files:
include/enfield/Analysis/Nodes.h
lib/Analysis/Nodes.cpp