Enfield: efd::PathGuidedSolBuilder Class Reference
efd::PathGuidedSolBuilder Class Reference
Solves the dependencies by looking at the path in the graph.
#include <PathGuidedSolBuilder.h>
Public Types
typedef PathGuidedSolBuilder * Ref
typedef std::unique_ptr< PathGuidedSolBuilder > uRef
Public Types inherited from efd::SolutionBuilder
typedef QbitAllocator::Mapping Mapping
typedef QbitAllocator::DepsSet DepsSet
typedef SolutionBuilder * Ref
typedef std::shared_ptr< SolutionBuilder > sRef
Public Member Functions
Solution build (Mapping initial, DepsSet &deps, ArchGraph::Ref g) override
Constructs a solution (QbitAllocator::Solution) from the mapping initial, with deps dependencies in the architecture g.
void setPathFinder (PathFinder::sRef finder)
Sets the path finder to be used.
Public Member Functions inherited from efd::SolutionBuilder
SolutionBuilder ()
Public Member Functions inherited from efd::BitOptions< SolutionBuilderOptions, SolutionBuilderOptions::KeepStats >
BitOptions ()
void set (SolutionBuilderOptions option, bool value=true)
Sets the bit related to option to value.
bool get (SolutionBuilderOptions option) const
Gets the value related to the bit that option represents.
Static Public Member Functions
static uRef Create ()
Creates an instance of this class.
Protected Attributes
PathFinder::sRef mPathFinder
Detailed Description
Solves the dependencies by looking at the path in the graph.
Definition at line 9 of file PathGuidedSolBuilder.h.
Member Typedef Documentation
Ref
typedef PathGuidedSolBuilder* efd::PathGuidedSolBuilder::Ref
Definition at line 11 of file PathGuidedSolBuilder.h.
uRef
typedef std::unique_ptr<PathGuidedSolBuilder> efd::PathGuidedSolBuilder::uRef
Definition at line 12 of file PathGuidedSolBuilder.h.
Member Function Documentation
build()
efd::Solution efd::PathGuidedSolBuilder::build (Mapping initial, DepsSet & deps, ArchGraph::Ref g) override virtual
Constructs a solution (QbitAllocator::Solution) from the mapping initial, with deps dependencies in the architecture g.
Implements efd::SolutionBuilder.
Definition at line 23 of file PathGuidedSolBuilder.cpp.
References efd::BFSPathFinder::Create(), efd::PathFinder::find(), efd::GenAssignment(), efd::BitOptions< ETy, last >::get(), efd::Stat< T >::getVal(), efd::Opt< T >::getVal(), efd::Graph::hasEdge(), efd::ImproveInitial, efd::ArchGraph::isReverseEdge(), efd::Operation::K_OP_CNOT, efd::Operation::K_OP_REV, efd::Operation::K_OP_SWAP, efd::KeepStats, efd::Dependencies::mCallPoint, efd::Solution::mCost, efd::Dep::mFrom, efd::Solution::mInitial, efd::Solution::mOpSeqs, mPathFinder, efd::Dep::mTo, efd::Stat< T >::operator+=(), efd::Stat< T >::operator/=(), efd::Dependencies::operator[](), RevCost, efd::Graph::size(), and SwapCost.
Create()
efd::PathGuidedSolBuilder::uRef efd::PathGuidedSolBuilder::Create () static
Creates an instance of this class.
Definition at line 130 of file PathGuidedSolBuilder.cpp.
setPathFinder()
void efd::PathGuidedSolBuilder::setPathFinder (PathFinder::sRef finder)
Sets the path finder to be used.
Definition at line 126 of file PathGuidedSolBuilder.cpp.
References mPathFinder.
Member Data Documentation
mPathFinder
PathFinder::sRef efd::PathGuidedSolBuilder::mPathFinder protected
Definition at line 15 of file PathGuidedSolBuilder.h.
Referenced by build(), and setPathFinder().
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/PathGuidedSolBuilder.h
lib/Transform/Allocators/PathGuidedSolBuilder.cpp