Enfield: efd::ApproxTSFinder Class Reference
efd::ApproxTSFinder Class Reference
#include <ApproxTSFinder.h>
Public Types
typedef ApproxTSFinder * Ref
typedef std::unique_ptr< ApproxTSFinder > uRef
Public Types inherited from efd::TokenSwapFinder
typedef TokenSwapFinder * Ref
typedef std::unique_ptr< TokenSwapFinder > uRef
Public Member Functions
ApproxTSFinder (Graph::sRef graph)
SwapSeq find (Assign from, Assign to) override
Finds a swap sequence to reach to from from.
SwapSeq find (Graph::Ref graph, Assign from, Assign to) override
Finds a swap sequence to reach to from from in graph.
Static Public Member Functions
static uRef Create (Graph::sRef graph=nullptr)
Creates an instance of this class.
Additional Inherited Members
Protected Member Functions inherited from efd::TokenSwapFinder
TokenSwapFinder (Graph::sRef graph)
Protected Attributes inherited from efd::TokenSwapFinder
Graph::sRef mG
Detailed Description
Definition at line 7 of file ApproxTSFinder.h.
Member Typedef Documentation
Ref
typedef ApproxTSFinder* efd::ApproxTSFinder::Ref
Definition at line 9 of file ApproxTSFinder.h.
uRef
typedef std::unique_ptr<ApproxTSFinder> efd::ApproxTSFinder::uRef
Definition at line 10 of file ApproxTSFinder.h.
Constructor & Destructor Documentation
ApproxTSFinder()
efd::ApproxTSFinder::ApproxTSFinder (Graph::sRef graph)
Definition at line 472 of file ApproxTSFinder.cpp.
References efd::TokenSwapFinder::TokenSwapFinder().
Referenced by Create(), and efd::BoundedSIDepSolver::solve().
Member Function Documentation
Create()
efd::ApproxTSFinder::uRef efd::ApproxTSFinder::Create (Graph::sRef graph = nullptr) static
Creates an instance of this class.
Definition at line 475 of file ApproxTSFinder.cpp.
References ApproxTSFinder().
find() [1/2]
efd::SwapSeq efd::ApproxTSFinder::find (Assign from, Assign to) override virtual
Finds a swap sequence to reach to from from.
Implements efd::TokenSwapFinder.
Definition at line 468 of file ApproxTSFinder.cpp.
References find(), and efd::TokenSwapFinder::mG.
Referenced by efd::BoundedSIDepSolver::solve().
find() [2/2]
efd::SwapSeq efd::ApproxTSFinder::find (Graph::Ref graph, Assign from, Assign to) override virtual
Finds a swap sequence to reach to from from in graph.
Implements efd::TokenSwapFinder.
Definition at line 376 of file ApproxTSFinder.cpp.
References efd::Graph::size().
Referenced by find().
The documentation for this class was generated from the following files:
include/enfield/Support/ApproxTSFinder.h
lib/Support/ApproxTSFinder.cpp