Enfield: efd::QModule Class Reference
efd::QModule Class Reference
Qasm module representation.
#include <QModule.h>
Public Types
typedef QModule * Ref
typedef std::unique_ptr< QModule > uRef
typedef std::shared_ptr< QModule > sRef
typedef std::vector< NDInclude::uRef > IncludeVector
typedef std::vector< NDRegDecl::Ref > RegsVector
typedef std::vector< NDGateSign::Ref > GatesVector
typedef std::unordered_map< std::string, NDRegDecl::uRef > RegsMap
typedef std::unordered_map< std::string, NDGateSign::uRef > GatesMap
typedef std::unordered_map< std::string, NDId::Ref > IdMap
typedef std::unordered_map< NDGateDecl::Ref, IdMap > GateIdMap
typedef Node::Iterator Iterator
typedef Node::ConstIterator ConstIterator
typedef RegsVector::iterator RegIterator
typedef RegsVector::const_iterator RegConstIterator
typedef GatesVector::iterator GateIterator
typedef GatesVector::const_iterator GateConstIterator
Public Member Functions
~QModule ()
NDQasmVersion::Ref getVersion ()
Gets the qasm version.
void setVersion (NDQasmVersion::uRef version)
Sets the qasm version.
void insertInclude (NDInclude::uRef incl)
Inserts an include node.
void insertReg (NDRegDecl::uRef reg)
Inserts a register declaration node.
void removeAllQRegs ()
Removes all quantum registers.
Iterator findStatement (Node::Ref ref)
Returns a iterator pointing to ref, if it exists.
void removeStatement (Iterator it)
Removes the node pointed by it.
Iterator inlineCall (NDQOp::Ref call)
Inlines call and returns an iterator to the first node inserted.
Iterator insertStatementAfter (Iterator it, Node::uRef ref)
Inserts ref after it, and returns a iterator to this node.
Iterator insertStatementBefore (Iterator it, Node::uRef ref)
Inserts ref before it, and returns a iterator to this node.
Iterator insertStatementFront (Node::uRef ref)
Inserts ref at the beginning, and returns a iterator to this node.
Iterator insertStatementLast (Node::uRef ref)
Inserts ref at the back, and returns a iterator to this node.
Iterator replaceStatement (Node::Ref stmt, std::vector< Node::uRef > stmts)
Replaces the stmt by the vector stmts.
void clearStatements ()
Removes all statements present int this module.
void insertGate (NDGateSign::uRef gate)
Inserts a gate to the QModule.
Node::Ref getStatement (uint32_t i)
Returns the i-th statement.
uint32_t getNumberOfRegs () const
Return the number of registers.
uint32_t getNumberOfGates () const
Return the number of gates.
uint32_t getNumberOfStmts () const
Return the number of statements.
RegIterator reg_begin ()
Iterator to the beginning of the register node vector.
RegConstIterator reg_begin () const
ConstIterator to the beginning of the register node vector.
RegIterator reg_end ()
Iterator to the end of the register node vector.
RegConstIterator reg_end () const
ConstIterator to the end of the register node vector.
GateIterator gates_begin ()
Iterator to the beginning of the gate declaration node vector.
GateConstIterator gates_begin () const
ConstIterator to the beginning of the gate declaration node vector.
GateIterator gates_end ()
Iterator to the end of the gate declaration node vector.
GateConstIterator gates_end () const
ConstIterator to the end of the gate declaration node vector.
Iterator stmt_begin ()
Iterator to the beginning of the statement node vector.
ConstIterator stmt_begin () const
ConstIterator to the beginning of the statement node vector.
Iterator stmt_end ()
Iterator to the end of the statement node vector.
ConstIterator stmt_end () const
ConstIterator to the end of the statement node vector.
void orderby (std::vector< uint32_t > order)
Order the statements according to order.
void print (std::ostream &O=std::cout, bool pretty=false, bool printGates=false) const
Prints the QModule to a std::ostream.
std::string toString (bool pretty=false, bool printGates=false) const
Returns a std::string representation of the QModule.
Node::Ref getQVar (std::string id, NDGateDecl::Ref gate=nullptr) const
Gets the quantum variable mapped to id from some gate.
bool hasQVar (std::string id, NDGateDecl::Ref gate=nullptr) const
Returns true if there is a quantum variable id inside gate gate (if not null).
NDGateSign::Ref getQGate (std::string id) const
Gets the quantum gate mapped to id.
bool hasQGate (std::string id) const
Returns true if there is a quantum gate id.
uRef clone () const
Clones the current qmodule.
Static Public Member Functions
static uRef Create ()
Create a new empty QModule.
static uRef GetFromAST (Node::uRef ref)
Process the AST in order to obtain the QModule.
static uRef Parse (std::string filename, std::string path="./")
Parses the file filename and returns a QModule.
static uRef ParseString (std::string program)
Parses the string program and returns a QModule.
Detailed Description
Qasm module representation.
Definition at line 13 of file QModule.h.
Member Typedef Documentation
ConstIterator
typedef Node::ConstIterator efd::QModule::ConstIterator
Definition at line 30 of file QModule.h.
GateConstIterator
typedef GatesVector::const_iterator efd::QModule::GateConstIterator
Definition at line 36 of file QModule.h.
GateIdMap
typedef std::unordered_map<NDGateDecl::Ref, IdMap> efd::QModule::GateIdMap
Definition at line 27 of file QModule.h.
GateIterator
typedef GatesVector::iterator efd::QModule::GateIterator
Definition at line 35 of file QModule.h.
GatesMap
typedef std::unordered_map<std::string, NDGateSign::uRef> efd::QModule::GatesMap
Definition at line 24 of file QModule.h.
GatesVector
typedef std::vector<NDGateSign::Ref> efd::QModule::GatesVector
Definition at line 21 of file QModule.h.
IdMap
typedef std::unordered_map<std::string, NDId::Ref> efd::QModule::IdMap
Definition at line 26 of file QModule.h.
IncludeVector
typedef std::vector<NDInclude::uRef> efd::QModule::IncludeVector
Definition at line 19 of file QModule.h.
Iterator
typedef Node::Iterator efd::QModule::Iterator
Definition at line 29 of file QModule.h.
Ref
typedef QModule* efd::QModule::Ref
Definition at line 15 of file QModule.h.
RegConstIterator
typedef RegsVector::const_iterator efd::QModule::RegConstIterator
Definition at line 33 of file QModule.h.
RegIterator
typedef RegsVector::iterator efd::QModule::RegIterator
Definition at line 32 of file QModule.h.
RegsMap
typedef std::unordered_map<std::string, NDRegDecl::uRef> efd::QModule::RegsMap
Definition at line 23 of file QModule.h.
RegsVector
typedef std::vector<NDRegDecl::Ref> efd::QModule::RegsVector
Definition at line 20 of file QModule.h.
sRef
typedef std::shared_ptr<QModule> efd::QModule::sRef
Definition at line 17 of file QModule.h.
uRef
typedef std::unique_ptr<QModule> efd::QModule::uRef
Definition at line 16 of file QModule.h.
Constructor & Destructor Documentation
~QModule()
efd::QModule::~QModule ()
Definition at line 16 of file QModule.cpp.
References efd::PassCache::Clear().
Member Function Documentation
clearStatements()
void efd::QModule::clearStatements ()
Removes all statements present int this module.
Definition at line 131 of file QModule.cpp.
Referenced by efd::GreedyCktQAllocator::buildStdSolution(), and efd::IBMQAllocator::buildStdSolution().
clone()
efd::QModule::uRef efd::QModule::clone () const
Clones the current qmodule.
Definition at line 349 of file QModule.cpp.
Create()
efd::QModule::uRef efd::QModule::Create () static
Create a new empty QModule.
Definition at line 368 of file QModule.cpp.
References efd::ParseString().
findStatement()
efd::QModule::Iterator efd::QModule::findStatement (Node::Ref ref)
Returns a iterator pointing to ref, if it exists.
Definition at line 53 of file QModule.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), and efd::Node::toString().
gates_begin() [1/2]
efd::QModule::GateIterator efd::QModule::gates_begin ()
Iterator to the beginning of the gate declaration node vector.
Definition at line 202 of file QModule.cpp.
Referenced by efd::XbitToNumberWrapperPass::run(), and efd::DependencyBuilderWrapperPass::run().
gates_begin() [2/2]
efd::QModule::GateConstIterator efd::QModule::gates_begin () const
ConstIterator to the beginning of the gate declaration node vector.
Definition at line 206 of file QModule.cpp.
gates_end() [1/2]
efd::QModule::GateIterator efd::QModule::gates_end ()
Iterator to the end of the gate declaration node vector.
Definition at line 210 of file QModule.cpp.
Referenced by efd::XbitToNumberWrapperPass::run(), and efd::DependencyBuilderWrapperPass::run().
gates_end() [2/2]
efd::QModule::GateConstIterator efd::QModule::gates_end () const
ConstIterator to the end of the gate declaration node vector.
Definition at line 214 of file QModule.cpp.
GetFromAST()
efd::QModule::uRef efd::QModule::GetFromAST (Node::uRef ref) static
Process the AST in order to obtain the QModule.
Definition at line 379 of file QModule.cpp.
References efd::GetIntrinsicGates(), and efd::ProcessAST().
getNumberOfGates()
uint32_t efd::QModule::getNumberOfGates () const
Return the number of gates.
Definition at line 178 of file QModule.cpp.
getNumberOfRegs()
uint32_t efd::QModule::getNumberOfRegs () const
Return the number of registers.
Definition at line 174 of file QModule.cpp.
getNumberOfStmts()
uint32_t efd::QModule::getNumberOfStmts () const
Return the number of statements.
Definition at line 182 of file QModule.cpp.
Referenced by efd::GreedyCktQAllocator::buildStdSolution(), and efd::QModuleQualityEvalPass::run().
getQGate()
efd::NDGateSign::Ref efd::QModule::getQGate (std::string id) const
Gets the quantum gate mapped to id.
Definition at line 336 of file QModule.cpp.
References ERR, efd::EXIT_unknown_resource, and efd::ExitWith().
Referenced by efd::InlineGate(), and efd::InlineAllPass::run().
getQVar()
efd::Node::Ref efd::QModule::getQVar (std::string id, NDGateDecl::Ref gate = nullptr) const
Gets the quantum variable mapped to id from some gate.
Definition at line 300 of file QModule.cpp.
References ERR, efd::EXIT_unknown_resource, efd::ExitWith(), efd::NDDecl::getId(), and efd::NDValue< T >::getVal().
Referenced by efd::UsedBitsVisitor::visit().
getStatement()
efd::Node::Ref efd::QModule::getStatement (uint32_t i)
Returns the i-th statement.
Definition at line 135 of file QModule.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
getVersion()
efd::NDQasmVersion::Ref efd::QModule::getVersion ()
Gets the qasm version.
Definition at line 20 of file QModule.cpp.
hasQGate()
bool efd::QModule::hasQGate (std::string id) const
Returns true if there is a quantum gate id.
Definition at line 344 of file QModule.cpp.
hasQVar()
bool efd::QModule::hasQVar (std::string id, NDGateDecl::Ref gate = nullptr) const
Returns true if there is a quantum variable id inside gate gate (if not null).
Definition at line 321 of file QModule.cpp.
inlineCall()
efd::QModule::Iterator efd::QModule::inlineCall (NDQOp::Ref call)
Inlines call and returns an iterator to the first node inserted.
Definition at line 69 of file QModule.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), efd::Node::findChild(), efd::Node::getParent(), efd::InlineGate(), efd::NDQOp::isGeneric(), and efd::NDQOp::toString().
Referenced by efd::InlineAllPass::run().
insertGate()
void efd::QModule::insertGate (NDGateSign::uRef gate)
Inserts a gate to the QModule.
Definition at line 144 of file QModule.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
insertInclude()
void efd::QModule::insertInclude (NDInclude::uRef incl)
Inserts an include node.
Definition at line 28 of file QModule.cpp.
insertReg()
void efd::QModule::insertReg (NDRegDecl::uRef reg)
Inserts a register declaration node.
Definition at line 32 of file QModule.cpp.
insertStatementAfter()
efd::QModule::Iterator efd::QModule::insertStatementAfter (Iterator it, Node::uRef ref)
Inserts ref after it, and returns a iterator to this node.
Definition at line 91 of file QModule.cpp.
insertStatementBefore()
efd::QModule::Iterator efd::QModule::insertStatementBefore (Iterator it, Node::uRef ref)
Inserts ref before it, and returns a iterator to this node.
Definition at line 96 of file QModule.cpp.
insertStatementFront()
efd::QModule::Iterator efd::QModule::insertStatementFront (Node::uRef ref)
Inserts ref at the beginning, and returns a iterator to this node.
Definition at line 101 of file QModule.cpp.
insertStatementLast()
efd::QModule::Iterator efd::QModule::insertStatementLast (Node::uRef ref)
Inserts ref at the back, and returns a iterator to this node.
Definition at line 107 of file QModule.cpp.
Referenced by efd::GreedyCktQAllocator::buildStdSolution(), and efd::IBMQAllocator::buildStdSolution().
orderby()
void efd::QModule::orderby (std::vector< uint32_t > order)
Order the statements according to order.
Definition at line 234 of file QModule.cpp.
Referenced by efd::LayerBasedOrderingWrapperPass::run().
Parse()
efd::QModule::uRef efd::QModule::Parse (std::string filename, std::string path = "./") static
Parses the file filename and returns a QModule.
Definition at line 390 of file QModule.cpp.
References efd::ParseFile().
Referenced by efd::ParseFile().
ParseString()
efd::QModule::uRef efd::QModule::ParseString (std::string program) static
Parses the string program and returns a QModule.
Definition at line 399 of file QModule.cpp.
References efd::ParseString().
print()
void efd::QModule::print (std::ostream & O = std::cout, bool pretty = false, bool printGates = false) const
Prints the QModule to a std::ostream.
Definition at line 242 of file QModule.cpp.
Referenced by efd::PrintToStream().
reg_begin() [1/2]
efd::QModule::RegIterator efd::QModule::reg_begin ()
Iterator to the beginning of the register node vector.
Definition at line 186 of file QModule.cpp.
Referenced by efd::XbitToNumberWrapperPass::run().
reg_begin() [2/2]
efd::QModule::RegConstIterator efd::QModule::reg_begin () const
ConstIterator to the beginning of the register node vector.
Definition at line 190 of file QModule.cpp.
reg_end() [1/2]
efd::QModule::RegIterator efd::QModule::reg_end ()
Iterator to the end of the register node vector.
Definition at line 194 of file QModule.cpp.
Referenced by efd::XbitToNumberWrapperPass::run().
reg_end() [2/2]
efd::QModule::RegConstIterator efd::QModule::reg_end () const
ConstIterator to the end of the register node vector.
Definition at line 198 of file QModule.cpp.
removeAllQRegs()
void efd::QModule::removeAllQRegs ()
Removes all quantum registers.
Definition at line 38 of file QModule.cpp.
removeStatement()
void efd::QModule::removeStatement (Iterator it)
Removes the node pointed by it.
Definition at line 65 of file QModule.cpp.
replaceStatement()
efd::QModule::Iterator efd::QModule::replaceStatement (Node::Ref stmt, std::vector< Node::uRef > stmts)
Replaces the stmt by the vector stmts.
Definition at line 113 of file QModule.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), and efd::Node::toString().
Referenced by efd::InlineGate(), efd::FlattenPass::run(), efd::ReverseEdgesPass::run(), and efd::StdSolutionImplPass::run().
setVersion()
void efd::QModule::setVersion (NDQasmVersion::uRef version)
Sets the qasm version.
Definition at line 24 of file QModule.cpp.
stmt_begin() [1/2]
efd::QModule::Iterator efd::QModule::stmt_begin ()
Iterator to the beginning of the statement node vector.
Definition at line 218 of file QModule.cpp.
Referenced by efd::IntrinsicGateCostPass::run(), efd::FlattenPass::run(), efd::LayersBuilderPass::run(), efd::ArchVerifierPass::run(), efd::ReverseEdgesPass::run(), efd::InlineAllPass::run(), efd::CircuitGraphBuilderPass::run(), efd::RenameQbitPass::run(), efd::LayerBasedOrderingWrapperPass::run(), efd::StdSolutionImplPass::run(), efd::QModuleQualityEvalPass::run(), efd::SemanticVerifierPass::run(), and efd::DependencyBuilderWrapperPass::run().
stmt_begin() [2/2]
efd::QModule::ConstIterator efd::QModule::stmt_begin () const
ConstIterator to the beginning of the statement node vector.
Definition at line 222 of file QModule.cpp.
stmt_end() [1/2]
efd::QModule::Iterator efd::QModule::stmt_end ()
Iterator to the end of the statement node vector.
Definition at line 226 of file QModule.cpp.
Referenced by efd::IntrinsicGateCostPass::run(), efd::FlattenPass::run(), efd::LayersBuilderPass::run(), efd::ArchVerifierPass::run(), efd::ReverseEdgesPass::run(), efd::InlineAllPass::run(), efd::CircuitGraphBuilderPass::run(), efd::RenameQbitPass::run(), efd::LayerBasedOrderingWrapperPass::run(), efd::StdSolutionImplPass::run(), efd::QModuleQualityEvalPass::run(), efd::SemanticVerifierPass::run(), and efd::DependencyBuilderWrapperPass::run().
stmt_end() [2/2]
efd::QModule::ConstIterator efd::QModule::stmt_end () const
ConstIterator to the end of the statement node vector.
Definition at line 230 of file QModule.cpp.
toString()
std::string efd::QModule::toString (bool pretty = false, bool printGates = false) const
Returns a std::string representation of the QModule.
Definition at line 246 of file QModule.cpp.
References efd::NDQOp::getId(), and efd::NDValue< T >::getVal().
The documentation for this class was generated from the following files:
include/enfield/Transform/QModule.h
lib/Transform/QModule.cpp