Enfield: efd::NodeCandidatesGenerator Struct Reference
efd::NodeCandidatesGenerator Struct Reference abstract
Generates a vector with the Nodes that can be chosen as the next instruction.
#include <BoundedMappingTreeQAllocator.h>
Public Types
typedef NodeCandidatesGenerator * Ref
typedef std::unique_ptr< NodeCandidatesGenerator > uRef
Public Member Functions
NodeCandidatesGenerator ()
void setQModule (QModule::Ref qmod)
Sets the QModule to be iterated.
std::vector< Node::Ref > generate ()
Returns the next collection of candidates.
bool finished ()
Returns whether we have finished processing the nodes.
void initialize ()
Initializes the generator.
virtual void signalProcessed (Node::Ref node)
Signals the generator which node has been selected.
Protected Member Functions
virtual void initializeImpl ()=0
virtual bool finishedImpl ()=0
virtual std::vector< Node::Ref > generateImpl ()=0
Protected Attributes
QModule::Ref mMod
Detailed Description
Generates a vector with the Nodes that can be chosen as the next instruction.
Definition at line 72 of file BoundedMappingTreeQAllocator.h.
Member Typedef Documentation
Ref
typedef NodeCandidatesGenerator* efd::NodeCandidatesGenerator::Ref
Definition at line 73 of file BoundedMappingTreeQAllocator.h.
uRef
typedef std::unique_ptr<NodeCandidatesGenerator> efd::NodeCandidatesGenerator::uRef
Definition at line 74 of file BoundedMappingTreeQAllocator.h.
Constructor & Destructor Documentation
NodeCandidatesGenerator()
NodeCandidatesGenerator::NodeCandidatesGenerator ()
Definition at line 30 of file BoundedMappingTreeQAllocator.cpp.
Member Function Documentation
finished()
bool NodeCandidatesGenerator::finished ()
Returns whether we have finished processing the nodes.
Definition at line 42 of file BoundedMappingTreeQAllocator.cpp.
References finishedImpl().
Referenced by generate().
finishedImpl()
virtual bool efd::NodeCandidatesGenerator::finishedImpl () protected pure virtual
Implemented in efd::CircuitCandidatesGenerator, and efd::SeqNCandidatesGenerator.
Referenced by finished().
generate()
std::vector< Node::Ref > NodeCandidatesGenerator::generate ()
Returns the next collection of candidates.
Definition at line 36 of file BoundedMappingTreeQAllocator.cpp.
References finished(), and generateImpl().
generateImpl()
virtual std::vector<Node::Ref> efd::NodeCandidatesGenerator::generateImpl () protected pure virtual
Implemented in efd::CircuitCandidatesGenerator, and efd::SeqNCandidatesGenerator.
Referenced by generate().
initialize()
void NodeCandidatesGenerator::initialize ()
Initializes the generator.
Definition at line 54 of file BoundedMappingTreeQAllocator.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), initializeImpl(), and mMod.
initializeImpl()
virtual void efd::NodeCandidatesGenerator::initializeImpl () protected pure virtual
Implemented in efd::CircuitCandidatesGenerator, and efd::SeqNCandidatesGenerator.
Referenced by initialize().
setQModule()
void NodeCandidatesGenerator::setQModule (QModule::Ref qmod)
Sets the QModule to be iterated.
Definition at line 32 of file BoundedMappingTreeQAllocator.cpp.
References mMod.
signalProcessed()
void NodeCandidatesGenerator::signalProcessed (Node::Ref node) virtual
Signals the generator which node has been selected.
Reimplemented in efd::CircuitCandidatesGenerator, and efd::SeqNCandidatesGenerator.
Definition at line 65 of file BoundedMappingTreeQAllocator.cpp.
Member Data Documentation
mMod
QModule::Ref efd::NodeCandidatesGenerator::mMod protected
Definition at line 94 of file BoundedMappingTreeQAllocator.h.
Referenced by initialize(), and setQModule().
The documentation for this struct was generated from the following files:
include/enfield/Transform/Allocators/BoundedMappingTreeQAllocator.h
lib/Transform/Allocators/BoundedMappingTreeQAllocator.cpp