Enfield: efd::SimpleDepSolver Class Reference
efd::SimpleDepSolver Class Reference
DependencySolver that allocates the logical qubits from an initial mapping.
#include <SimpleDepSolver.h>
Public Types
typedef SimpleDepSolver * Ref
typedef std::unique_ptr< SimpleDepSolver > uRef
Public Types inherited from efd::QbitAllocator
typedef QbitAllocator * Ref
typedef std::unique_ptr< QbitAllocator > uRef
typedef Solution::Mapping Mapping
typedef std::vector< std::string > BasisVector
typedef DependencyBuilder::DepsSet DepsSet
typedef DependencyBuilder::DepsSet::iterator Iterator
Public Types inherited from efd::PassT< Solution >
typedef PassT< Solution > * Ref
typedef std::shared_ptr< PassT< Solution > > sRef
typedef std::unique_ptr< PassT< Solution > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
void setMapFinder (MappingFinder::sRef finder)
Sets the mapping finder to finder.
void setSolBuilder (SolutionBuilder::sRef builder)
Sets the solution builder to builder.
Public Member Functions inherited from efd::QbitAllocator
bool run (QModule::Ref qmod) override
void setInlineAll (BasisVector basis={})
Flags the QbitAllocator to inline all gates, but those inside the basis vector, before mapping.
void setDontInline ()
Flags the QbitAllocator not to inline.
Public Member Functions inherited from efd::PassT< Solution >
PassT ()
Solution getData () const
Gets the resulting data.
Solution & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create (ArchGraph::sRef agraph)
Creates an instance of this class.
Static Public Member Functions inherited from efd::PassT< Solution >
static bool ClassOf (Pass *ref)
Protected Member Functions
SimpleDepSolver (ArchGraph::sRef agraph)
Solution solve (DepsSet &deps) override
Solves the allocation problem, returning a solution.
Protected Member Functions inherited from efd::DepSolverQAllocator
DepSolverQAllocator (ArchGraph::sRef archGraph)
virtual Solution executeAllocation (QModule::Ref qmod) override
Executes the allocation algorithm after the preprocessing.
Protected Member Functions inherited from efd::QbitAllocator
QbitAllocator (ArchGraph::sRef archGraph)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Protected Attributes
MappingFinder::sRef mMapFinder
SolutionBuilder::sRef mSolBuilder
Protected Attributes inherited from efd::QbitAllocator
bool mInlineAll
ArchGraph::sRef mArchGraph
BasisVector mBasis
QModule::Ref mMod
uint32_t mVQubits
uint32_t mPQubits
Protected Attributes inherited from efd::PassT< Solution >
Solution mData
Detailed Description
DependencySolver that allocates the logical qubits from an initial mapping.
Definition at line 10 of file SimpleDepSolver.h.
Member Typedef Documentation
Ref
typedef SimpleDepSolver* efd::SimpleDepSolver::Ref
Definition at line 12 of file SimpleDepSolver.h.
uRef
typedef std::unique_ptr<SimpleDepSolver> efd::SimpleDepSolver::uRef
Definition at line 13 of file SimpleDepSolver.h.
Constructor & Destructor Documentation
SimpleDepSolver()
efd::SimpleDepSolver::SimpleDepSolver (ArchGraph::sRef agraph) protected
Definition at line 3 of file SimpleDepSolver.cpp.
References efd::DepSolverQAllocator::DepSolverQAllocator().
Referenced by Create().
Member Function Documentation
Create()
efd::SimpleDepSolver::uRef efd::SimpleDepSolver::Create (ArchGraph::sRef agraph) static
Creates an instance of this class.
Definition at line 21 of file SimpleDepSolver.cpp.
References SimpleDepSolver().
setMapFinder()
void efd::SimpleDepSolver::setMapFinder (MappingFinder::sRef finder)
Sets the mapping finder to finder.
Definition at line 12 of file SimpleDepSolver.cpp.
References mMapFinder.
setSolBuilder()
void efd::SimpleDepSolver::setSolBuilder (SolutionBuilder::sRef builder)
Sets the solution builder to builder.
Definition at line 16 of file SimpleDepSolver.cpp.
References mSolBuilder.
solve()
efd::Solution efd::SimpleDepSolver::solve (DepsSet & deps) override protected virtual
Solves the allocation problem, returning a solution.
Implements efd::DepSolverQAllocator.
Definition at line 7 of file SimpleDepSolver.cpp.
References efd::SolutionBuilder::build(), efd::MappingFinder::find(), efd::QbitAllocator::mArchGraph, mMapFinder, and mSolBuilder.
Member Data Documentation
mMapFinder
MappingFinder::sRef efd::SimpleDepSolver::mMapFinder protected
Definition at line 16 of file SimpleDepSolver.h.
Referenced by setMapFinder(), and solve().
mSolBuilder
SolutionBuilder::sRef efd::SimpleDepSolver::mSolBuilder protected
Definition at line 17 of file SimpleDepSolver.h.
Referenced by setSolBuilder(), and solve().
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/SimpleDepSolver.h
lib/Transform/Allocators/SimpleDepSolver.cpp