Enfield: efd::WeightedSIMappingFinder Class Reference
efd::WeightedSIMappingFinder Class Reference
Finds a mapping with a weighted partial matching algorithm (subgraph isomorphism).
#include <WeightedSIMappingFinder.h>
Public Types
typedef uint32_t WeightTy
typedef WeightedSIMappingFinder * Ref
typedef std::unique_ptr< WeightedSIMappingFinder > uRef
Public Types inherited from efd::MappingFinder
typedef QbitAllocator::DepsVector DepsVector
typedef MappingFinder * Ref
typedef std::shared_ptr< MappingFinder > sRef
Public Member Functions
Mapping find (ArchGraph::Ref g, DepsVector &deps) override
Returns a mapping generated from a set of dependencies.
void setSIFinder (SIFinder::sRef finder)
Sets the subgraph isomorphism finder to finder.
Static Public Member Functions
static uRef Create ()
Creates an instance of this class.
Detailed Description
Finds a mapping with a weighted partial matching algorithm (subgraph isomorphism).
Definition at line 11 of file WeightedSIMappingFinder.h.
Member Typedef Documentation
Ref
typedef WeightedSIMappingFinder* efd::WeightedSIMappingFinder::Ref
Definition at line 15 of file WeightedSIMappingFinder.h.
uRef
typedef std::unique_ptr<WeightedSIMappingFinder> efd::WeightedSIMappingFinder::uRef
Definition at line 16 of file WeightedSIMappingFinder.h.
WeightTy
typedef uint32_t efd::WeightedSIMappingFinder::WeightTy
Definition at line 13 of file WeightedSIMappingFinder.h.
Member Function Documentation
Create()
efd::WeightedSIMappingFinder::uRef efd::WeightedSIMappingFinder::Create () static
Creates an instance of this class.
Definition at line 30 of file WeightedSIMappingFinder.cpp.
Referenced by efd::GreedyCktQAllocator::buildStdSolution().
find()
efd::Mapping efd::WeightedSIMappingFinder::find (ArchGraph::Ref g, DepsVector & deps) override virtual
Returns a mapping generated from a set of dependencies.
Implements efd::MappingFinder.
Definition at line 6 of file WeightedSIMappingFinder.cpp.
References efd::Graph::Directed, efd::Dep::mFrom, efd::Dep::mTo, efd::Graph::size(), and efd::toShared().
setSIFinder()
void efd::WeightedSIMappingFinder::setSIFinder (SIFinder::sRef finder)
Sets the subgraph isomorphism finder to finder.
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/Simple/WeightedSIMappingFinder.h
lib/Transform/Allocators/Simple/WeightedSIMappingFinder.cpp