Enfield: efd::RenameQbitVisitor Class Reference
efd::RenameQbitVisitor Class Reference
Public Member Functions
RenameQbitVisitor (RenameQbitPass::ArchMap &map)
void visit (NDQOpMeasure::Ref ref) override
void visit (NDQOpReset::Ref ref) override
void visit (NDQOpU::Ref ref) override
void visit (NDQOpCX::Ref ref) override
void visit (NDQOpBarrier::Ref ref) override
void visit (NDQOpGen::Ref ref) override
void visit (NDList::Ref ref) override
Public Member Functions inherited from efd::NodeVisitor
virtual void visit (NDQasmVersion::Ref ref)
virtual void visit (NDInclude::Ref ref)
virtual void visit (NDRegDecl::Ref ref)
virtual void visit (NDGateDecl::Ref ref)
virtual void visit (NDOpaque::Ref ref)
virtual void visit (NDBinOp::Ref ref)
virtual void visit (NDUnaryOp::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDStmtList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDIfStmt::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Additional Inherited Members
Public Types inherited from efd::NodeVisitor
typedef NodeVisitor * Ref
Detailed Description
Definition at line 8 of file RenameQbitsPass.cpp.
Constructor & Destructor Documentation
RenameQbitVisitor()
efd::RenameQbitVisitor::RenameQbitVisitor (RenameQbitPass::ArchMap & map) inline
Definition at line 17 of file RenameQbitsPass.cpp.
Member Function Documentation
visit() [1/7]
void efd::RenameQbitVisitor::visit (NDQOpMeasure::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 40 of file RenameQbitsPass.cpp.
References efd::NDQOpMeasure::getQBit(), and efd::NDQOpMeasure::setQBit().
visit() [2/7]
void efd::RenameQbitVisitor::visit (NDQOpReset::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 44 of file RenameQbitsPass.cpp.
References efd::NDQOpReset::getQArg(), and efd::NDQOpReset::setQArg().
visit() [3/7]
void efd::RenameQbitVisitor::visit (NDQOpU::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 48 of file RenameQbitsPass.cpp.
References efd::NDQOpU::getQArg(), and efd::NDQOpU::setQArg().
visit() [4/7]
void efd::RenameQbitVisitor::visit (NDQOpCX::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 52 of file RenameQbitsPass.cpp.
References efd::NDQOpCX::getLhs(), efd::NDQOpCX::getRhs(), efd::NDQOpCX::setLhs(), and efd::NDQOpCX::setRhs().
visit() [5/7]
void efd::RenameQbitVisitor::visit (NDQOpBarrier::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 57 of file RenameQbitsPass.cpp.
References efd::NDList::apply(), and efd::NDQOp::getQArgs().
visit() [6/7]
void efd::RenameQbitVisitor::visit (NDQOpGen::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 61 of file RenameQbitsPass.cpp.
References efd::NDList::apply(), and efd::NDQOp::getQArgs().
visit() [7/7]
void efd::RenameQbitVisitor::visit (NDList::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 67 of file RenameQbitsPass.cpp.
References efd::Node::getChild(), efd::NDList::getChildNumber(), and efd::Node::setChild().
The documentation for this class was generated from the following file:
lib/Transform/RenameQbitsPass.cpp