Enfield: efd::DependencyBuilder Struct Reference
efd::DependencyBuilder Struct Reference
Keep track of the dependencies of each qbit for the whole program, as well as the dependencies for every gate.
#include <DependencyBuilderPass.h>
Public Types
typedef DependencyBuilder * Ref
typedef std::vector< Dependencies > DepsSet
Public Member Functions
DependencyBuilder ()
uint32_t getUId (Node::Ref ref, NDGateDecl::Ref gate)
Gets an unsingned id for ref.
const DepsSet * getDepsSet (NDGateDecl::Ref gate=nullptr) const
Gets the DepsSet corresponding to the current quantum gate, or the global (if current gate is null).
DepsSet * getDepsSet (NDGateDecl::Ref gate=nullptr)
XbitToNumber & getXbitToNumber ()
Returns the structure that mapped the qbits.
void setXbitToNumber (XbitToNumber &xtn)
Sets the structure that will map the qbits.
const DepsSet & getDependencies (NDGateDecl::Ref ref=nullptr) const
Gets the dependencies for some gate declaration. If it is a nullptr, then it is returned the dependencies for the whole program.
DepsSet & getDependencies (NDGateDecl::Ref ref=nullptr)
const Dependencies getDeps (Node *ref) const
Gets the dependencies for a specific instruction.
Dependencies getDeps (Node *ref)
Public Attributes
XbitToNumber mXbitToNumber
std::unordered_map< NDGateDecl *, DepsSet > mLDeps
std::map< Node *, Dependencies > mIDeps
DepsSet mGDeps
Detailed Description
Keep track of the dependencies of each qbit for the whole program, as well as the dependencies for every gate.
Each gate, as well as the whole program have one 'DepsSet' variable. The idea is to store a sequence of parallel dependencies. Here, parallel dependency is a dependency that can't be broken down (unless the gate is inlined).
Definition at line 58 of file DependencyBuilderPass.h.
Member Typedef Documentation
DepsSet
typedef std::vector<Dependencies> efd::DependencyBuilder::DepsSet
Definition at line 60 of file DependencyBuilderPass.h.
Ref
typedef DependencyBuilder* efd::DependencyBuilder::Ref
Definition at line 59 of file DependencyBuilderPass.h.
Constructor & Destructor Documentation
DependencyBuilder()
efd::DependencyBuilder::DependencyBuilder ()
Definition at line 43 of file DependencyBuilderPass.cpp.
Member Function Documentation
getDependencies() [1/2]
const efd::DependencyBuilder::DepsSet & efd::DependencyBuilder::getDependencies (NDGateDecl::Ref ref = nullptr) const
Gets the dependencies for some gate declaration. If it is a nullptr, then it is returned the dependencies for the whole program.
Definition at line 79 of file DependencyBuilderPass.cpp.
References getDepsSet().
getDependencies() [2/2]
efd::DependencyBuilder::DepsSet & efd::DependencyBuilder::getDependencies (NDGateDecl::Ref ref = nullptr)
Definition at line 85 of file DependencyBuilderPass.cpp.
References getDepsSet().
Referenced by efd::GreedyCktQAllocator::executeAllocation(), efd::DepSolverQAllocator::executeAllocation(), efd::DependencyGraphBuilderPass::run(), and efd::QbitAllocator::run().
getDeps() [1/2]
const efd::Dependencies efd::DependencyBuilder::getDeps (Node * ref) const
Gets the dependencies for a specific instruction.
Definition at line 89 of file DependencyBuilderPass.cpp.
References mIDeps.
getDeps() [2/2]
efd::Dependencies efd::DependencyBuilder::getDeps (Node * ref)
Definition at line 94 of file DependencyBuilderPass.cpp.
References mIDeps.
Referenced by efd::GreedyCktQAllocator::executeAllocation(), and efd::IBMQAllocator::executeAllocation().
getDepsSet() [1/2]
const efd::DependencyBuilder::DepsSet * efd::DependencyBuilder::getDepsSet (NDGateDecl::Ref gate = nullptr) const
Gets the DepsSet corresponding to the current quantum gate, or the global (if current gate is null).
Definition at line 52 of file DependencyBuilderPass.cpp.
References mGDeps, and mLDeps.
Referenced by getDependencies(), and getDepsSet().
getDepsSet() [2/2]
efd::DependencyBuilder::DepsSet * efd::DependencyBuilder::getDepsSet (NDGateDecl::Ref gate = nullptr)
Definition at line 65 of file DependencyBuilderPass.cpp.
References getDepsSet().
Referenced by getDependencies(), and efd::DependencyBuilderVisitor::visit().
getUId()
uint32_t efd::DependencyBuilder::getUId (Node::Ref ref, NDGateDecl::Ref gate)
Gets an unsingned id for ref.
Definition at line 46 of file DependencyBuilderPass.cpp.
References efd::XbitToNumber::getQUId(), mXbitToNumber, and efd::Node::toString().
Referenced by efd::DependencyBuilderVisitor::visit().
getXbitToNumber()
efd::XbitToNumber & efd::DependencyBuilder::getXbitToNumber ()
Returns the structure that mapped the qbits.
Definition at line 70 of file DependencyBuilderPass.cpp.
References mXbitToNumber.
setXbitToNumber()
void efd::DependencyBuilder::setXbitToNumber (efd::XbitToNumber & xtn)
Sets the structure that will map the qbits.
Definition at line 74 of file DependencyBuilderPass.cpp.
References mXbitToNumber.
Referenced by efd::DependencyBuilderWrapperPass::run().
Member Data Documentation
mGDeps
DepsSet efd::DependencyBuilder::mGDeps
Definition at line 66 of file DependencyBuilderPass.h.
Referenced by getDepsSet(), and efd::DependencyBuilderWrapperPass::run().
mIDeps
std::map<Node*, Dependencies> efd::DependencyBuilder::mIDeps
Definition at line 65 of file DependencyBuilderPass.h.
Referenced by getDeps(), efd::DependencyBuilderWrapperPass::run(), and efd::DependencyBuilderVisitor::visit().
mLDeps
std::unordered_map<NDGateDecl*, DepsSet> efd::DependencyBuilder::mLDeps
Definition at line 64 of file DependencyBuilderPass.h.
Referenced by getDepsSet(), efd::DependencyBuilderWrapperPass::run(), and efd::DependencyBuilderVisitor::visit().
mXbitToNumber
XbitToNumber efd::DependencyBuilder::mXbitToNumber
Definition at line 62 of file DependencyBuilderPass.h.
Referenced by efd::IBMQAllocator::executeAllocation(), getUId(), getXbitToNumber(), efd::DependencyGraphBuilderPass::run(), efd::QbitAllocator::run(), and setXbitToNumber().
The documentation for this struct was generated from the following files:
include/enfield/Transform/DependencyBuilderPass.h
lib/Transform/DependencyBuilderPass.cpp