Enfield: efd::QModuleQualityEvalPass Class Reference
efd::QModuleQualityEvalPass Class Reference
Evaluates a QModule.
#include <QModuleQualityEvalPass.h>
Public Types
typedef QModuleQualityEvalPass * Ref
typedef std::unique_ptr< QModuleQualityEvalPass > uRef
typedef std::shared_ptr< QModuleQualityEvalPass > sRef
typedef std::map< std::string, uint32_t > MapGateUInt
Public Types inherited from efd::PassT< QModuleQuality >
typedef PassT< QModuleQuality > * Ref
typedef std::shared_ptr< PassT< QModuleQuality > > sRef
typedef std::unique_ptr< PassT< QModuleQuality > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
QModuleQualityEvalPass (MapGateUInt gatesW)
bool run (QModule::Ref qmod) override
Public Member Functions inherited from efd::PassT< QModuleQuality >
PassT ()
QModuleQuality getData () const
Gets the resulting data.
QModuleQuality & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create (MapGateUInt gatesW)
Returns a new instance of this class.
Static Public Member Functions inherited from efd::PassT< QModuleQuality >
static bool ClassOf (Pass *ref)
Static Public Attributes
static uint8_t ID = 0
Additional Inherited Members
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Protected Attributes inherited from efd::PassT< QModuleQuality >
QModuleQuality mData
Detailed Description
Evaluates a QModule.
Computes the depth of the circuit, the number of gates, and a weighted sum for each gate.
Definition at line 21 of file QModuleQualityEvalPass.h.
Member Typedef Documentation
MapGateUInt
typedef std::map<std::string, uint32_t> efd::QModuleQualityEvalPass::MapGateUInt
Definition at line 26 of file QModuleQualityEvalPass.h.
Ref
typedef QModuleQualityEvalPass* efd::QModuleQualityEvalPass::Ref
Definition at line 23 of file QModuleQualityEvalPass.h.
sRef
typedef std::shared_ptr<QModuleQualityEvalPass> efd::QModuleQualityEvalPass::sRef
Definition at line 25 of file QModuleQualityEvalPass.h.
uRef
typedef std::unique_ptr<QModuleQualityEvalPass> efd::QModuleQualityEvalPass::uRef
Definition at line 24 of file QModuleQualityEvalPass.h.
Constructor & Destructor Documentation
QModuleQualityEvalPass()
QModuleQualityEvalPass::QModuleQualityEvalPass (MapGateUInt gatesW)
Definition at line 11 of file QModuleQualityEvalPass.cpp.
Referenced by Create().
Member Function Documentation
Create()
QModuleQualityEvalPass::uRef QModuleQualityEvalPass::Create (MapGateUInt gatesW) static
Returns a new instance of this class.
Definition at line 46 of file QModuleQualityEvalPass.cpp.
References QModuleQualityEvalPass().
run()
bool QModuleQualityEvalPass::run (QModule::Ref qmod) override
Definition at line 14 of file QModuleQualityEvalPass.cpp.
References efd::PassT< QModuleQuality >::getData(), efd::QModule::getNumberOfStmts(), efd::PassT< QModuleQuality >::mData, efd::QModuleQuality::mDepth, efd::QModuleQuality::mGates, efd::QModuleQuality::mWeightedCost, efd::QModule::stmt_begin(), efd::QModule::stmt_end(), and WAR.
Member Data Documentation
ID
uint8_t QModuleQualityEvalPass::ID = 0 static
Definition at line 32 of file QModuleQualityEvalPass.h.
The documentation for this class was generated from the following files:
include/enfield/Transform/QModuleQualityEvalPass.h
lib/Transform/QModuleQualityEvalPass.cpp