Enfield: efd::PassCache Class Reference
efd::PassCache Class Reference
Static class that caches passes that were run by this compiler.
#include <PassCache.h>
Public Types
typedef std::unordered_map< uint8_t *, Pass::sRef > PassMap
typedef std::unordered_map< QModule::Ref, PassMap > QModPassesMap
Public Member Functions
PassCache ()=delete
Static Public Member Functions
static void Clear (QModule::Ref qmod=nullptr)
Clears the cache for a certain qmod, or simply clears all cache.
template<typename T >
static bool Has (QModule::Ref qmod)
Returns true if this pass was already run for this module.
template<typename T >
static void Run (QModule::Ref qmod)
Runs the pass T in qmod.
template<typename T >
static void Run (QModule::Ref qmod, T *pass)
Wrapper that runs a created pass.
template<typename T >
static T * Get (QModule::Ref qmod)
Gets a shared pointer to the pass T run in qmod. If it does not exist, it tries to run.
Detailed Description
Static class that caches passes that were run by this compiler.
Definition at line 10 of file PassCache.h.
Member Typedef Documentation
PassMap
typedef std::unordered_map<uint8_t*, Pass::sRef> efd::PassCache::PassMap
Definition at line 12 of file PassCache.h.
QModPassesMap
typedef std::unordered_map<QModule::Ref, PassMap> efd::PassCache::QModPassesMap
Definition at line 13 of file PassCache.h.
Constructor & Destructor Documentation
PassCache()
efd::PassCache::PassCache () delete
Member Function Documentation
Clear()
static void efd::PassCache::Clear (QModule::Ref qmod = nullptr) inline static
Clears the cache for a certain qmod, or simply clears all cache.
Definition at line 22 of file PassCache.h.
Referenced by efd::QModule::~QModule().
Get()
template<typename T > static T* efd::PassCache::Get (QModule::Ref qmod) inline static
Gets a shared pointer to the pass T run in qmod. If it does not exist, it tries to run.
Definition at line 71 of file PassCache.h.
Referenced by efd::Compile(), efd::GreedyCktQAllocator::executeAllocation(), efd::DepSolverQAllocator::executeAllocation(), efd::IBMQAllocator::executeAllocation(), efd::PrintDependencyGraph(), efd::DependencyGraphBuilderPass::run(), efd::LayersBuilderPass::run(), efd::CircuitGraphBuilderPass::run(), efd::LayerBasedOrderingWrapperPass::run(), efd::SemanticVerifierPass::run(), efd::SolutionImplPass::run(), efd::QbitAllocator::run(), and efd::DependencyBuilderWrapperPass::run().
Has()
template<typename T > static bool efd::PassCache::Has (QModule::Ref qmod) inline static
Returns true if this pass was already run for this module.
Definition at line 32 of file PassCache.h.
Run() [1/2]
template<typename T > static void efd::PassCache::Run (QModule::Ref qmod) inline static
Runs the pass T in qmod.
This will cache the pass run and return it if called without any modifications to the module.
Definition at line 47 of file PassCache.h.
References efd::Pass::run().
Referenced by efd::Compile(), and efd::SemanticVerifierPass::run().
Run() [2/2]
template<typename T > static void efd::PassCache::Run (QModule::Ref qmod, T * pass) inline static
Wrapper that runs a created pass.
Should be used in order to maintain consistent the data in the cache.
Definition at line 63 of file PassCache.h.
Referenced by efd::Compile(), main(), efd::SemanticVerifierPass::run(), and efd::QbitAllocator::run().
The documentation for this class was generated from the following files:
include/enfield/Transform/PassCache.h
lib/Transform/PassCache.cpp