Enfield: efd Namespace Reference
efd Namespace Reference
Namespaces
bmt
Classes
class ApproxTSFinder
4-Approximative polynomial algorithm.
class ArchGraph
This is the base class for the architectures that this project will be supporting.
class ArchIBMQX2
class ArchIBMQX3
class ArchVerifierPass
Verifies if the CNOT relations between every qubit respects the architecture constraints.
class ArchVerifierVisitor
class ArgsParser
struct ASTWrapper
class BestNMSSelector
Selects the line that yielded the best cost.
class BFSPathFinder
Finds swaps for one restriction only.
class BitOptions
Implements bit options for size last.
class BoundedMappingTreeQAllocator
Subgraph Isomorphism based Qubit Allocator.
struct CandidateSelector
Interface for selecting candidates (if they are greater than a max) in phase 1.
class CircuitCandidatesGenerator
Generates a vector with the nodes that it can reach using the CircuitGraph.
class CircuitGraph
The Circuit representation of the QModule.
class CircuitGraphBuilderPass
Builds the circuit graph corresponding to the QModule given.
class CNOTLBOWrapperPass
Layer-based Ordering with CNOT priority.
struct CompilationSettings
Required information in order to compile a QModule.
struct Dep
Structure for abstracting dependencies.
struct Dependencies
Represents a sequence of dependencies (should be treated as parallel dependencies) for each node.
struct DependencyBuilder
Keep track of the dependencies of each qbit for the whole program, as well as the dependencies for every gate.
class DependencyBuilderVisitor
class DependencyBuilderWrapperPass
WrapperPass that yields a DependencyBuilder structure.
class DependencyGraphBuilderPass
Constructs the dependency graph for a QModule.
class DijkstraPathFinder
Dijkstra algorithm for finding a swap sequence in a weighted graph.
class DynprogQAllocator
Implementation of DepSolverQAllocator that uses dynamic programming to obtain an optimal solution.
class EnumString
Enum wrapper class.
class ExpTSFinder
Brute force solution to the Token Swap Finder.
class FirstCandidateSelector
Gets the first maxCandidates from candidates.
class FlattenPass
Flattens the given QModule.
class FlattenVisitor
class GeoDistanceSwapCEstimator
The estimation is the sum of all distances.
class GeoNearestLQPProcessor
Forces toM to map all qubits mapped in fromM.
class Graph
Graph representation.
class GreedyCktQAllocator
class IBMQAllocator
Port of IBM's allocator.
class IdentityMappingFinder
Finds a mapping where the logical qubit 0 is mapped to the physical qubit 0, etc.
struct IndexOrder
Helper class to sort an index vector based on a value vector.
class InlineAllPass
class InlineAllVisitor
class IntrinsicGateCostPass
struct LayerBasedOrdering
class LayerBasedOrderingWrapperPass
Interface for ordering the program by a specific layer-based ordering.
class LayersBuilderPass
Create the layers of the 'QModule'.
struct LiveQubitsPreProcessor
Interface for preparing the Mappings for fixing the Live Qubits problem.
class MappingFinder
Interface for finding a mapping from some set of dependencies.
struct MapSeqSelector
Selects a number of line numbers from the memoized matrix.
class NDBinOp
Binary operation node.
class NDDecl
Node for declaration of registers (concrete and quantum).
class NDGateDecl
Node for declaration of quantum gates.
class NDGateSign
Node for declaration of opaque quantum gates.
class NDGOpList
Node for list of qubit operation sequences inside gate declarations.
class NDIdRef
Node for id references (register specific positions).
class NDIfStmt
Node for conditional statement.
class NDInclude
Node used to parse another file.
class NDList
Base class for list of nodes.
class NDQasmVersion
Node that holds the current Qasm version and the rest of the program.
class NDQOp
Generic node for quantum operations. This is also the base node for the other quantum gates.
class NDQOpBarrier
NDQOp specialized for barrier operation.
class NDQOpCX
NDQOp specialized for barrier operation.
class NDQOpGen
NDQOp specialized for generic gates.
struct NDQOpLongCX
Special node for long cnot calls.
class NDQOpMeasure
NDQOp specialized for measure operation.
class NDQOpReset
NDQOp specialized for reset operation.
struct NDQOpRevCX
Special node for reversal cnot calls.
struct NDQOpSwap
Special node for swap calls.
class NDQOpU
NDQOp specialized for barrier operation.
class NDRegDecl
class NDStmtList
Node for list of qubit operation sequences.
class NDUnaryOp
Unary operation node.
class NDValue
Node for literal types.
class Node
Base class for AST nodes.
struct NodeCandidatesGenerator
Generates a vector with the Nodes that can be chosen as the next instruction.
class NodeRenameVisitor
class NodeVisitor
Interface class to be used as a visitor.
struct Operation
Struct used to describe the operation chosen for each solving each dependency.
class Opt
Class used to declare the command line options available.
class OptBase
Base class for implementing command line options.
struct ParseOptTrait
Parses the arguments in args to opt.
struct ParseOptTrait< bool >
struct ParseOptTrait< double >
struct ParseOptTrait< EnumString< T, first, last > >
struct ParseOptTrait< float >
struct ParseOptTrait< int >
struct ParseOptTrait< long long >
struct ParseOptTrait< MapGateUInt >
struct ParseOptTrait< std::string >
struct ParseOptTrait< std::vector< std::string > >
struct ParseOptTrait< unsigned >
struct ParseOptTrait< unsigned long long >
class Pass
Base class for implementation of QModule passes. This information will be used when the QModule's function is called.
class PassCache
Static class that caches passes that were run by this compiler.
class PassT
Should serve as base class for classes that produces some data of type T.
class PassT< void >
class PathFinder
Interface for finding the path between two vertices.
class PathGuidedSolBuilder
Solves the dependencies by looking at the path in the graph.
struct PossibleValuesListTrait
struct PossibleValuesListTrait< efd::EnumString< T, first, last > >
class QArgsReplaceVisitor
class QbitAllocator
Base abstract class that allocates the qbits used in the program to the qbits that are in the physical architecture.
class QbitterSolBuilder
Solves the dependencies using the 'long-cnot' gates.
class QModule
Qasm module representation.
class QModulefyVisitor
struct QModuleQuality
Holds the evaluation metrics for an allocation.
class QModuleQualityEvalPass
Evaluates a QModule.
class RandomMappingFinder
Randomizes the mapping.
class Registry
Base registry class for sets.
class RenameQbitPass
Renames all the qbits according to the map from the constructor.
class RenameQbitVisitor
class ReverseEdgesPass
Pass that reverses the edges accordingly with the architecture Graph.
class ReverseEdgesVisitor
class SemanticVerifierPass
Verifies the CNOT relations between every qubit.
class SemanticVerifierVisitor
class SeqNCandidatesGenerator
Sequential generator.
class SIFinder
Interface for implementing different algorithms for finding matchings (subgraph isomorphism).
class SimpleQAllocator
DependencySolver that allocates the logical qubits from an initial mapping.
class SolutionBuilder
Interface for building the solution from an initial mapping.
class Stat
Stats of a given type.
class StatBase
Base class for stats.
class StatsPool
struct StdSolution
The solution for the allocation problem.
class StdSolutionImplPass
class StdSolutionQAllocator
An abstract allocator that builds the solution based on a StdSolution.
struct Swap
Struct used for representing a swap between two qubits;.
struct SwapCostEstimator
Interface for estimating the number of swaps in phase 2.
class Timer
Tracks the elapsed time. One should use the methods start and stop in order to track the time of some event.
class TokenSwapFinder
Interface for solving the Token Swap Problem.
class UsedBitsVisitor
class WeightedGraph
class WeightedRouletteCandidateSelector
Selects the candidates randomly, based on their cost.
class WeightedSIFinder
Extends the SIFinder class for weighted graphs.
class WeightedSIMappingFinder
Finds a mapping with a weighted partial matching algorithm (subgraph isomorphism).
struct WrapperVal
Wrapper for primitive values.
class Xbit
Represents the id of one Quantum or Classical bit.
struct XbitToNumber
Maps every quantum and classic bit (not register) to a number inside a vector.
class XbitToNumberVisitor
class XbitToNumberWrapperPass
WrapperPass that yields a XbitToNumber structure.
Typedefs
typedef std::shared_ptr< ArchRegistry > ArchRegistryPtr
typedef std::shared_ptr< efd::AllocatorRegistry > AllocatorRegistryPtr
typedef NDGateSign NDOpaque
typedef NDValue< IntVal > NDInt
typedef NDValue< RealVal > NDReal
typedef NDValue< std::string > NDId
typedef NDValue< std::string > NDString
typedef EnumString< Architecture, Architecture::A_ibmqx2, Architecture::A_ibmqx3 > EnumArchitecture
typedef Registry< ArchGraph::uRef, int, EnumArchitecture > ArchRegistry
typedef std::vector< uint32_t > Mapping
Defines the type used for mapping the qubits.
typedef std::vector< uint32_t > InverseMap
typedef std::vector< Swap > SwapSeq
typedef WrapperVal< long long > IntVal
typedef WrapperVal< double > RealVal
typedef EnumString< Allocator, Allocator::first, Allocator::last > EnumAllocator
typedef Registry< QbitAllocator::uRef, ArchGraph::sRef, EnumAllocator > AllocatorRegistry
typedef WeightedGraph< uint32_t > DependencyGraph
typedef std::vector< uint32_t > Ordering
typedef std::vector< Node::Ref > Layer
typedef std::vector< Layer > Layers
Enumerations
enum Architecture { Architecture::EFD_FIRSTLAST, Architecture::EFD_ARCH, Architecture::A_ibmqx2, Architecture::A_ibmqx3 }
enum ExitCode { ExitCode::EXIT_multi_deps = 11, ExitCode::EXIT_unknown_resource, ExitCode::EXIT_out_of_bounds, ExitCode::EXIT_unreachable }
Instead of issueing an 'assert(false)', we should use this enum in order to exit with errors.
enum Allocator {
Allocator::first, Allocator::EFD_ALLOCATOR, Allocator::EFD_ALLOCATOR_SIMPLE, Allocator::EFD_ALLOCATOR_BMT,
Allocator::Q_dynprog, Allocator::Q_grdy, Allocator::Q_ibm, Allocator::Q_bmt,
Allocator::Q_ibmt, Allocator::Q_wpm, Allocator::Q_random, Allocator::Q_qubiter,
Allocator::Q_wqubiter, Allocator::last
}
enum SolutionBuilderOptions { SolutionBuilderOptions::ImproveInitial = 0, SolutionBuilderOptions::KeepStats }
Options for solution builders.
Functions
ArchRegistry::RetTy CreateArchIBMQX2 (int pad)
ArchRegistry::RetTy CreateArchIBMQX3 (int pad)
Node::uRef ParseFile (std::string filename, std::string path="./", bool forceStdLib=true)
Parse filename at path.
Node::uRef ParseString (std::string program, bool forceStdLib=true)
Parse the string program.
void InitializeAllArchitectures ()
Registers all available architectures in the register.
bool HasArchitecture (EnumArchitecture key)
Returns true if there is an architecture mapped by key;.
void RegisterArchitecture (EnumArchitecture key, ArchRegistry::CtorTy ctor)
Register an architecture, mapping key to ctor.
ArchRegistry::RetTy CreateArchitecture (EnumArchitecture key)
Creates an architecture referenced by name.
void ParseArguments (const int argc, const char **argv)
Parses the command line arguments (this function should be used in the main function).
void ParseArguments (int argc, char **argv)
std::ostream & ErrorLog (std::string file="", uint32_t line=0)
Returns a stream object for logging errors.
std::ostream & WarningLog (std::string file="", uint32_t line=0)
Returns a stream object for logging warnings.
std::ostream & InfoLog (std::string file="", uint32_t line=0)
Returns a stream object for logging information.
void ExitWith (ExitCode e)
template<typename TargetTy , typename SrcTy >
bool instanceOf (const SrcTy *src)
Returns true if the pointer src is of class TargetTy.
template<typename TargetTy , typename SrcTy >
TargetTy * dynCast (SrcTy *src)
Returns src cast to TargetTy, iff it is of class TargetTy, otherwise it will return nullptr.
void PrintStats (std::ostream &out=std::cout)
Usually called in the end of the program, i.e. when all statistical data have already been collected.
template<typename T , typename U >
std::unique_ptr< T > uniqueCastBackward (std::unique_ptr< U > from)
Uses the RTTI framework to cast backwardly an unique_ptr.
template<typename T , typename U >
std::unique_ptr< T > uniqueCastForward (std::unique_ptr< U > from)
Uses the RTTI framework to cast forwardly an unique_ptr.
template<typename T >
std::shared_ptr< T > toShared (std::unique_ptr< T > from)
Wrapper function that "transforms" a std::unique_ptr into a std::shared_ptr.
void InitializeAllQbitAllocators ()
bool HasAllocator (EnumAllocator key)
Returns true if there is an allocator mapped by key;.
void RegisterQbitAllocator (EnumAllocator key, AllocatorRegistry::CtorTy ctor)
Registers an allocator, mapping name to ctor.
AllocatorRegistry::RetTy CreateQbitAllocator (EnumAllocator key, AllocatorRegistry::ArgTy arg)
Creates an allocator referenced by name with arguments arg.
AllocatorRegistry::RetTy CreateDynprogQAllocator (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateGreedyCktQAllocator (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateIBMQAllocator (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateBMTSeqNCandidatesGeneratorFirstCandidateSelectorFirstCandidateSelectorGeoDistanceSwapCEstimatorGeoNearestLQPProcessorBestNMSSelectorApproxTSFinder (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateBMTCircuitCandidatesGeneratorWeightedRouletteCandidateSelectorWeightedRouletteCandidateSelectorGeoDistanceSwapCEstimatorGeoNearestLQPProcessorBestNMSSelectorApproxTSFinder (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateWeightedSIMappingFinderWithPathGuidedSolBuilder (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateRandomMappingFinderWithPathGuidedSolBuilder (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateIdentityMappingFinderWithQbitterSolBuilder (AllocatorRegistry::ArgTy arg)
AllocatorRegistry::RetTy CreateWeightedSIMappingFinderWithQbitterSolBuilder (AllocatorRegistry::ArgTy arg)
InverseMap InvertMapping (uint32_t archQ, Mapping mapping, bool fill=true)
Generates an assignment mapping (maps the architecture's qubits to the logical ones) of size archQ.
void Fill (uint32_t archQ, Mapping &mapping)
Fills the unmapped qubits with the ones missing.
void Fill (Mapping &mapping, InverseMap &inv)
Mapping IdentityMapping (uint32_t progQ)
Returns an identity mapping.
std::string MappingToString (Mapping m)
Prints the mapping m to a string and returns it.
QModule::uRef Compile (QModule::uRef qmod, CompilationSettings settings)
Compile qmod, and return the compiled version.
QModule::uRef ParseFile (std::string filepath)
Parse file in the path filepath.
void PrintToStream (QModule::Ref qmod, std::ostream &o=std::cout, bool pretty=true)
Print qmod to an standard output stream o.
void PrintDependencyGraph (QModule::Ref qmod, std::ostream &o=std::cout)
Print the dependency graph of the qmod in o.
void InlineGate (QModule::Ref qmod, NDQOp::Ref qop)
If found, inlines the gate that qop calls.
void ProcessAST (QModule::Ref qmod, Node::Ref root)
Processes the root node, and transform the entire AST into a QModule.
std::vector< NDGateSign::uRef > GetIntrinsicGates ()
Returns a vector with the intrinsic gates implementation.
NDQOp::uRef CreateISwap (Node::uRef lhs, Node::uRef rhs)
Creates a call to the intrinsic swap function.
NDQOp::uRef CreateILongCX (Node::uRef lhs, Node::uRef middle, Node::uRef rhs)
Creates a call to the intrinsic long cnot function.
NDQOp::uRef CreateIRevCX (Node::uRef lhs, Node::uRef rhs)
Creates a call to the intrinsic reversal cnot function.
bool IsCNOTGateCall (Node::Ref ref)
Returns whether ref is a CNOT gate.
bool IsIntrinsicGateCall (Node::Ref ref)
Returns whether ref is (or should be) an intrinsic gate.
NDQOpGen::IntrinsicKind GetIntrinsicKind (Node::Ref ref)
Gets the NDQOpGen::IntrinsicKind, given a Node ref.
NDQOp::uRef CreateIntrinsicGate (NDQOpGen::IntrinsicKind kind, std::vector< Node::uRef > qargs)
Creates an intrinsic gate of kind kind and arguments args.
Variables
const std::string StdLibCX = "cx"
Typedef Documentation
AllocatorRegistry
typedef Registry<QbitAllocator::uRef, ArchGraph::sRef, EnumAllocator> efd::AllocatorRegistry
Definition at line 29 of file Allocators.h.
AllocatorRegistryPtr
typedef std::shared_ptr<efd::AllocatorRegistry> efd::AllocatorRegistryPtr
Definition at line 22 of file Allocators.cpp.
ArchRegistry
typedef Registry<ArchGraph::uRef, int, EnumArchitecture> efd::ArchRegistry
Definition at line 28 of file Architectures.h.
ArchRegistryPtr
typedef std::shared_ptr<ArchRegistry> efd::ArchRegistryPtr
Definition at line 6 of file Architectures.cpp.
DependencyGraph
typedef WeightedGraph<uint32_t> efd::DependencyGraph
Definition at line 9 of file DependencyGraphBuilderPass.h.
EnumAllocator
typedef EnumString<Allocator, Allocator::first, Allocator::last> efd::EnumAllocator
Definition at line 26 of file Allocators.h.
EnumArchitecture
typedef EnumString<Architecture, Architecture::A_ibmqx2 , Architecture::A_ibmqx3 > efd::EnumArchitecture
Definition at line 2 of file Architectures.h.
IntVal
typedef WrapperVal<long long> efd::IntVal
Definition at line 30 of file WrapperVal.h.
InverseMap
typedef std::vector<uint32_t> efd::InverseMap
Definition at line 12 of file Defs.h.
Layer
typedef std::vector<Node::Ref> efd::Layer
Definition at line 11 of file LayersBuilderPass.h.
Layers
typedef std::vector<Layer> efd::Layers
Definition at line 13 of file LayersBuilderPass.h.
Mapping
typedef std::vector<uint32_t> efd::Mapping
Defines the type used for mapping the qubits.
Definition at line 11 of file Defs.h.
NDId
typedef NDValue<std::string> efd::NDId
Definition at line 214 of file Nodes.h.
NDInt
typedef NDValue<IntVal> efd::NDInt
Definition at line 212 of file Nodes.h.
NDOpaque
typedef NDGateSign efd::NDOpaque
Definition at line 34 of file Nodes.h.
NDReal
typedef NDValue<RealVal> efd::NDReal
Definition at line 213 of file Nodes.h.
NDString
typedef NDValue<std::string> efd::NDString
Definition at line 215 of file Nodes.h.
Ordering
typedef std::vector<uint32_t> efd::Ordering
Definition at line 10 of file LayerBasedOrderingWrapperPass.h.
RealVal
typedef WrapperVal<double> efd::RealVal
Definition at line 31 of file WrapperVal.h.
SwapSeq
typedef std::vector<Swap> efd::SwapSeq
Definition at line 23 of file Defs.h.
Enumeration Type Documentation
Allocator
enum efd::Allocator strong
Enumerator
first
EFD_ALLOCATOR
EFD_ALLOCATOR_SIMPLE
EFD_ALLOCATOR_BMT
Q_dynprog
Q_grdy
Q_ibm
Q_bmt
Q_ibmt
Q_wpm
Q_random
Q_qubiter
Q_wqubiter
last
Definition at line 10 of file Allocators.h.
Architecture
enum efd::Architecture strong
Enumerator
EFD_FIRSTLAST
EFD_ARCH
A_ibmqx2
A_ibmqx3
Definition at line 9 of file Architectures.h.
ExitCode
enum efd::ExitCode strong
Instead of issueing an 'assert(false)', we should use this enum in order to exit with errors.
Enumerator
EXIT_multi_deps
EXIT_unknown_resource
EXIT_out_of_bounds
EXIT_unreachable
Definition at line 34 of file Defs.h.
SolutionBuilderOptions
enum efd::SolutionBuilderOptions strong
Options for solution builders.
Enumerator
ImproveInitial
KeepStats
Definition at line 21 of file SimpleQAllocator.h.
Function Documentation
Compile()
QModule::uRef efd::Compile (QModule::uRef qmod, CompilationSettings settings)
Compile qmod, and return the compiled version.
Transform qmod according to settings. It shall specify the architecture, the allocator to use, the basis vector and whether to reorder the program or not.
Definition at line 24 of file Driver.cpp.
References efd::CompilationSettings::allocator, efd::CompilationSettings::archGraph, efd::CompilationSettings::basis, efd::ReverseEdgesPass::Create(), efd::ArchVerifierPass::Create(), efd::SemanticVerifierPass::Create(), CreateQbitAllocator(), ERR, EXIT_unreachable, ExitWith(), efd::CompilationSettings::force, efd::CompilationSettings::reorder, efd::PassCache::Run(), efd::CompilationSettings::verify, and WAR.
CreateArchIBMQX2()
ArchRegistry::RetTy efd::CreateArchIBMQX2 (int pad)
Definition at line 3 of file Architectures.cpp.
CreateArchIBMQX3()
ArchRegistry::RetTy efd::CreateArchIBMQX3 (int pad)
Definition at line 4 of file Architectures.cpp.
CreateArchitecture()
efd::ArchRegistry::RetTy efd::CreateArchitecture (EnumArchitecture key)
Creates an architecture referenced by name.
Definition at line 91 of file Architectures.cpp.
CreateBMTCircuitCandidatesGeneratorWeightedRouletteCandidateSelectorWeightedRouletteCandidateSelectorGeoDistanceSwapCEstimatorGeoNearestLQPProcessorBestNMSSelectorApproxTSFinder()
AllocatorRegistry::RetTy efd::CreateBMTCircuitCandidatesGeneratorWeightedRouletteCandidateSelectorWeightedRouletteCandidateSelectorGeoDistanceSwapCEstimatorGeoNearestLQPProcessorBestNMSSelectorApproxTSFinder (AllocatorRegistry::ArgTy arg)
CreateBMTSeqNCandidatesGeneratorFirstCandidateSelectorFirstCandidateSelectorGeoDistanceSwapCEstimatorGeoNearestLQPProcessorBestNMSSelectorApproxTSFinder()
AllocatorRegistry::RetTy efd::CreateBMTSeqNCandidatesGeneratorFirstCandidateSelectorFirstCandidateSelectorGeoDistanceSwapCEstimatorGeoNearestLQPProcessorBestNMSSelectorApproxTSFinder (AllocatorRegistry::ArgTy arg)
CreateDynprogQAllocator()
AllocatorRegistry::RetTy efd::CreateDynprogQAllocator (AllocatorRegistry::ArgTy arg)
CreateGreedyCktQAllocator()
AllocatorRegistry::RetTy efd::CreateGreedyCktQAllocator (AllocatorRegistry::ArgTy arg)
CreateIBMQAllocator()
AllocatorRegistry::RetTy efd::CreateIBMQAllocator (AllocatorRegistry::ArgTy arg)
CreateIdentityMappingFinderWithQbitterSolBuilder()
AllocatorRegistry::RetTy efd::CreateIdentityMappingFinderWithQbitterSolBuilder (AllocatorRegistry::ArgTy arg)
CreateILongCX()
NDQOp::uRef efd::CreateILongCX (Node::uRef lhs, Node::uRef middle, Node::uRef rhs)
Creates a call to the intrinsic long cnot function.
Definition at line 187 of file Utils.cpp.
Referenced by CreateIntrinsicGate().
CreateIntrinsicGate()
NDQOp::uRef efd::CreateIntrinsicGate (NDQOpGen::IntrinsicKind kind, std::vector< Node::uRef > qargs)
Creates an intrinsic gate of kind kind and arguments args.
Definition at line 146 of file Utils.cpp.
References CreateILongCX(), CreateIRevCX(), CreateISwap(), ERR, EXIT_unknown_resource, ExitWith(), efd::NDQOpGen::K_INTRINSIC_LCX, efd::NDQOpGen::K_INTRINSIC_REV_CX, and efd::NDQOpGen::K_INTRINSIC_SWAP.
CreateIRevCX()
NDQOp::uRef efd::CreateIRevCX (Node::uRef lhs, Node::uRef rhs)
Creates a call to the intrinsic reversal cnot function.
Definition at line 192 of file Utils.cpp.
Referenced by CreateIntrinsicGate().
CreateISwap()
NDQOp::uRef efd::CreateISwap (Node::uRef lhs, Node::uRef rhs)
Creates a call to the intrinsic swap function.
Definition at line 181 of file Utils.cpp.
Referenced by CreateIntrinsicGate().
CreateQbitAllocator()
efd::AllocatorRegistry::RetTy efd::CreateQbitAllocator (EnumAllocator key, AllocatorRegistry::ArgTy arg)
Creates an allocator referenced by name with arguments arg.
Definition at line 73 of file Allocators.cpp.
Referenced by Compile().
CreateRandomMappingFinderWithPathGuidedSolBuilder()
AllocatorRegistry::RetTy efd::CreateRandomMappingFinderWithPathGuidedSolBuilder (AllocatorRegistry::ArgTy arg)
CreateWeightedSIMappingFinderWithPathGuidedSolBuilder()
AllocatorRegistry::RetTy efd::CreateWeightedSIMappingFinderWithPathGuidedSolBuilder (AllocatorRegistry::ArgTy arg)
CreateWeightedSIMappingFinderWithQbitterSolBuilder()
AllocatorRegistry::RetTy efd::CreateWeightedSIMappingFinderWithQbitterSolBuilder (AllocatorRegistry::ArgTy arg)
dynCast()
template<typename TargetTy , typename SrcTy > TargetTy* efd::dynCast (SrcTy * src)
Returns src cast to TargetTy, iff it is of class TargetTy, otherwise it will return nullptr.
Definition at line 15 of file RTTI.h.
Referenced by efd::NDValue< T >::equalsImpl().
ErrorLog()
std::ostream & efd::ErrorLog (std::string file = "", uint32_t line = 0)
Returns a stream object for logging errors.
Definition at line 27 of file Defs.cpp.
ExitWith()
void efd::ExitWith (ExitCode e)
Definition at line 45 of file Defs.cpp.
Referenced by efd::StatsPool::addStat(), efd::QbitterSolBuilder::build(), efd::GreedyCktQAllocator::buildStdSolution(), efd::DynprogQAllocator::buildStdSolution(), efd::IBMQAllocator::buildStdSolution(), efd::TokenSwapFinder::checkGraphSet(), efd::SwapCostEstimator::checkGraphSet(), efd::CircuitGraph::checkInitialized(), Compile(), CreateIntrinsicGate(), efd::Registry< RTy, ATy, KTy, CTy >::createObj(), efd::EnumString< Allocator, Allocator::first, Allocator::last >::EnumString(), efd::DijkstraPathFinder< T >::find(), efd::WeightedSIFinder< T >::find(), efd::QModule::findStatement(), efd::XbitToNumber::getCStrId(), efd::XbitToNumber::getCUId(), efd::DependencyBuilder::getDeps(), efd::DependencyBuilder::getDepsVector(), efd::WeightedSIFinder< T >::getFirstFree(), GetIntrinsicKind(), efd::NDQOpGen::getIntrinsicKind(), efd::Timer::getMicroseconds(), efd::Timer::getMilliseconds(), efd::Timer::getNanoseconds(), efd::ArchGraph::getNode(), efd::LayerBasedOrderingWrapperPass::getNodeId(), efd::NDRegDecl::getOperation(), efd::NDBinOp::getOperation(), efd::NDUnaryOp::getOperation(), efd::XbitToNumber::getQbitMap(), efd::QModule::getQGate(), efd::XbitToNumber::getQStrId(), efd::QModule::getQVar(), efd::Xbit::getRealId(), efd::XbitToNumber::getRegUIds(), efd::Timer::getSeconds(), efd::ArchGraph::getSId(), efd::QModule::getStatement(), efd::EnumString< Allocator, Allocator::first, Allocator::last >::getStringValue(), efd::ArchGraph::getUId(), efd::WeightedGraph< T >::getW(), efd::NodeCandidatesGenerator::initialize(), efd::QModule::inlineCall(), InlineGate(), efd::QModule::insertGate(), efd::NDList::removeChild(), efd::QModule::replaceStatement(), efd::WeightedGraph< T >::setW(), efd::SeqNCandidatesGenerator::signalProcessed(), uniqueCastBackward(), uniqueCastForward(), efd::ReverseEdgesVisitor::visit(), efd::DependencyBuilderVisitor::visit(), and efd::Xbit::Xbit().
Fill() [1/2]
void efd::Fill (uint32_t archQ, Mapping & mapping)
Fills the unmapped qubits with the ones missing.
Definition at line 62 of file QbitAllocator.cpp.
References InvertMapping().
Fill() [2/2]
void efd::Fill (Mapping & mapping, InverseMap & inv)
Definition at line 44 of file QbitAllocator.cpp.
GetIntrinsicGates()
std::vector< NDGateSign::uRef > efd::GetIntrinsicGates ()
Returns a vector with the intrinsic gates implementation.
Definition at line 45 of file Utils.cpp.
Referenced by efd::QModule::GetFromAST().
GetIntrinsicKind()
NDQOpGen::IntrinsicKind efd::GetIntrinsicKind (Node::Ref ref)
Gets the NDQOpGen::IntrinsicKind, given a Node ref.
This function should be only called if ref is really an intrinsic function. Otherwise, it will crash.
Definition at line 128 of file Utils.cpp.
References ERR, EXIT_unknown_resource, ExitWith(), efd::Node::getOperation(), efd::NDQOpSwap::IdStr, efd::NDQOpLongCX::IdStr, efd::NDQOpRevCX::IdStr, IsIntrinsicGateCall(), efd::NDQOpGen::K_INTRINSIC_LCX, efd::NDQOpGen::K_INTRINSIC_REV_CX, efd::NDQOpGen::K_INTRINSIC_SWAP, and efd::Node::toString().
HasAllocator()
bool efd::HasAllocator (EnumAllocator key)
Returns true if there is an allocator mapped by key;.
Definition at line 64 of file Allocators.cpp.
HasArchitecture()
bool efd::HasArchitecture (EnumArchitecture key)
Returns true if there is an architecture mapped by key;.
Definition at line 83 of file Architectures.cpp.
IdentityMapping()
efd::Mapping efd::IdentityMapping (uint32_t progQ)
Returns an identity mapping.
Definition at line 67 of file QbitAllocator.cpp.
InfoLog()
std::ostream & efd::InfoLog (std::string file = "", uint32_t line = 0)
Returns a stream object for logging information.
Definition at line 39 of file Defs.cpp.
InitializeAllArchitectures()
void efd::InitializeAllArchitectures ()
Registers all available architectures in the register.
Definition at line 74 of file Architectures.cpp.
Referenced by main().
InitializeAllQbitAllocators()
void efd::InitializeAllQbitAllocators ()
Definition at line 72 of file Allocators.cpp.
Referenced by main().
InlineGate()
void efd::InlineGate (QModule::Ref qmod, NDQOp::Ref qop)
If found, inlines the gate that qop calls.
Definition at line 427 of file Utils.cpp.
References efd::Node::apply(), efd::Node::clone(), ERR, EXIT_unknown_resource, EXIT_unreachable, ExitWith(), efd::NDGateSign::getArgs(), efd::NDQOp::getArgs(), efd::Node::getChild(), efd::Node::getChildNumber(), efd::NDGateDecl::getGOpList(), efd::NDQOp::getId(), efd::Node::getParent(), efd::NDGateSign::getQArgs(), efd::NDQOp::getQArgs(), efd::QModule::getQGate(), efd::NDValue< T >::getVal(), efd::QModule::replaceStatement(), and efd::Node::toString().
Referenced by efd::QModule::inlineCall().
instanceOf()
template<typename TargetTy , typename SrcTy > bool efd::instanceOf (const SrcTy * src)
Returns true if the pointer src is of class TargetTy.
Definition at line 8 of file RTTI.h.
InvertMapping()
efd::InverseMap efd::InvertMapping (uint32_t archQ, Mapping mapping, bool fill = true)
Generates an assignment mapping (maps the architecture's qubits to the logical ones) of size archQ.
Definition at line 25 of file QbitAllocator.cpp.
Referenced by efd::QbitterSolBuilder::build(), efd::PathGuidedSolBuilder::build(), efd::GreedyCktQAllocator::buildStdSolution(), efd::DynprogQAllocator::buildStdSolution(), Fill(), and efd::GeoNearestLQPProcessor::process().
IsCNOTGateCall()
bool efd::IsCNOTGateCall (Node::Ref ref)
Returns whether ref is a CNOT gate.
This is used because there may be gates like the standard library 'cx'.
Definition at line 101 of file Utils.cpp.
References efd::Node::getKind(), efd::Node::getOperation(), efd::Node::K_QOP_CX, efd::Node::K_QOP_GEN, and StdLibCX.
IsIntrinsicGateCall()
bool efd::IsIntrinsicGateCall (Node::Ref ref)
Returns whether ref is (or should be) an intrinsic gate.
Definition at line 116 of file Utils.cpp.
References efd::NDQOpSwap::IdStr, efd::NDQOpLongCX::IdStr, and efd::NDQOpRevCX::IdStr.
Referenced by GetIntrinsicKind().
MappingToString()
std::string efd::MappingToString (Mapping m)
Prints the mapping m to a string and returns it.
Definition at line 77 of file QbitAllocator.cpp.
References std::to_string().
Referenced by efd::IBMQAllocator::buildStdSolution(), and efd::StdSolutionImplPass::run().
ParseArguments() [1/2]
void efd::ParseArguments (const int argc, const char ** argv)
Parses the command line arguments (this function should be used in the main function).
Definition at line 233 of file CommandLine.cpp.
Referenced by main(), and ParseArguments().
ParseArguments() [2/2]
void efd::ParseArguments (int argc, char ** argv)
Definition at line 227 of file CommandLine.cpp.
References ParseArguments().
ParseFile() [1/2]
Node::uRef efd::ParseFile (std::string filename, std::string path = "./", bool forceStdLib = true)
Parse filename at path.
Referenced by main(), and efd::QModule::Parse().
ParseFile() [2/2]
QModule::uRef efd::ParseFile (std::string filepath)
Parse file in the path filepath.
Definition at line 84 of file Driver.cpp.
References efd::QModule::Parse().
ParseString()
Node::uRef efd::ParseString (std::string program, bool forceStdLib = true)
Parse the string program.
Referenced by efd::QModule::Create(), and efd::QModule::ParseString().
PrintDependencyGraph()
void efd::PrintDependencyGraph (QModule::Ref qmod, std::ostream & o = std::cout)
Print the dependency graph of the qmod in o.
Definition at line 111 of file Driver.cpp.
PrintStats()
void efd::PrintStats (std::ostream & out = std::cout)
Usually called in the end of the program, i.e. when all statistical data have already been collected.
Definition at line 66 of file Stats.cpp.
PrintToStream()
void efd::PrintToStream (QModule::Ref qmod, std::ostream & o = std::cout, bool pretty = true)
Print qmod to an standard output stream o.
Definition at line 107 of file Driver.cpp.
References efd::QModule::print().
ProcessAST()
void efd::ProcessAST (QModule::Ref qmod, Node::Ref root)
Processes the root node, and transform the entire AST into a QModule.
Definition at line 340 of file Utils.cpp.
References efd::Node::apply().
Referenced by efd::QModule::GetFromAST().
RegisterArchitecture()
void efd::RegisterArchitecture (EnumArchitecture key, ArchRegistry::CtorTy ctor)
Register an architecture, mapping key to ctor.
Definition at line 87 of file Architectures.cpp.
RegisterQbitAllocator()
void efd::RegisterQbitAllocator (EnumAllocator key, AllocatorRegistry::CtorTy ctor)
Registers an allocator, mapping name to ctor.
Definition at line 68 of file Allocators.cpp.
toShared()
template<typename T > std::shared_ptr<T> efd::toShared (std::unique_ptr< T > from) inline
Wrapper function that "transforms" a std::unique_ptr into a std::shared_ptr.
Note that the unique_ptr will lose the reference to the previously pointed object.
Definition at line 57 of file uRefCast.h.
Referenced by efd::WeightedSIMappingFinder::find(), and efd::XbitToNumberVisitor::visit().
uniqueCastBackward()
template<typename T , typename U > std::unique_ptr<T> efd::uniqueCastBackward (std::unique_ptr< U > from)
Uses the RTTI framework to cast backwardly an unique_ptr.
Note that it transfers the ownership. So, if the cast returns an error, by assertion the execution stops.
It casts from a derived class to a base one.
Definition at line 18 of file uRefCast.h.
References ERR, EXIT_unreachable, and ExitWith().
uniqueCastForward()
template<typename T , typename U > std::unique_ptr<T> efd::uniqueCastForward (std::unique_ptr< U > from)
Uses the RTTI framework to cast forwardly an unique_ptr.
Note that it transfers the ownership. So, if the cast returns an error, by assertion the execution stops.
It casts from a base class to a derived one.
Definition at line 39 of file uRefCast.h.
References ERR, EXIT_unreachable, and ExitWith().
WarningLog()
std::ostream & efd::WarningLog (std::string file = "", uint32_t line = 0)
Returns a stream object for logging warnings.
Definition at line 33 of file Defs.cpp.
Variable Documentation
StdLibCX
const std::string efd::StdLibCX = "cx"
Definition at line 99 of file Utils.cpp.
Referenced by IsCNOTGateCall().