Enfield: efd::IBMQAllocator Class Reference
efd::IBMQAllocator Class Reference
Port of IBM's allocator.
#include <IBMQAllocator.h>
Public Types
typedef IBMQAllocator * Ref
typedef std::unique_ptr< IBMQAllocator > uRef
Public Types inherited from efd::QbitAllocator
typedef QbitAllocator * Ref
typedef std::unique_ptr< QbitAllocator > uRef
typedef Solution::Mapping Mapping
typedef std::vector< std::string > BasisVector
typedef DependencyBuilder::DepsSet DepsSet
typedef DependencyBuilder::DepsSet::iterator Iterator
Public Types inherited from efd::PassT< Solution >
typedef PassT< Solution > * Ref
typedef std::shared_ptr< PassT< Solution > > sRef
typedef std::unique_ptr< PassT< Solution > > uRef
Public Types inherited from efd::Pass
enum Kind { K_VOID, K_GEN }
typedef Pass * Ref
typedef std::shared_ptr< Pass > sRef
Public Member Functions
IBMQAllocator (ArchGraph::sRef archGraph)
Solution executeAllocation (QModule::Ref qmod) override
Executes the allocation algorithm after the preprocessing.
Public Member Functions inherited from efd::QbitAllocator
bool run (QModule::Ref qmod) override
void setInlineAll (BasisVector basis={})
Flags the QbitAllocator to inline all gates, but those inside the basis vector, before mapping.
void setDontInline ()
Flags the QbitAllocator not to inline.
Public Member Functions inherited from efd::PassT< Solution >
PassT ()
Solution getData () const
Gets the resulting data.
Solution & getData ()
Public Member Functions inherited from efd::Pass
virtual bool run (QModule *qmod)=0
Runs the pass in the given QModule and returns true if it has modified qmod.
Kind getKind () const
Gets the kind of this pass.
Static Public Member Functions
static uRef Create (ArchGraph::sRef archGraph)
Static Public Member Functions inherited from efd::PassT< Solution >
static bool ClassOf (Pass *ref)
Additional Inherited Members
Protected Member Functions inherited from efd::QbitAllocator
QbitAllocator (ArchGraph::sRef archGraph)
Protected Member Functions inherited from efd::Pass
Pass (Kind k)
Protected Attributes inherited from efd::QbitAllocator
bool mInlineAll
ArchGraph::sRef mArchGraph
BasisVector mBasis
QModule::Ref mMod
uint32_t mVQubits
uint32_t mPQubits
Protected Attributes inherited from efd::PassT< Solution >
Solution mData
Detailed Description
Port of IBM's allocator.
Definition at line 10 of file IBMQAllocator.h.
Member Typedef Documentation
Ref
typedef IBMQAllocator* efd::IBMQAllocator::Ref
Definition at line 12 of file IBMQAllocator.h.
uRef
typedef std::unique_ptr<IBMQAllocator> efd::IBMQAllocator::uRef
Definition at line 13 of file IBMQAllocator.h.
Constructor & Destructor Documentation
IBMQAllocator()
IBMQAllocator::IBMQAllocator (ArchGraph::sRef archGraph)
Definition at line 13 of file IBMQAllocator.cpp.
References efd::QbitAllocator::QbitAllocator().
Referenced by Create().
Member Function Documentation
Create()
IBMQAllocator::uRef IBMQAllocator::Create (ArchGraph::sRef archGraph) static
Definition at line 15 of file IBMQAllocator.cpp.
References IBMQAllocator().
executeAllocation()
Solution IBMQAllocator::executeAllocation (QModule::Ref qmod) override virtual
Executes the allocation algorithm after the preprocessing.
Implements efd::QbitAllocator.
Definition at line 168 of file IBMQAllocator.cpp.
References efd::QModule::clearStatements(), efd::Node::clone(), efd::BFSPathFinder::find(), efd::PassCache::Get(), efd::PassT< T >::getData(), efd::DependencyBuilder::getDeps(), efd::XbitToNumber::getQSize(), efd::Dependencies::getSize(), efd::Opt< T >::getVal(), efd::Graph::hasEdge(), efd::QModule::insertStatementLast(), efd::Operation::K_OP_CNOT, efd::Operation::K_OP_REV, efd::MappingToString(), efd::QbitAllocator::mArchGraph, efd::Solution::mCost, efd::Dep::mFrom, efd::Solution::mInitial, efd::Solution::mOpSeqs, efd::Dep::mTo, efd::DependencyBuilder::mXbitToNumber, efd::Dependencies::operator[](), RevCost, Seed, efd::Graph::size(), efd::Graph::succ(), SwapCost, and efd::Node::toString().
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/IBMQAllocator.h
lib/Transform/Allocators/IBMQAllocator.cpp