Enfield: efd::QbitterSolBuilder Class Reference
efd::QbitterSolBuilder Class Reference
Solves the dependencies using the 'long-cnot' gates.
#include <QbitterSolBuilder.h>
Public Types
typedef QbitterSolBuilder * Ref
typedef std::unique_ptr< QbitterSolBuilder > uRef
Public Types inherited from efd::SolutionBuilder
typedef QbitAllocator::DepsVector DepsVector
typedef SolutionBuilder * Ref
typedef std::shared_ptr< SolutionBuilder > sRef
Public Member Functions
StdSolution build (Mapping initial, DepsVector &deps, ArchGraph::Ref g) override
Constructs a solution (QbitAllocator::Solution) from the mapping initial, with deps dependencies in the architecture g.
Public Member Functions inherited from efd::SolutionBuilder
SolutionBuilder ()
Public Member Functions inherited from efd::BitOptions< SolutionBuilderOptions, SolutionBuilderOptions::KeepStats >
BitOptions ()
void set (SolutionBuilderOptions option, bool value=true)
Sets the bit related to option to value.
bool get (SolutionBuilderOptions option) const
Gets the value related to the bit that option represents.
Static Public Member Functions
static uRef Create ()
Creates an instance of this class.
Detailed Description
Solves the dependencies using the 'long-cnot' gates.
This algorithm was based on the implementation on the link: https://github.com/artiste-qb-net/qubiter/blob/master/Qubiter_to_IBMqasm.py
Definition at line 11 of file QbitterSolBuilder.h.
Member Typedef Documentation
Ref
typedef QbitterSolBuilder* efd::QbitterSolBuilder::Ref
Definition at line 13 of file QbitterSolBuilder.h.
uRef
typedef std::unique_ptr<QbitterSolBuilder> efd::QbitterSolBuilder::uRef
Definition at line 14 of file QbitterSolBuilder.h.
Member Function Documentation
build()
efd::StdSolution efd::QbitterSolBuilder::build (Mapping initial, DepsVector & deps, ArchGraph::Ref g) override virtual
Constructs a solution (QbitAllocator::Solution) from the mapping initial, with deps dependencies in the architecture g.
Implements efd::SolutionBuilder.
Definition at line 5 of file QbitterSolBuilder.cpp.
References ERR, efd::ExitWith(), efd::Graph::hasEdge(), efd::InvertMapping(), efd::ArchGraph::isReverseEdge(), LCXCost, efd::StdSolution::mOpSeqs, efd::Operation::mW, RevCost, and efd::Graph::size().
Create()
efd::QbitterSolBuilder::uRef efd::QbitterSolBuilder::Create () static
Creates an instance of this class.
Definition at line 48 of file QbitterSolBuilder.cpp.
The documentation for this class was generated from the following files:
include/enfield/Transform/Allocators/Simple/QbitterSolBuilder.h
lib/Transform/Allocators/Simple/QbitterSolBuilder.cpp