Enfield: efd::Graph Class Reference
efd::Graph Class Reference
Graph representation.
#include <Graph.h>
Public Types
enum Kind { K_GRAPH, K_WEIGHTED, K_ARCH }
enum Type { Directed, Undirected }
typedef Graph * Ref
typedef std::unique_ptr< Graph > uRef
typedef std::shared_ptr< Graph > sRef
Public Member Functions
Graph (uint32_t n, Type ty=Undirected)
uint32_t inDegree (uint32_t i) const
Return the degree entering the vertex i.
uint32_t outDegree (uint32_t i) const
Return the degree leaving the vertex i.
uint32_t size () const
Return the number of vertices.
std::set< uint32_t > & succ (uint32_t i)
Return the set of succesors of some vertex i.
std::set< uint32_t > & pred (uint32_t i)
Return the set of predecessors of some vertex i.
std::set< uint32_t > adj (uint32_t i) const
Return the set of adjacent vertices of some vertex i.
void putEdge (uint32_t i, uint32_t j)
Inserts an edge (i, j) in the successor's list and an edge (j, i) in the predecessor's list.
bool hasEdge (uint32_t i, uint32_t j)
Returns true whether it has an edge (i, j).
bool isWeighted () const
Returns true if this is a weighted graph.
bool isArch () const
Returns true if this is an architecture graph.
bool isDirectedGraph () const
Returns true if this is a directed graph.
std::string dotify (std::string name="Dump") const
Converts itself to a 'dot' graph representation.
Static Public Member Functions
static bool ClassOf (const Graph *g)
Returns true if g is of this type.
static uRef Create (uint32_t n, Type ty=Undirected)
Encapsulates the creation of a new Graph.
static uRef Read (std::string filepath, Type ty=Undirected)
Parses the file filename into a Graph representation.
static uRef ReadString (std::string graphStr, Type ty=Undirected)
Parses the string graphStr into a Graph representation.
Protected Member Functions
Graph (Kind k, uint32_t n, Type ty=Undirected)
virtual std::string vertexToString (uint32_t i) const
virtual std::string edgeToString (uint32_t i, uint32_t j, std::string op) const
Protected Attributes
Kind mK
uint32_t mN
Type mTy
std::vector< std::set< uint32_t > > mSuccessors
std::vector< std::set< uint32_t > > mPredecessors
Detailed Description
Graph representation.
Definition at line 11 of file Graph.h.
Member Typedef Documentation
Ref
typedef Graph* efd::Graph::Ref
Definition at line 13 of file Graph.h.
sRef
typedef std::shared_ptr<Graph> efd::Graph::sRef
Definition at line 15 of file Graph.h.
uRef
typedef std::unique_ptr<Graph> efd::Graph::uRef
Definition at line 14 of file Graph.h.
Member Enumeration Documentation
Kind
enum efd::Graph::Kind
Enumerator
K_GRAPH
K_WEIGHTED
K_ARCH
Definition at line 17 of file Graph.h.
Type
enum efd::Graph::Type
Enumerator
Directed
Undirected
Definition at line 23 of file Graph.h.
Constructor & Destructor Documentation
Graph() [1/2]
efd::Graph::Graph (Kind k, uint32_t n, Type ty = Undirected) protected
Definition at line 8 of file Graph.cpp.
References mPredecessors, and mSuccessors.
Graph() [2/2]
efd::Graph::Graph (uint32_t n, Type ty = Undirected)
Definition at line 13 of file Graph.cpp.
References mPredecessors, and mSuccessors.
Member Function Documentation
adj()
std::set< uint32_t > efd::Graph::adj (uint32_t i) const
Return the set of adjacent vertices of some vertex i.
Definition at line 46 of file Graph.cpp.
ClassOf()
bool efd::Graph::ClassOf (const Graph * g) static
Returns true if g is of this type.
Definition at line 107 of file Graph.cpp.
Create()
efd::Graph::uRef efd::Graph::Create (uint32_t n, Type ty = Undirected) static
Encapsulates the creation of a new Graph.
Definition at line 111 of file Graph.cpp.
dotify()
std::string efd::Graph::dotify (std::string name = "Dump") const
Converts itself to a 'dot' graph representation.
Definition at line 84 of file Graph.cpp.
edgeToString()
std::string efd::Graph::edgeToString (uint32_t i, uint32_t j, std::string op) const protected virtual
Reimplemented in efd::WeightedGraph< T >.
Definition at line 22 of file Graph.cpp.
hasEdge()
bool efd::Graph::hasEdge (uint32_t i, uint32_t j)
Returns true whether it has an edge (i, j).
Definition at line 57 of file Graph.cpp.
Referenced by efd::QbitterSolBuilder::build().
inDegree()
uint32_t efd::Graph::inDegree (uint32_t i) const
Return the degree entering the vertex i.
Definition at line 26 of file Graph.cpp.
isArch()
bool efd::Graph::isArch () const
Returns true if this is an architecture graph.
Definition at line 76 of file Graph.cpp.
Referenced by efd::ArchGraph::ClassOf().
isDirectedGraph()
bool efd::Graph::isDirectedGraph () const
Returns true if this is a directed graph.
Definition at line 80 of file Graph.cpp.
isWeighted()
bool efd::Graph::isWeighted () const
Returns true if this is a weighted graph.
Definition at line 72 of file Graph.cpp.
Referenced by efd::WeightedGraph< T >::ClassOf(), and efd::WeightedSIFinder< T >::find().
outDegree()
uint32_t efd::Graph::outDegree (uint32_t i) const
Return the degree leaving the vertex i.
Definition at line 30 of file Graph.cpp.
pred()
std::set< uint32_t > & efd::Graph::pred (uint32_t i)
Return the set of predecessors of some vertex i.
Definition at line 42 of file Graph.cpp.
putEdge()
void efd::Graph::putEdge (uint32_t i, uint32_t j)
Inserts an edge (i, j) in the successor's list and an edge (j, i) in the predecessor's list.
Definition at line 62 of file Graph.cpp.
Referenced by efd::WeightedGraph< T >::putEdge().
Read()
efd::Graph::uRef efd::Graph::Read (std::string filepath, Type ty = Undirected) static
Parses the file filename into a Graph representation.
Definition at line 126 of file Graph.cpp.
ReadString()
efd::Graph::uRef efd::Graph::ReadString (std::string graphStr, Type ty = Undirected) static
Parses the string graphStr into a Graph representation.
Definition at line 131 of file Graph.cpp.
size()
uint32_t efd::Graph::size () const
Return the number of vertices.
Definition at line 34 of file Graph.cpp.
Referenced by efd::QbitterSolBuilder::build(), efd::PathGuidedSolBuilder::build(), efd::RandomMappingFinder::find(), efd::IdentityMappingFinder::find(), efd::WeightedSIMappingFinder::find(), and efd::GeoNearestLQPProcessor::process().
succ()
std::set< uint32_t > & efd::Graph::succ (uint32_t i)
Return the set of succesors of some vertex i.
Definition at line 38 of file Graph.cpp.
vertexToString()
std::string efd::Graph::vertexToString (uint32_t i) const protected virtual
Reimplemented in efd::ArchGraph.
Definition at line 18 of file Graph.cpp.
References std::to_string().
Member Data Documentation
mK
Kind efd::Graph::mK protected
Definition at line 26 of file Graph.h.
mN
uint32_t efd::Graph::mN protected
Definition at line 27 of file Graph.h.
mPredecessors
std::vector<std::set<uint32_t> > efd::Graph::mPredecessors protected
Definition at line 31 of file Graph.h.
Referenced by Graph().
mSuccessors
std::vector<std::set<uint32_t> > efd::Graph::mSuccessors protected
Definition at line 30 of file Graph.h.
Referenced by Graph().
mTy
Type efd::Graph::mTy protected
Definition at line 28 of file Graph.h.
The documentation for this class was generated from the following files:
include/enfield/Support/Graph.h
lib/Support/Graph.cpp