Enfield: efd::Dependencies Struct Reference
efd::Dependencies Struct Reference
Represents a sequence of dependencies (should be treated as parallel dependencies) for each node.
#include <DependencyBuilderPass.h>
Public Types
typedef std::vector< Dep >::iterator Iterator
typedef std::vector< Dep >::const_iterator ConstIterator
Public Member Functions
const Dep & operator[] (uint32_t i) const
Forwards to the mDeps attribute.
Dep & operator[] (uint32_t i)
Forwards to the mDeps attribute.
bool isEmpty () const
Forwards to the mDeps attribute.
uint32_t getSize () const
Forwards to the mDeps attribute.
Iterator begin ()
Forwards to the mDeps attribute.
ConstIterator begin () const
Forwards to the mDeps attribute.
Iterator end ()
Forwards to the mDeps attribute.
ConstIterator end () const
Forwards to the mDeps attribute.
Public Attributes
std::vector< Dep > mDeps
Node::Ref mCallPoint
Detailed Description
Represents a sequence of dependencies (should be treated as parallel dependencies) for each node.
Definition at line 24 of file DependencyBuilderPass.h.
Member Typedef Documentation
ConstIterator
typedef std::vector<Dep>::const_iterator efd::Dependencies::ConstIterator
Definition at line 26 of file DependencyBuilderPass.h.
Iterator
typedef std::vector<Dep>::iterator efd::Dependencies::Iterator
Definition at line 25 of file DependencyBuilderPass.h.
Member Function Documentation
begin() [1/2]
efd::Dependencies::Iterator efd::Dependencies::begin ()
Forwards to the mDeps attribute.
Definition at line 26 of file DependencyBuilderPass.cpp.
References mDeps.
begin() [2/2]
efd::Dependencies::ConstIterator efd::Dependencies::begin () const
Forwards to the mDeps attribute.
Definition at line 30 of file DependencyBuilderPass.cpp.
References mDeps.
end() [1/2]
efd::Dependencies::Iterator efd::Dependencies::end ()
Forwards to the mDeps attribute.
Definition at line 34 of file DependencyBuilderPass.cpp.
References mDeps.
end() [2/2]
efd::Dependencies::ConstIterator efd::Dependencies::end () const
Forwards to the mDeps attribute.
Definition at line 38 of file DependencyBuilderPass.cpp.
References mDeps.
getSize()
uint32_t efd::Dependencies::getSize () const
Forwards to the mDeps attribute.
Definition at line 14 of file DependencyBuilderPass.cpp.
References mDeps.
Referenced by efd::GreedyCktQAllocator::executeAllocation(), efd::IBMQAllocator::executeAllocation(), efd::BoundedSIDepSolver::solve(), and efd::DynprogDepSolver::solve().
isEmpty()
bool efd::Dependencies::isEmpty () const
Forwards to the mDeps attribute.
Definition at line 10 of file DependencyBuilderPass.cpp.
References mDeps.
Referenced by efd::DependencyBuilderVisitor::visit().
operator[]() [1/2]
const efd::Dep & efd::Dependencies::operator[] (uint32_t i) const
Forwards to the mDeps attribute.
Definition at line 18 of file DependencyBuilderPass.cpp.
References mDeps.
operator[]() [2/2]
efd::Dep & efd::Dependencies::operator[] (uint32_t i)
Forwards to the mDeps attribute.
Definition at line 22 of file DependencyBuilderPass.cpp.
References mDeps.
Referenced by efd::QbitterSolBuilder::build(), efd::PathGuidedSolBuilder::build(), efd::GreedyCktQAllocator::executeAllocation(), efd::IBMQAllocator::executeAllocation(), efd::BoundedSIDepSolver::solve(), and efd::DynprogDepSolver::solve().
Member Data Documentation
mCallPoint
Node::Ref efd::Dependencies::mCallPoint
Definition at line 29 of file DependencyBuilderPass.h.
Referenced by efd::QbitterSolBuilder::build(), efd::PathGuidedSolBuilder::build(), efd::BoundedSIDepSolver::solve(), and efd::DynprogDepSolver::solve().
mDeps
std::vector<Dep> efd::Dependencies::mDeps
Definition at line 28 of file DependencyBuilderPass.h.
Referenced by begin(), end(), efd::WeightedSIMappingFinder::find(), getSize(), isEmpty(), operator[](), efd::QbitAllocator::run(), efd::DynprogDepSolver::solve(), and efd::DependencyBuilderVisitor::visit().
The documentation for this struct was generated from the following files:
include/enfield/Transform/DependencyBuilderPass.h
lib/Transform/DependencyBuilderPass.cpp