Enfield: efd::TokenSwapFinder Class Reference
efd::TokenSwapFinder Class Reference abstract
Interface for solving the Token Swap Problem.
#include <TokenSwapFinder.h>
Public Types
typedef TokenSwapFinder * Ref
typedef std::unique_ptr< TokenSwapFinder > uRef
Public Member Functions
void setGraph (Graph::Ref graph)
Sets the Graph.
SwapSeq find (const InverseMap &from, const InverseMap &to)
Finds a swap sequence to reach to from from.
Protected Member Functions
TokenSwapFinder ()
void checkGraphSet ()
virtual void preprocess ()=0
virtual SwapSeq findImpl (const InverseMap &from, const InverseMap &to)=0
Protected Attributes
Graph::Ref mG
Detailed Description
Interface for solving the Token Swap Problem.
Definition at line 9 of file TokenSwapFinder.h.
Member Typedef Documentation
Ref
typedef TokenSwapFinder* efd::TokenSwapFinder::Ref
Definition at line 11 of file TokenSwapFinder.h.
uRef
typedef std::unique_ptr<TokenSwapFinder> efd::TokenSwapFinder::uRef
Definition at line 12 of file TokenSwapFinder.h.
Constructor & Destructor Documentation
TokenSwapFinder()
TokenSwapFinder::TokenSwapFinder () protected
Definition at line 5 of file TokenSwapFinder.cpp.
Member Function Documentation
checkGraphSet()
void TokenSwapFinder::checkGraphSet () protected
Definition at line 7 of file TokenSwapFinder.cpp.
References ERR, efd::EXIT_unreachable, efd::ExitWith(), and mG.
Referenced by find().
find()
SwapSeq TokenSwapFinder::find (const InverseMap & from, const InverseMap & to)
Finds a swap sequence to reach to from from.
Definition at line 19 of file TokenSwapFinder.cpp.
References checkGraphSet(), and findImpl().
Referenced by efd::DynprogQAllocator::buildStdSolution().
findImpl()
virtual SwapSeq efd::TokenSwapFinder::findImpl (const InverseMap & from, const InverseMap & to) protected pure virtual
Implemented in efd::ApproxTSFinder.
Referenced by find().
preprocess()
virtual void efd::TokenSwapFinder::preprocess () protected pure virtual
Implemented in efd::ApproxTSFinder.
Referenced by setGraph().
setGraph()
void TokenSwapFinder::setGraph (Graph::Ref graph)
Sets the Graph.
Definition at line 14 of file TokenSwapFinder.cpp.
References mG, and preprocess().
Referenced by efd::DynprogQAllocator::buildStdSolution().
Member Data Documentation
mG
Graph::Ref efd::TokenSwapFinder::mG protected
Definition at line 15 of file TokenSwapFinder.h.
Referenced by checkGraphSet(), and setGraph().
The documentation for this class was generated from the following files:
include/enfield/Support/TokenSwapFinder.h
lib/Support/TokenSwapFinder.cpp