Enfield: efd::Opt< T > Class Template Reference
efd::Opt< T > Class Template Reference
Class used to declare the command line options available.
#include <CommandLine.h>
Public Member Functions
Opt (std::string name, std::string description, bool isRequired=false)
Opt (std::string name, std::string description, T def, bool isRequired=false)
const T & getVal () const
Gets a const reference to the value of this command line option.
std::vector< std::string > getPossibleValuesList () override
Return list of possible values for this option.
uint32_t argsConsumed () override
Type sensitive number of arguments consumed.
std::string getStringVal () override
Return the value in a string representation.
template<>
uint32_t argsConsumed ()
Type sensitive number of arguments consumed.
template<>
std::string getStringVal ()
Return the value in a string representation.
template<>
std::string getStringVal ()
Return the value in a string representation.
template<>
std::string getStringVal ()
Return the value in a string representation.
template<>
uint32_t argsConsumed ()
Type sensitive number of arguments consumed.
template<>
std::string getStringVal ()
Return the value in a string representation.
template<>
std::string getStringVal ()
Return the value in a string representation.
template<>
std::string getStringVal ()
Return the value in a string representation.
template<>
std::string getStringVal ()
Return the value in a string representation.
Public Member Functions inherited from efd::OptBase
OptBase (std::string name, std::string description, bool isRequired)
Constructs and inserts itself in the command line options container.
virtual ~OptBase ()
Destructs and removes itself from the command line options container.
bool isParsed ()
True if this option has already been parsed.
bool isRequired ()
True if the option was constructed as 'required'.
void parse (std::vector< std::string > args)
Calls the parseImpl function, which is type-dependent.
Protected Member Functions
void parseImpl (std::vector< std::string > args) override
Type sensitive parsing of the arguments itself.
Friends
struct ParseOptTrait< T >
Additional Inherited Members
Public Attributes inherited from efd::OptBase
std::string mName
Command line string that represents the option.
std::string mDescription
Description of the command line option.
Detailed Description
template<typename T>
class efd::Opt< T >
Class used to declare the command line options available.
Definition at line 12 of file CommandLine.h.
Constructor & Destructor Documentation
Opt() [1/2]
template<typename T > efd::Opt< T >::Opt (std::string name, std::string description, bool isRequired = false)
Definition at line 149 of file CommandLine.h.
Opt() [2/2]
template<typename T > efd::Opt< T >::Opt (std::string name, std::string description, T def, bool isRequired = false)
Definition at line 153 of file CommandLine.h.
Member Function Documentation
argsConsumed() [1/3]
template<> uint32_t efd::Opt< bool >::argsConsumed () virtual
Type sensitive number of arguments consumed.
Implements efd::OptBase.
Definition at line 116 of file CommandLine.cpp.
argsConsumed() [2/3]
template<typename T > uint32_t efd::Opt< T >::argsConsumed () override virtual
Type sensitive number of arguments consumed.
Implements efd::OptBase.
Definition at line 170 of file CommandLine.h.
argsConsumed() [3/3]
template<> uint32_t efd::Opt< bool >::argsConsumed () virtual
Type sensitive number of arguments consumed.
Implements efd::OptBase.
getPossibleValuesList()
template<typename T > std::vector< std::string > efd::Opt< T >::getPossibleValuesList () override virtual
Return list of possible values for this option.
Implements efd::OptBase.
Definition at line 165 of file CommandLine.h.
References efd::PossibleValuesListTrait< T >::Get().
getStringVal() [1/8]
template<> std::string efd::Opt< MapGateUInt >::getStringVal () virtual
Return the value in a string representation.
Implements efd::OptBase.
Definition at line 25 of file Enfield.cpp.
References std::to_string().
getStringVal() [2/8]
template<typename T > std::string efd::Opt< T >::getStringVal () override virtual
Return the value in a string representation.
Implements efd::OptBase.
Definition at line 173 of file CommandLine.h.
References std::to_string().
getStringVal() [3/8]
template<> std::string efd::Opt< bool >::getStringVal () virtual
Return the value in a string representation.
Implements efd::OptBase.
Definition at line 121 of file CommandLine.cpp.
getStringVal() [4/8]
template<> std::string efd::Opt< std::string >::getStringVal () virtual
Return the value in a string representation.
Implements efd::OptBase.
Definition at line 127 of file CommandLine.cpp.
getStringVal() [5/8]
template<> std::string efd::Opt< bool >::getStringVal () virtual
Return the value in a string representation.
Implements efd::OptBase.
getStringVal() [6/8]
template<> std::string efd::Opt< std::vector< std::string > >::getStringVal () virtual
Return the value in a string representation.
Implements efd::OptBase.
Definition at line 132 of file CommandLine.cpp.
getStringVal() [7/8]
template<> std::string efd::Opt< std::string >::getStringVal () virtual
Return the value in a string representation.
Implements efd::OptBase.
getStringVal() [8/8]
template<> std::string efd::Opt< std::vector< std::string > >::getStringVal () virtual
Return the value in a string representation.
Implements efd::OptBase.
getVal()
template<typename T > const T & efd::Opt< T >::getVal () const
Gets a const reference to the value of this command line option.
Definition at line 157 of file CommandLine.h.
parseImpl()
template<typename T > void efd::Opt< T >::parseImpl (std::vector< std::string > args) override protected virtual
Type sensitive parsing of the arguments itself.
Implements efd::OptBase.
Definition at line 160 of file CommandLine.h.
References efd::ParseOptTrait< T >::Run().
Friends And Related Function Documentation
ParseOptTrait< T >
template<typename T> friend struct ParseOptTrait< T > friend
Definition at line 122 of file CommandLine.h.
The documentation for this class was generated from the following file:
include/enfield/Support/CommandLine.h