Enfield: efd::XbitToNumber Struct Reference
efd::XbitToNumber Struct Reference
Maps every quantum and classic bit (not register) to a number inside a vector.
#include <XbitToNumberPass.h>
Classes
struct XbitInfo
Public Types
typedef std::map< std::string, XbitInfo > XbitMap
typedef std::map< std::string, std::vector< uint32_t > > XRegMap
Public Member Functions
const XbitMap & getQbitMap (NDGateDecl::Ref gate=nullptr) const
Gets a constant reference to the mapping of qubtis of a gate.
std::vector< uint32_t > getRegUIds (std::string id) const
Returns a list of uids that relate to a given register.
uint32_t getQUId (std::string id, NDGateDecl::Ref gate=nullptr) const
Returns an uint32_t number representing the qubit in this specific gate (if any).
uint32_t getCUId (std::string id) const
Returns an uint32_t number representing the classic bit;.
uint32_t getQSize (NDGateDecl::Ref gate=nullptr) const
Returns the number of qbits in a given gate (if any).
uint32_t getCSize () const
Returns the number of cbits in a given gate (if any).
std::string getQStrId (uint32_t id, NDGateDecl::Ref gate=nullptr) const
Returns the std::string id representation of the corresponding qubit, represented by uint32_t id in the specific gate (if any).
std::string getCStrId (uint32_t id) const
Returns the std::string id representation of the corresponding classic bit, represented by id.
Node::Ref getQNode (uint32_t id, NDGateDecl::Ref gate=nullptr) const
Get a Node::Ref, representing that qbit.
Node::Ref getCNode (uint32_t id) const
Get a Node::Ref, representing that cbit.
Public Attributes
std::unordered_map< NDGateDecl *, XbitMap > lidQMap
XbitMap gidQMap
XbitMap gidCMap
XRegMap gidRegMap
Detailed Description
Maps every quantum and classic bit (not register) to a number inside a vector.
It also keeps track of the qubits inside every gate declaration. Inside every scope, it maps the qubits existing inside them to an uint32_t number.
Note that if "qreg r[10];" declaration exists, then "r" is not a qbit, but "r[n]" is (where "n" is in "{0 .. 9}").
Definition at line 23 of file XbitToNumberPass.h.
Member Typedef Documentation
XbitMap
typedef std::map<std::string, XbitInfo> efd::XbitToNumber::XbitMap
Definition at line 29 of file XbitToNumberPass.h.
XRegMap
typedef std::map<std::string, std::vector<uint32_t> > efd::XbitToNumber::XRegMap
Definition at line 30 of file XbitToNumberPass.h.
Member Function Documentation
getCNode()
efd::Node::Ref efd::XbitToNumber::getCNode (uint32_t id) const
Get a Node::Ref, representing that cbit.
Definition at line 95 of file XbitToNumberPass.cpp.
getCSize()
uint32_t efd::XbitToNumber::getCSize () const
Returns the number of cbits in a given gate (if any).
Definition at line 54 of file XbitToNumberPass.cpp.
getCStrId()
std::string efd::XbitToNumber::getCStrId (uint32_t id) const
Returns the std::string id representation of the corresponding classic bit, represented by id.
Definition at line 75 of file XbitToNumberPass.cpp.
References ERR, efd::EXIT_unknown_resource, and efd::ExitWith().
getCUId()
uint32_t efd::XbitToNumber::getCUId (std::string id) const
Returns an uint32_t number representing the classic bit;.
Definition at line 41 of file XbitToNumberPass.cpp.
References ERR, efd::EXIT_unknown_resource, and efd::ExitWith().
Referenced by efd::UsedBitsVisitor::visit(), and efd::SemanticVerifierVisitor::visit().
getQbitMap()
const efd::XbitToNumber::XbitMap & efd::XbitToNumber::getQbitMap (NDGateDecl::Ref gate = nullptr) const
Gets a constant reference to the mapping of qubtis of a gate.
Definition at line 11 of file XbitToNumberPass.cpp.
References ERR, efd::EXIT_unknown_resource, efd::ExitWith(), efd::NDDecl::getId(), efd::NDValue< T >::getVal(), gidQMap, and lidQMap.
getQNode()
efd::Node::Ref efd::XbitToNumber::getQNode (uint32_t id, NDGateDecl::Ref gate = nullptr) const
Get a Node::Ref, representing that qbit.
Definition at line 89 of file XbitToNumberPass.cpp.
getQSize()
uint32_t efd::XbitToNumber::getQSize (NDGateDecl::Ref gate = nullptr) const
Returns the number of qbits in a given gate (if any).
Definition at line 49 of file XbitToNumberPass.cpp.
Referenced by efd::UsedBitsVisitor::visit().
getQStrId()
std::string efd::XbitToNumber::getQStrId (uint32_t id, NDGateDecl::Ref gate = nullptr) const
Returns the std::string id representation of the corresponding qubit, represented by uint32_t id in the specific gate (if any).
Definition at line 58 of file XbitToNumberPass.cpp.
References ERR, efd::EXIT_unknown_resource, efd::ExitWith(), efd::NDDecl::getId(), and efd::NDValue< T >::getVal().
getQUId()
uint32_t efd::XbitToNumber::getQUId (std::string id, NDGateDecl::Ref gate = nullptr) const
Returns an uint32_t number representing the qubit in this specific gate (if any).
Definition at line 30 of file XbitToNumberPass.cpp.
References ERR, efd::NDDecl::getId(), and efd::NDValue< T >::getVal().
Referenced by efd::SemanticVerifierVisitor::visit(), efd::NodeRenameVisitor::visitNDQOp(), and efd::UsedBitsVisitor::visitQOp().
getRegUIds()
std::vector< uint32_t > efd::XbitToNumber::getRegUIds (std::string id) const
Returns a list of uids that relate to a given register.
Definition at line 21 of file XbitToNumberPass.cpp.
References ERR, efd::EXIT_unknown_resource, and efd::ExitWith().
Member Data Documentation
gidCMap
XbitMap efd::XbitToNumber::gidCMap
Definition at line 34 of file XbitToNumberPass.h.
gidQMap
XbitMap efd::XbitToNumber::gidQMap
Definition at line 33 of file XbitToNumberPass.h.
Referenced by getQbitMap().
gidRegMap
XRegMap efd::XbitToNumber::gidRegMap
Definition at line 35 of file XbitToNumberPass.h.
lidQMap
std::unordered_map<NDGateDecl*, XbitMap> efd::XbitToNumber::lidQMap
Definition at line 32 of file XbitToNumberPass.h.
Referenced by getQbitMap().
The documentation for this struct was generated from the following files:
include/enfield/Transform/XbitToNumberPass.h
lib/Transform/XbitToNumberPass.cpp