Enfield: efd::NodeRenameVisitor Class Reference
efd::NodeRenameVisitor Class Reference
Public Member Functions
NodeRenameVisitor (Mapping &m, XbitToNumber &xtoN, ArchGraph::Ref archGraph)
void visitNDQOp (NDQOp::Ref qop)
void visit (NDQOpMeasure::Ref ref) override
void visit (NDQOpReset::Ref ref) override
void visit (NDQOpU::Ref ref) override
void visit (NDQOpCX::Ref ref) override
void visit (NDQOpBarrier::Ref ref) override
void visit (NDQOpGen::Ref ref) override
void visit (NDIfStmt::Ref ref) override
Public Member Functions inherited from efd::NodeVisitor
virtual void visit (NDQasmVersion::Ref ref)
virtual void visit (NDInclude::Ref ref)
virtual void visit (NDRegDecl::Ref ref)
virtual void visit (NDGateDecl::Ref ref)
virtual void visit (NDOpaque::Ref ref)
virtual void visit (NDBinOp::Ref ref)
virtual void visit (NDUnaryOp::Ref ref)
virtual void visit (NDIdRef::Ref ref)
virtual void visit (NDList::Ref ref)
virtual void visit (NDStmtList::Ref ref)
virtual void visit (NDGOpList::Ref ref)
virtual void visit (NDValue< std::string >::Ref ref)
virtual void visit (NDValue< IntVal >::Ref ref)
virtual void visit (NDValue< RealVal >::Ref ref)
void visitChildren (Node::Ref ref)
Visits the children of ref.
Additional Inherited Members
Public Types inherited from efd::NodeVisitor
typedef NodeVisitor * Ref
Detailed Description
Definition at line 89 of file BoundedMappingTreeQAllocator.cpp.
Constructor & Destructor Documentation
NodeRenameVisitor()
NodeRenameVisitor::NodeRenameVisitor (Mapping & m, XbitToNumber & xtoN, ArchGraph::Ref archGraph)
Definition at line 112 of file BoundedMappingTreeQAllocator.cpp.
Member Function Documentation
visit() [1/7]
void NodeRenameVisitor::visit (NDQOpMeasure::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 130 of file BoundedMappingTreeQAllocator.cpp.
References visitNDQOp().
visit() [2/7]
void NodeRenameVisitor::visit (NDQOpReset::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 134 of file BoundedMappingTreeQAllocator.cpp.
References visitNDQOp().
visit() [3/7]
void NodeRenameVisitor::visit (NDQOpU::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 138 of file BoundedMappingTreeQAllocator.cpp.
References visitNDQOp().
visit() [4/7]
void NodeRenameVisitor::visit (NDQOpCX::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 142 of file BoundedMappingTreeQAllocator.cpp.
References visitNDQOp().
visit() [5/7]
void NodeRenameVisitor::visit (NDQOpBarrier::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 146 of file BoundedMappingTreeQAllocator.cpp.
References visitNDQOp().
visit() [6/7]
void NodeRenameVisitor::visit (NDQOpGen::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 150 of file BoundedMappingTreeQAllocator.cpp.
References visitNDQOp().
visit() [7/7]
void NodeRenameVisitor::visit (NDIfStmt::Ref ref) override virtual
Reimplemented from efd::NodeVisitor.
Definition at line 154 of file BoundedMappingTreeQAllocator.cpp.
References efd::Node::apply(), and efd::NDIfStmt::getQOp().
visitNDQOp()
void NodeRenameVisitor::visitNDQOp (NDQOp::Ref qop)
Definition at line 117 of file BoundedMappingTreeQAllocator.cpp.
References efd::Node::clone(), efd::NDList::Create(), efd::ArchGraph::getNode(), efd::NDQOp::getQArgs(), efd::XbitToNumber::getQUId(), and efd::NDQOp::setQArgs().
Referenced by visit().
The documentation for this class was generated from the following file:
lib/Transform/Allocators/BoundedMappingTreeQAllocator.cpp