Enfield: efd::Timer Class Reference
efd::Timer Class Reference
Tracks the elapsed time. One should use the methods start and stop in order to track the time of some event.
#include <Timer.h>
Public Member Functions
Timer ()
void start ()
Starts the timer.
void stop ()
Stops the timer.
uint64_t getNanoseconds ()
Gets the number of nanoseconds stored in mDuration.
uint64_t getMicroseconds ()
Gets the number of microseconds stored in mDuration.
uint64_t getMilliseconds ()
Gets the number of milliseconds stored in mDuration.
uint64_t getSeconds ()
Gets the number of seconds stored in mDuration.
Static Public Member Functions
static void Start ()
Starts the static timer.
template<typename T >
static uint64_t Stop ()
Stops the timer and returns the elapsed time in the unit specified in T.
Detailed Description
Tracks the elapsed time. One should use the methods start and stop in order to track the time of some event.
Note that if you use the static members, you will be using a Timer shared between everyone (as it is using a static Timer).
Definition at line 14 of file Timer.h.
Constructor & Destructor Documentation
Timer()
efd::Timer::Timer ()
Definition at line 7 of file Timer.cpp.
Member Function Documentation
getMicroseconds()
uint64_t efd::Timer::getMicroseconds ()
Gets the number of microseconds stored in mDuration.
Definition at line 30 of file Timer.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
getMilliseconds()
uint64_t efd::Timer::getMilliseconds ()
Gets the number of milliseconds stored in mDuration.
Definition at line 39 of file Timer.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
getNanoseconds()
uint64_t efd::Timer::getNanoseconds ()
Gets the number of nanoseconds stored in mDuration.
Definition at line 21 of file Timer.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
getSeconds()
uint64_t efd::Timer::getSeconds ()
Gets the number of seconds stored in mDuration.
Definition at line 48 of file Timer.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
start()
void efd::Timer::start ()
Starts the timer.
Definition at line 10 of file Timer.cpp.
Referenced by efd::QbitAllocator::run().
Start()
void efd::Timer::Start () static
Starts the static timer.
Definition at line 57 of file Timer.cpp.
stop()
void efd::Timer::stop ()
Stops the timer.
Definition at line 15 of file Timer.cpp.
Referenced by efd::QbitAllocator::run(), and Stop().
Stop()
template<typename T > uint64_t efd::Timer::Stop () static
Stops the timer and returns the elapsed time in the unit specified in T.
Definition at line 52 of file Timer.h.
References stop().
The documentation for this class was generated from the following files:
include/enfield/Support/Timer.h
lib/Support/Timer.cpp