Enfield: efd::ArchGraph Class Reference
efd::ArchGraph Class Reference
This is the base class for the architectures that this project will be supporting.
#include <ArchGraph.h>
Public Types
typedef ArchGraph * Ref
typedef std::unique_ptr< ArchGraph > uRef
typedef std::shared_ptr< ArchGraph > sRef
typedef std::vector< std::pair< std::string, uint32_t > > RegsVector
typedef RegsVector::iterator RegsIterator
Public Types inherited from efd::Graph
enum Kind { K_GRAPH, K_WEIGHTED, K_ARCH }
enum Type { Directed, Undirected }
typedef Graph * Ref
typedef std::unique_ptr< Graph > uRef
typedef std::shared_ptr< Graph > sRef
Public Member Functions
Node::Ref getNode (uint32_t i) const
Gets the node corresponding to the uid.
uint32_t putVertex (std::string s)
Creates a string vertex and puts it in the vector.
uint32_t putVertex (Node::uRef node)
Creates a node vertex and puts it in the vector.
void putReg (std::string id, std::string size)
Register the register.
uint32_t getUId (std::string s)
Returns the uint32_t id of the vertex s.
bool hasSId (std::string s) const
Returns true if this architecture has a vertex whose string representation is s.
std::string getSId (uint32_t i)
Returns the std::string id of the vertex whose uid is i.
bool isReverseEdge (uint32_t i, uint32_t j)
Returns true if the edge (i, j) is a reverse edge. i.e.: if (i, j) is not in the graph, but (j, i) is.
bool isGeneric ()
Returns true if this is a generic architechture graph, i.e.: it was not created by any of the architechtures compiled within the program.
RegsIterator reg_begin ()
The begin iterator for the mRegs.
RegsIterator reg_end ()
The end iterator for the mRegs.
Public Member Functions inherited from efd::Graph
Graph (uint32_t n, Type ty=Undirected)
uint32_t inDegree (uint32_t i) const
Return the degree entering the vertex i.
uint32_t outDegree (uint32_t i) const
Return the degree leaving the vertex i.
uint32_t size () const
Return the number of vertices.
std::set< uint32_t > & succ (uint32_t i)
Return the set of succesors of some vertex i.
std::set< uint32_t > & pred (uint32_t i)
Return the set of predecessors of some vertex i.
std::set< uint32_t > adj (uint32_t i) const
Return the set of adjacent vertices of some vertex i.
void putEdge (uint32_t i, uint32_t j)
Inserts an edge (i, j) in the successor's list and an edge (j, i) in the predecessor's list.
bool hasEdge (uint32_t i, uint32_t j)
Returns true whether it has an edge (i, j).
bool isWeighted () const
Returns true if this is a weighted graph.
bool isArch () const
Returns true if this is an architecture graph.
bool isDirectedGraph () const
Returns true if this is a directed graph.
std::string dotify (std::string name="Dump") const
Converts itself to a 'dot' graph representation.
Static Public Member Functions
static bool ClassOf (const Graph *g)
Returns true if g is of this type.
static uRef Create (uint32_t n)
Encapsulates the creation of a new ArchGraph.
static uRef Read (std::string filepath)
Parses the file filename into a ArchGraph representation.
static uRef ReadString (std::string graphStr)
Parses the string graphStr into a ArchGraph representation.
Static Public Member Functions inherited from efd::Graph
static bool ClassOf (const Graph *g)
Returns true if g is of this type.
static uRef Create (uint32_t n, Type ty=Undirected)
Encapsulates the creation of a new Graph.
static uRef Read (std::string filepath, Type ty=Undirected)
Parses the file filename into a Graph representation.
static uRef ReadString (std::string graphStr, Type ty=Undirected)
Parses the string graphStr into a Graph representation.
Protected Member Functions
ArchGraph (uint32_t n, bool isGeneric=true)
std::string vertexToString (uint32_t i) const override
Protected Member Functions inherited from efd::Graph
Graph (Kind k, uint32_t n, Type ty=Undirected)
virtual std::string edgeToString (uint32_t i, uint32_t j, std::string op) const
Protected Attributes
RegsVector mRegs
std::vector< Node::uRef > mNodes
std::vector< std::string > mId
std::unordered_map< std::string, uint32_t > mStrToId
bool mGeneric
uint32_t mVID
Protected Attributes inherited from efd::Graph
Kind mK
uint32_t mN
Type mTy
std::vector< std::set< uint32_t > > mSuccessors
std::vector< std::set< uint32_t > > mPredecessors
Detailed Description
This is the base class for the architectures that this project will be supporting.
Definition at line 10 of file ArchGraph.h.
Member Typedef Documentation
Ref
typedef ArchGraph* efd::ArchGraph::Ref
Definition at line 12 of file ArchGraph.h.
RegsIterator
typedef RegsVector::iterator efd::ArchGraph::RegsIterator
Definition at line 17 of file ArchGraph.h.
RegsVector
typedef std::vector<std::pair<std::string, uint32_t> > efd::ArchGraph::RegsVector
Definition at line 16 of file ArchGraph.h.
sRef
typedef std::shared_ptr<ArchGraph> efd::ArchGraph::sRef
Definition at line 14 of file ArchGraph.h.
uRef
typedef std::unique_ptr<ArchGraph> efd::ArchGraph::uRef
Definition at line 13 of file ArchGraph.h.
Constructor & Destructor Documentation
ArchGraph()
efd::ArchGraph::ArchGraph (uint32_t n, bool isGeneric = true) protected
Definition at line 9 of file ArchGraph.cpp.
Member Function Documentation
ClassOf()
bool efd::ArchGraph::ClassOf (const Graph * g) static
Returns true if g is of this type.
Definition at line 102 of file ArchGraph.cpp.
References efd::Graph::isArch().
Create()
std::unique_ptr< efd::ArchGraph > efd::ArchGraph::Create (uint32_t n) static
Encapsulates the creation of a new ArchGraph.
Definition at line 106 of file ArchGraph.cpp.
getNode()
efd::Node::Ref efd::ArchGraph::getNode (uint32_t i) const
Gets the node corresponding to the uid.
Definition at line 29 of file ArchGraph.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
Referenced by efd::NodeRenameVisitor::visitNDQOp().
getSId()
std::string efd::ArchGraph::getSId (uint32_t i)
Returns the std::string id of the vertex whose uid is i.
Definition at line 75 of file ArchGraph.cpp.
References ERR, efd::EXIT_unreachable, and efd::ExitWith().
getUId()
uint32_t efd::ArchGraph::getUId (std::string s)
Returns the uint32_t id of the vertex s.
Definition at line 63 of file ArchGraph.cpp.
References ERR, efd::EXIT_unknown_resource, and efd::ExitWith().
hasSId()
bool efd::ArchGraph::hasSId (std::string s) const
Returns true if this architecture has a vertex whose string representation is s.
Definition at line 71 of file ArchGraph.cpp.
isGeneric()
bool efd::ArchGraph::isGeneric ()
Returns true if this is a generic architechture graph, i.e.: it was not created by any of the architechtures compiled within the program.
Definition at line 90 of file ArchGraph.cpp.
isReverseEdge()
bool efd::ArchGraph::isReverseEdge (uint32_t i, uint32_t j)
Returns true if the edge (i, j) is a reverse edge. i.e.: if (i, j) is not in the graph, but (j, i) is.
Definition at line 84 of file ArchGraph.cpp.
Referenced by efd::QbitterSolBuilder::build(), and efd::PathGuidedSolBuilder::build().
putReg()
void efd::ArchGraph::putReg (std::string id, std::string size)
Register the register.
Definition at line 59 of file ArchGraph.cpp.
putVertex() [1/2]
uint32_t efd::ArchGraph::putVertex (std::string s)
Creates a string vertex and puts it in the vector.
Definition at line 38 of file ArchGraph.cpp.
putVertex() [2/2]
uint32_t efd::ArchGraph::putVertex (Node::uRef node)
Creates a node vertex and puts it in the vector.
Definition at line 48 of file ArchGraph.cpp.
Read()
std::unique_ptr< efd::ArchGraph > efd::ArchGraph::Read (std::string filepath) static
Parses the file filename into a ArchGraph representation.
Definition at line 139 of file ArchGraph.cpp.
ReadString()
std::unique_ptr< efd::ArchGraph > efd::ArchGraph::ReadString (std::string graphStr) static
Parses the string graphStr into a ArchGraph representation.
Definition at line 144 of file ArchGraph.cpp.
reg_begin()
efd::ArchGraph::RegsIterator efd::ArchGraph::reg_begin ()
The begin iterator for the mRegs.
Definition at line 94 of file ArchGraph.cpp.
reg_end()
efd::ArchGraph::RegsIterator efd::ArchGraph::reg_end ()
The end iterator for the mRegs.
Definition at line 98 of file ArchGraph.cpp.
vertexToString()
std::string efd::ArchGraph::vertexToString (uint32_t i) const override protected virtual
Reimplemented from efd::Graph.
Definition at line 12 of file ArchGraph.cpp.
Member Data Documentation
mGeneric
bool efd::ArchGraph::mGeneric protected
Definition at line 26 of file ArchGraph.h.
mId
std::vector<std::string> efd::ArchGraph::mId protected
Definition at line 23 of file ArchGraph.h.
mNodes
std::vector<Node::uRef> efd::ArchGraph::mNodes protected
Definition at line 21 of file ArchGraph.h.
mRegs
RegsVector efd::ArchGraph::mRegs protected
Definition at line 20 of file ArchGraph.h.
mStrToId
std::unordered_map<std::string, uint32_t> efd::ArchGraph::mStrToId protected
Definition at line 24 of file ArchGraph.h.
mVID
uint32_t efd::ArchGraph::mVID protected
Definition at line 27 of file ArchGraph.h.
The documentation for this class was generated from the following files:
include/enfield/Arch/ArchGraph.h
lib/Arch/ArchGraph.cpp