Enfield: efd::CircuitGraph::Iterator Class Reference
efd::CircuitGraph::Iterator Class Reference
Abstracts the iteration of the CircuitGraph.
#include <CircuitGraph.h>
Public Member Functions
Iterator ()
bool next (Xbit xbit)
Advances the bit xbit.
bool next (uint32_t id)
bool back (Xbit xbit)
Retreats the bit xbit.
bool back (uint32_t id)
Node::Ref get (Xbit xbit)
Returns the Node::Ref for the bit xbit.
Node::Ref get (uint32_t id)
CircuitNode::sRef operator[] (Xbit xbit)
CircuitNode::sRef operator[] (uint32_t id)
Friends
class CircuitGraph
Detailed Description
Abstracts the iteration of the CircuitGraph.
Definition at line 89 of file CircuitGraph.h.
Constructor & Destructor Documentation
Iterator()
CircuitGraph::Iterator::Iterator ()
Definition at line 119 of file CircuitGraph.cpp.
Member Function Documentation
back() [1/2]
bool CircuitGraph::Iterator::back (Xbit xbit)
Retreats the bit xbit.
Definition at line 138 of file CircuitGraph.cpp.
References efd::Xbit::getRealId().
back() [2/2]
bool CircuitGraph::Iterator::back (uint32_t id)
Definition at line 132 of file CircuitGraph.cpp.
get() [1/2]
Node::Ref CircuitGraph::Iterator::get (Xbit xbit)
Returns the Node::Ref for the bit xbit.
Definition at line 147 of file CircuitGraph.cpp.
References efd::Xbit::getRealId().
get() [2/2]
Node::Ref CircuitGraph::Iterator::get (uint32_t id)
Definition at line 143 of file CircuitGraph.cpp.
next() [1/2]
bool CircuitGraph::Iterator::next (Xbit xbit)
Advances the bit xbit.
Definition at line 127 of file CircuitGraph.cpp.
References efd::Xbit::getRealId().
Referenced by efd::CNOTLBOWrapperPass::generate(), and efd::SemanticVerifierVisitor::SemanticVerifierVisitor().
next() [2/2]
bool CircuitGraph::Iterator::next (uint32_t id)
Definition at line 121 of file CircuitGraph.cpp.
operator[]() [1/2]
CircuitGraph::CircuitNode::sRef CircuitGraph::Iterator::operator[] (Xbit xbit)
Definition at line 156 of file CircuitGraph.cpp.
References efd::Xbit::getRealId().
operator[]() [2/2]
CircuitGraph::CircuitNode::sRef CircuitGraph::Iterator::operator[] (uint32_t id)
Definition at line 152 of file CircuitGraph.cpp.
Friends And Related Function Documentation
CircuitGraph
friend class CircuitGraph friend
Definition at line 115 of file CircuitGraph.h.
The documentation for this class was generated from the following files:
include/enfield/Transform/CircuitGraph.h
lib/Transform/CircuitGraph.cpp